import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - IntersectionType
const IntersectionTypeIntersectionTypeLiteralWithParenthesizedTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = 1;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithParenthesizedTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = 1;
const RemoveIntersectionTypeParenthesizedTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithParenthesizedTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["ParenthesizedType"]["String"] = 1;
const RemoveIntersectionTypeParenthesizedTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithParenthesizedTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = 1;
const RemoveIntersectionTypeParenthesizedTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithParenthesizedTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = 1;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithParenthesizedTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = 1;
const RemoveIntersectionTypeParenthesizedTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithTypeReferenceBuiltinLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferenceBuiltinObject: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferenceBuiltinString: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferenceBuiltinNumber: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferenceBuiltinBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferenceBuiltinAny: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithTypeReferencePredefinedLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferencePredefinedObject: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferencePredefinedString: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferencePredefinedNumber: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferencePredefinedBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeReferencePredefinedAny: Defaults["IntersectionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithUnionTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["UnionType"]["Literal"] = 1;
const RemoveIntersectionTypeUnionTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithUnionTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["UnionType"]["Object"] = 1;
const RemoveIntersectionTypeUnionTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithUnionTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["UnionType"]["String"] = 1;
const RemoveIntersectionTypeUnionTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithUnionTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["UnionType"]["Number"] = 1;
const RemoveIntersectionTypeUnionTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithUnionTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["UnionType"]["Boolean"] = 1;
const RemoveIntersectionTypeUnionTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithUnionTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["UnionType"]["Any"] = 1;
const RemoveIntersectionTypeUnionTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["IntersectionType"]["Literal"] = 1;
const RemoveIntersectionTypeIntersectionTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithIntersectionTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["IntersectionType"]["Object"] = 1;
const RemoveIntersectionTypeIntersectionTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithIntersectionTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["IntersectionType"]["String"] = 1;
const RemoveIntersectionTypeIntersectionTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithIntersectionTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["IntersectionType"]["Number"] = 1;
const RemoveIntersectionTypeIntersectionTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithIntersectionTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = 1;
const RemoveIntersectionTypeIntersectionTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithIntersectionTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["IntersectionType"]["Any"] = 1;
const RemoveIntersectionTypeIntersectionTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithTypeLiteralLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = 1;
const RemoveIntersectionTypeTypeLiteralLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeLiteralObject: Defaults["IntersectionType"]["Literal"] & Defaults["TypeLiteral"]["Object"] = 1;
const RemoveIntersectionTypeTypeLiteralObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeLiteralString: Defaults["IntersectionType"]["Literal"] & Defaults["TypeLiteral"]["String"] = 1;
const RemoveIntersectionTypeTypeLiteralStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeLiteralNumber: Defaults["IntersectionType"]["Literal"] & Defaults["TypeLiteral"]["Number"] = 1;
const RemoveIntersectionTypeTypeLiteralNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeLiteralBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeLiteralBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTypeLiteralAny: Defaults["IntersectionType"]["Literal"] & Defaults["TypeLiteral"]["Any"] = 1;
const RemoveIntersectionTypeTypeLiteralAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithTupleTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["TupleType"]["Literal"] = 1;
const RemoveIntersectionTypeTupleTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTupleTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["TupleType"]["Object"] = 1;
const RemoveIntersectionTypeTupleTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTupleTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["TupleType"]["String"] = 1;
const RemoveIntersectionTypeTupleTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTupleTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["TupleType"]["Number"] = 1;
const RemoveIntersectionTypeTupleTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTupleTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["TupleType"]["Boolean"] = 1;
const RemoveIntersectionTypeTupleTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithTupleTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["TupleType"]["Any"] = 1;
const RemoveIntersectionTypeTupleTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithArrayTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["ArrayType"]["Literal"] = 1;
const RemoveIntersectionTypeArrayTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithArrayTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["ArrayType"]["Object"] = 1;
const RemoveIntersectionTypeArrayTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithArrayTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["ArrayType"]["String"] = 1;
const RemoveIntersectionTypeArrayTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithArrayTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["ArrayType"]["Number"] = 1;
const RemoveIntersectionTypeArrayTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithArrayTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["ArrayType"]["Boolean"] = 1;
const RemoveIntersectionTypeArrayTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithArrayTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["ArrayType"]["Any"] = 1;
const RemoveIntersectionTypeArrayTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithFunctionTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["FunctionType"]["Literal"] = 1;
const RemoveIntersectionTypeFunctionTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithFunctionTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["FunctionType"]["Object"] = 1;
const RemoveIntersectionTypeFunctionTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithFunctionTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["FunctionType"]["String"] = 1;
const RemoveIntersectionTypeFunctionTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithFunctionTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["FunctionType"]["Number"] = 1;
const RemoveIntersectionTypeFunctionTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithFunctionTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["FunctionType"]["Boolean"] = 1;
const RemoveIntersectionTypeFunctionTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithFunctionTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["FunctionType"]["Any"] = 1;
const RemoveIntersectionTypeFunctionTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeLiteralWithConstructorTypeLiteral: Defaults["IntersectionType"]["Literal"] & Defaults["ConstructorType"]["Literal"] = 1;
const RemoveIntersectionTypeConstructorTypeLiteralFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithConstructorTypeObject: Defaults["IntersectionType"]["Literal"] & Defaults["ConstructorType"]["Object"] = 1;
const RemoveIntersectionTypeConstructorTypeObjectFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithConstructorTypeString: Defaults["IntersectionType"]["Literal"] & Defaults["ConstructorType"]["String"] = 1;
const RemoveIntersectionTypeConstructorTypeStringFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithConstructorTypeNumber: Defaults["IntersectionType"]["Literal"] & Defaults["ConstructorType"]["Number"] = 1;
const RemoveIntersectionTypeConstructorTypeNumberFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithConstructorTypeBoolean: Defaults["IntersectionType"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = 1;
const RemoveIntersectionTypeConstructorTypeBooleanFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1
const IntersectionTypeIntersectionTypeLiteralWithConstructorTypeAny: Defaults["IntersectionType"]["Literal"] & Defaults["ConstructorType"]["Any"] = 1;
const RemoveIntersectionTypeConstructorTypeAnyFromIntersectionTypeLiteral: Defaults["IntersectionType"]["Literal"]= 1

const IntersectionTypeIntersectionTypeObjectWithParenthesizedTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = {};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithParenthesizedTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["ParenthesizedType"]["Object"] = {};
const RemoveIntersectionTypeParenthesizedTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithParenthesizedTypeString: Defaults["IntersectionType"]["Object"] & Defaults["ParenthesizedType"]["String"] = {};
const RemoveIntersectionTypeParenthesizedTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithParenthesizedTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["ParenthesizedType"]["Number"] = {};
const RemoveIntersectionTypeParenthesizedTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithParenthesizedTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = {};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithParenthesizedTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["ParenthesizedType"]["Any"] = {};
const RemoveIntersectionTypeParenthesizedTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithTypeReferenceBuiltinLiteral: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferenceBuiltinObject: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferenceBuiltinString: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferenceBuiltinNumber: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferenceBuiltinBoolean: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferenceBuiltinAny: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithTypeReferencePredefinedLiteral: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferencePredefinedObject: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferencePredefinedString: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferencePredefinedNumber: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferencePredefinedBoolean: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeReferencePredefinedAny: Defaults["IntersectionType"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithUnionTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["UnionType"]["Literal"] = {};
const RemoveIntersectionTypeUnionTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithUnionTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["UnionType"]["Object"] = {};
const RemoveIntersectionTypeUnionTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithUnionTypeString: Defaults["IntersectionType"]["Object"] & Defaults["UnionType"]["String"] = {};
const RemoveIntersectionTypeUnionTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithUnionTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["UnionType"]["Number"] = {};
const RemoveIntersectionTypeUnionTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithUnionTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["UnionType"]["Boolean"] = {};
const RemoveIntersectionTypeUnionTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithUnionTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["UnionType"]["Any"] = {};
const RemoveIntersectionTypeUnionTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithIntersectionTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["IntersectionType"]["Literal"] = {};
const RemoveIntersectionTypeIntersectionTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithIntersectionTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["IntersectionType"]["Object"] = {};
const RemoveIntersectionTypeIntersectionTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithIntersectionTypeString: Defaults["IntersectionType"]["Object"] & Defaults["IntersectionType"]["String"] = {};
const RemoveIntersectionTypeIntersectionTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithIntersectionTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["IntersectionType"]["Number"] = {};
const RemoveIntersectionTypeIntersectionTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithIntersectionTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["IntersectionType"]["Boolean"] = {};
const RemoveIntersectionTypeIntersectionTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithIntersectionTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["IntersectionType"]["Any"] = {};
const RemoveIntersectionTypeIntersectionTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithTypeLiteralLiteral: Defaults["IntersectionType"]["Object"] & Defaults["TypeLiteral"]["Literal"] = {};
const RemoveIntersectionTypeTypeLiteralLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeLiteralObject: Defaults["IntersectionType"]["Object"] & Defaults["TypeLiteral"]["Object"] = {};
const RemoveIntersectionTypeTypeLiteralObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeLiteralString: Defaults["IntersectionType"]["Object"] & Defaults["TypeLiteral"]["String"] = {};
const RemoveIntersectionTypeTypeLiteralStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeLiteralNumber: Defaults["IntersectionType"]["Object"] & Defaults["TypeLiteral"]["Number"] = {};
const RemoveIntersectionTypeTypeLiteralNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeLiteralBoolean: Defaults["IntersectionType"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = {};
const RemoveIntersectionTypeTypeLiteralBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTypeLiteralAny: Defaults["IntersectionType"]["Object"] & Defaults["TypeLiteral"]["Any"] = {};
const RemoveIntersectionTypeTypeLiteralAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithTupleTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["TupleType"]["Literal"] = {};
const RemoveIntersectionTypeTupleTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTupleTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["TupleType"]["Object"] = {};
const RemoveIntersectionTypeTupleTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTupleTypeString: Defaults["IntersectionType"]["Object"] & Defaults["TupleType"]["String"] = {};
const RemoveIntersectionTypeTupleTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTupleTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["TupleType"]["Number"] = {};
const RemoveIntersectionTypeTupleTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTupleTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["TupleType"]["Boolean"] = {};
const RemoveIntersectionTypeTupleTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithTupleTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["TupleType"]["Any"] = {};
const RemoveIntersectionTypeTupleTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithArrayTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["ArrayType"]["Literal"] = {};
const RemoveIntersectionTypeArrayTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithArrayTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["ArrayType"]["Object"] = {};
const RemoveIntersectionTypeArrayTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithArrayTypeString: Defaults["IntersectionType"]["Object"] & Defaults["ArrayType"]["String"] = {};
const RemoveIntersectionTypeArrayTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithArrayTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["ArrayType"]["Number"] = {};
const RemoveIntersectionTypeArrayTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithArrayTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["ArrayType"]["Boolean"] = {};
const RemoveIntersectionTypeArrayTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithArrayTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["ArrayType"]["Any"] = {};
const RemoveIntersectionTypeArrayTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithFunctionTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["FunctionType"]["Literal"] = {};
const RemoveIntersectionTypeFunctionTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithFunctionTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["FunctionType"]["Object"] = {};
const RemoveIntersectionTypeFunctionTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithFunctionTypeString: Defaults["IntersectionType"]["Object"] & Defaults["FunctionType"]["String"] = {};
const RemoveIntersectionTypeFunctionTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithFunctionTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["FunctionType"]["Number"] = {};
const RemoveIntersectionTypeFunctionTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithFunctionTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["FunctionType"]["Boolean"] = {};
const RemoveIntersectionTypeFunctionTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithFunctionTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["FunctionType"]["Any"] = {};
const RemoveIntersectionTypeFunctionTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeObjectWithConstructorTypeLiteral: Defaults["IntersectionType"]["Object"] & Defaults["ConstructorType"]["Literal"] = {};
const RemoveIntersectionTypeConstructorTypeLiteralFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithConstructorTypeObject: Defaults["IntersectionType"]["Object"] & Defaults["ConstructorType"]["Object"] = {};
const RemoveIntersectionTypeConstructorTypeObjectFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithConstructorTypeString: Defaults["IntersectionType"]["Object"] & Defaults["ConstructorType"]["String"] = {};
const RemoveIntersectionTypeConstructorTypeStringFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithConstructorTypeNumber: Defaults["IntersectionType"]["Object"] & Defaults["ConstructorType"]["Number"] = {};
const RemoveIntersectionTypeConstructorTypeNumberFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithConstructorTypeBoolean: Defaults["IntersectionType"]["Object"] & Defaults["ConstructorType"]["Boolean"] = {};
const RemoveIntersectionTypeConstructorTypeBooleanFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}
const IntersectionTypeIntersectionTypeObjectWithConstructorTypeAny: Defaults["IntersectionType"]["Object"] & Defaults["ConstructorType"]["Any"] = {};
const RemoveIntersectionTypeConstructorTypeAnyFromIntersectionTypeObject: Defaults["IntersectionType"]["Object"]= {}

const IntersectionTypeIntersectionTypeStringWithParenthesizedTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["ParenthesizedType"]["Literal"] = "two";
const RemoveIntersectionTypeParenthesizedTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithParenthesizedTypeObject: Defaults["IntersectionType"]["String"] & Defaults["ParenthesizedType"]["Object"] = "two";
const RemoveIntersectionTypeParenthesizedTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithParenthesizedTypeString: Defaults["IntersectionType"]["String"] & Defaults["ParenthesizedType"]["String"] = "two";
const RemoveIntersectionTypeParenthesizedTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithParenthesizedTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["ParenthesizedType"]["Number"] = "two";
const RemoveIntersectionTypeParenthesizedTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithParenthesizedTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = "two";
const RemoveIntersectionTypeParenthesizedTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithParenthesizedTypeAny: Defaults["IntersectionType"]["String"] & Defaults["ParenthesizedType"]["Any"] = "two";
const RemoveIntersectionTypeParenthesizedTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithTypeReferenceBuiltinLiteral: Defaults["IntersectionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferenceBuiltinObject: Defaults["IntersectionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferenceBuiltinString: Defaults["IntersectionType"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferenceBuiltinNumber: Defaults["IntersectionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferenceBuiltinBoolean: Defaults["IntersectionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferenceBuiltinAny: Defaults["IntersectionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithTypeReferencePredefinedLiteral: Defaults["IntersectionType"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferencePredefinedObject: Defaults["IntersectionType"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferencePredefinedString: Defaults["IntersectionType"]["String"] & Defaults["TypeReferencePredefined"]["String"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferencePredefinedNumber: Defaults["IntersectionType"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferencePredefinedBoolean: Defaults["IntersectionType"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeReferencePredefinedAny: Defaults["IntersectionType"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithUnionTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["UnionType"]["Literal"] = "two";
const RemoveIntersectionTypeUnionTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithUnionTypeObject: Defaults["IntersectionType"]["String"] & Defaults["UnionType"]["Object"] = "two";
const RemoveIntersectionTypeUnionTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithUnionTypeString: Defaults["IntersectionType"]["String"] & Defaults["UnionType"]["String"] = "two";
const RemoveIntersectionTypeUnionTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithUnionTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["UnionType"]["Number"] = "two";
const RemoveIntersectionTypeUnionTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithUnionTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["UnionType"]["Boolean"] = "two";
const RemoveIntersectionTypeUnionTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithUnionTypeAny: Defaults["IntersectionType"]["String"] & Defaults["UnionType"]["Any"] = "two";
const RemoveIntersectionTypeUnionTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithIntersectionTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["IntersectionType"]["Literal"] = "two";
const RemoveIntersectionTypeIntersectionTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithIntersectionTypeObject: Defaults["IntersectionType"]["String"] & Defaults["IntersectionType"]["Object"] = "two";
const RemoveIntersectionTypeIntersectionTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithIntersectionTypeString: Defaults["IntersectionType"]["String"] & Defaults["IntersectionType"]["String"] = "two";
const RemoveIntersectionTypeIntersectionTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithIntersectionTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["IntersectionType"]["Number"] = "two";
const RemoveIntersectionTypeIntersectionTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithIntersectionTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["IntersectionType"]["Boolean"] = "two";
const RemoveIntersectionTypeIntersectionTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithIntersectionTypeAny: Defaults["IntersectionType"]["String"] & Defaults["IntersectionType"]["Any"] = "two";
const RemoveIntersectionTypeIntersectionTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithTypeLiteralLiteral: Defaults["IntersectionType"]["String"] & Defaults["TypeLiteral"]["Literal"] = "two";
const RemoveIntersectionTypeTypeLiteralLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeLiteralObject: Defaults["IntersectionType"]["String"] & Defaults["TypeLiteral"]["Object"] = "two";
const RemoveIntersectionTypeTypeLiteralObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeLiteralString: Defaults["IntersectionType"]["String"] & Defaults["TypeLiteral"]["String"] = "two";
const RemoveIntersectionTypeTypeLiteralStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeLiteralNumber: Defaults["IntersectionType"]["String"] & Defaults["TypeLiteral"]["Number"] = "two";
const RemoveIntersectionTypeTypeLiteralNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeLiteralBoolean: Defaults["IntersectionType"]["String"] & Defaults["TypeLiteral"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeLiteralBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTypeLiteralAny: Defaults["IntersectionType"]["String"] & Defaults["TypeLiteral"]["Any"] = "two";
const RemoveIntersectionTypeTypeLiteralAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithTupleTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["TupleType"]["Literal"] = "two";
const RemoveIntersectionTypeTupleTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTupleTypeObject: Defaults["IntersectionType"]["String"] & Defaults["TupleType"]["Object"] = "two";
const RemoveIntersectionTypeTupleTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTupleTypeString: Defaults["IntersectionType"]["String"] & Defaults["TupleType"]["String"] = "two";
const RemoveIntersectionTypeTupleTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTupleTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["TupleType"]["Number"] = "two";
const RemoveIntersectionTypeTupleTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTupleTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["TupleType"]["Boolean"] = "two";
const RemoveIntersectionTypeTupleTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithTupleTypeAny: Defaults["IntersectionType"]["String"] & Defaults["TupleType"]["Any"] = "two";
const RemoveIntersectionTypeTupleTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithArrayTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["ArrayType"]["Literal"] = "two";
const RemoveIntersectionTypeArrayTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithArrayTypeObject: Defaults["IntersectionType"]["String"] & Defaults["ArrayType"]["Object"] = "two";
const RemoveIntersectionTypeArrayTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithArrayTypeString: Defaults["IntersectionType"]["String"] & Defaults["ArrayType"]["String"] = "two";
const RemoveIntersectionTypeArrayTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithArrayTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["ArrayType"]["Number"] = "two";
const RemoveIntersectionTypeArrayTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithArrayTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["ArrayType"]["Boolean"] = "two";
const RemoveIntersectionTypeArrayTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithArrayTypeAny: Defaults["IntersectionType"]["String"] & Defaults["ArrayType"]["Any"] = "two";
const RemoveIntersectionTypeArrayTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithFunctionTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["FunctionType"]["Literal"] = "two";
const RemoveIntersectionTypeFunctionTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithFunctionTypeObject: Defaults["IntersectionType"]["String"] & Defaults["FunctionType"]["Object"] = "two";
const RemoveIntersectionTypeFunctionTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithFunctionTypeString: Defaults["IntersectionType"]["String"] & Defaults["FunctionType"]["String"] = "two";
const RemoveIntersectionTypeFunctionTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithFunctionTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["FunctionType"]["Number"] = "two";
const RemoveIntersectionTypeFunctionTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithFunctionTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["FunctionType"]["Boolean"] = "two";
const RemoveIntersectionTypeFunctionTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithFunctionTypeAny: Defaults["IntersectionType"]["String"] & Defaults["FunctionType"]["Any"] = "two";
const RemoveIntersectionTypeFunctionTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeStringWithConstructorTypeLiteral: Defaults["IntersectionType"]["String"] & Defaults["ConstructorType"]["Literal"] = "two";
const RemoveIntersectionTypeConstructorTypeLiteralFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithConstructorTypeObject: Defaults["IntersectionType"]["String"] & Defaults["ConstructorType"]["Object"] = "two";
const RemoveIntersectionTypeConstructorTypeObjectFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithConstructorTypeString: Defaults["IntersectionType"]["String"] & Defaults["ConstructorType"]["String"] = "two";
const RemoveIntersectionTypeConstructorTypeStringFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithConstructorTypeNumber: Defaults["IntersectionType"]["String"] & Defaults["ConstructorType"]["Number"] = "two";
const RemoveIntersectionTypeConstructorTypeNumberFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithConstructorTypeBoolean: Defaults["IntersectionType"]["String"] & Defaults["ConstructorType"]["Boolean"] = "two";
const RemoveIntersectionTypeConstructorTypeBooleanFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"
const IntersectionTypeIntersectionTypeStringWithConstructorTypeAny: Defaults["IntersectionType"]["String"] & Defaults["ConstructorType"]["Any"] = "two";
const RemoveIntersectionTypeConstructorTypeAnyFromIntersectionTypeString: Defaults["IntersectionType"]["String"]= "two"

const IntersectionTypeIntersectionTypeNumberWithParenthesizedTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithParenthesizedTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithParenthesizedTypeString: Defaults["IntersectionType"]["Number"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithParenthesizedTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithParenthesizedTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithParenthesizedTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithTypeReferenceBuiltinLiteral: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferenceBuiltinObject: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferenceBuiltinString: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferenceBuiltinNumber: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferenceBuiltinBoolean: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferenceBuiltinAny: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithTypeReferencePredefinedLiteral: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferencePredefinedObject: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferencePredefinedString: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferencePredefinedNumber: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferencePredefinedBoolean: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeReferencePredefinedAny: Defaults["IntersectionType"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithUnionTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithUnionTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithUnionTypeString: Defaults["IntersectionType"]["Number"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithUnionTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithUnionTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithUnionTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithIntersectionTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithIntersectionTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithIntersectionTypeString: Defaults["IntersectionType"]["Number"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithIntersectionTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithIntersectionTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithIntersectionTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithTypeLiteralLiteral: Defaults["IntersectionType"]["Number"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeLiteralObject: Defaults["IntersectionType"]["Number"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeLiteralString: Defaults["IntersectionType"]["Number"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeLiteralNumber: Defaults["IntersectionType"]["Number"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeLiteralBoolean: Defaults["IntersectionType"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTypeLiteralAny: Defaults["IntersectionType"]["Number"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithTupleTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTupleTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTupleTypeString: Defaults["IntersectionType"]["Number"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTupleTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTupleTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithTupleTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithArrayTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithArrayTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithArrayTypeString: Defaults["IntersectionType"]["Number"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithArrayTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithArrayTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithArrayTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithFunctionTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithFunctionTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithFunctionTypeString: Defaults["IntersectionType"]["Number"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithFunctionTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithFunctionTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithFunctionTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeNumberWithConstructorTypeLiteral: Defaults["IntersectionType"]["Number"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithConstructorTypeObject: Defaults["IntersectionType"]["Number"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithConstructorTypeString: Defaults["IntersectionType"]["Number"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithConstructorTypeNumber: Defaults["IntersectionType"]["Number"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithConstructorTypeBoolean: Defaults["IntersectionType"]["Number"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2
const IntersectionTypeIntersectionTypeNumberWithConstructorTypeAny: Defaults["IntersectionType"]["Number"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromIntersectionTypeNumber: Defaults["IntersectionType"]["Number"]= 2

const IntersectionTypeIntersectionTypeBooleanWithParenthesizedTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = true;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithParenthesizedTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = true;
const RemoveIntersectionTypeParenthesizedTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithParenthesizedTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = true;
const RemoveIntersectionTypeParenthesizedTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithParenthesizedTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = true;
const RemoveIntersectionTypeParenthesizedTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithParenthesizedTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = true;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithParenthesizedTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = true;
const RemoveIntersectionTypeParenthesizedTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithTypeReferenceBuiltinLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferenceBuiltinObject: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferenceBuiltinString: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferenceBuiltinNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferenceBuiltinBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferenceBuiltinAny: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithTypeReferencePredefinedLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferencePredefinedObject: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferencePredefinedString: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferencePredefinedNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferencePredefinedBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeReferencePredefinedAny: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithUnionTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["UnionType"]["Literal"] = true;
const RemoveIntersectionTypeUnionTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithUnionTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["UnionType"]["Object"] = true;
const RemoveIntersectionTypeUnionTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithUnionTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["UnionType"]["String"] = true;
const RemoveIntersectionTypeUnionTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithUnionTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["UnionType"]["Number"] = true;
const RemoveIntersectionTypeUnionTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithUnionTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["UnionType"]["Boolean"] = true;
const RemoveIntersectionTypeUnionTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithUnionTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["UnionType"]["Any"] = true;
const RemoveIntersectionTypeUnionTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithIntersectionTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = true;
const RemoveIntersectionTypeIntersectionTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithIntersectionTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["IntersectionType"]["Object"] = true;
const RemoveIntersectionTypeIntersectionTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithIntersectionTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["IntersectionType"]["String"] = true;
const RemoveIntersectionTypeIntersectionTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithIntersectionTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["IntersectionType"]["Number"] = true;
const RemoveIntersectionTypeIntersectionTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = true;
const RemoveIntersectionTypeIntersectionTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithIntersectionTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["IntersectionType"]["Any"] = true;
const RemoveIntersectionTypeIntersectionTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithTypeLiteralLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = true;
const RemoveIntersectionTypeTypeLiteralLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeLiteralObject: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = true;
const RemoveIntersectionTypeTypeLiteralObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeLiteralString: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeLiteral"]["String"] = true;
const RemoveIntersectionTypeTypeLiteralStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeLiteralNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = true;
const RemoveIntersectionTypeTypeLiteralNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeLiteralBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = true;
const RemoveIntersectionTypeTypeLiteralBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTypeLiteralAny: Defaults["IntersectionType"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = true;
const RemoveIntersectionTypeTypeLiteralAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithTupleTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["TupleType"]["Literal"] = true;
const RemoveIntersectionTypeTupleTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTupleTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["TupleType"]["Object"] = true;
const RemoveIntersectionTypeTupleTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTupleTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["TupleType"]["String"] = true;
const RemoveIntersectionTypeTupleTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTupleTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["TupleType"]["Number"] = true;
const RemoveIntersectionTypeTupleTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTupleTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["TupleType"]["Boolean"] = true;
const RemoveIntersectionTypeTupleTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithTupleTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["TupleType"]["Any"] = true;
const RemoveIntersectionTypeTupleTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithArrayTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["ArrayType"]["Literal"] = true;
const RemoveIntersectionTypeArrayTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithArrayTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["ArrayType"]["Object"] = true;
const RemoveIntersectionTypeArrayTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithArrayTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["ArrayType"]["String"] = true;
const RemoveIntersectionTypeArrayTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithArrayTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["ArrayType"]["Number"] = true;
const RemoveIntersectionTypeArrayTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithArrayTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = true;
const RemoveIntersectionTypeArrayTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithArrayTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["ArrayType"]["Any"] = true;
const RemoveIntersectionTypeArrayTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithFunctionTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["FunctionType"]["Literal"] = true;
const RemoveIntersectionTypeFunctionTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithFunctionTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["FunctionType"]["Object"] = true;
const RemoveIntersectionTypeFunctionTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithFunctionTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["FunctionType"]["String"] = true;
const RemoveIntersectionTypeFunctionTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithFunctionTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["FunctionType"]["Number"] = true;
const RemoveIntersectionTypeFunctionTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithFunctionTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = true;
const RemoveIntersectionTypeFunctionTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithFunctionTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["FunctionType"]["Any"] = true;
const RemoveIntersectionTypeFunctionTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeBooleanWithConstructorTypeLiteral: Defaults["IntersectionType"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = true;
const RemoveIntersectionTypeConstructorTypeLiteralFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithConstructorTypeObject: Defaults["IntersectionType"]["Boolean"] & Defaults["ConstructorType"]["Object"] = true;
const RemoveIntersectionTypeConstructorTypeObjectFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithConstructorTypeString: Defaults["IntersectionType"]["Boolean"] & Defaults["ConstructorType"]["String"] = true;
const RemoveIntersectionTypeConstructorTypeStringFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithConstructorTypeNumber: Defaults["IntersectionType"]["Boolean"] & Defaults["ConstructorType"]["Number"] = true;
const RemoveIntersectionTypeConstructorTypeNumberFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithConstructorTypeBoolean: Defaults["IntersectionType"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = true;
const RemoveIntersectionTypeConstructorTypeBooleanFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true
const IntersectionTypeIntersectionTypeBooleanWithConstructorTypeAny: Defaults["IntersectionType"]["Boolean"] & Defaults["ConstructorType"]["Any"] = true;
const RemoveIntersectionTypeConstructorTypeAnyFromIntersectionTypeBoolean: Defaults["IntersectionType"]["Boolean"]= true

const IntersectionTypeIntersectionTypeAnyWithParenthesizedTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithParenthesizedTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithParenthesizedTypeString: Defaults["IntersectionType"]["Any"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithParenthesizedTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithParenthesizedTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithParenthesizedTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithTypeReferenceBuiltinLiteral: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferenceBuiltinObject: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferenceBuiltinString: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferenceBuiltinNumber: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferenceBuiltinBoolean: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferenceBuiltinAny: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithTypeReferencePredefinedLiteral: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferencePredefinedObject: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferencePredefinedString: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferencePredefinedNumber: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferencePredefinedBoolean: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeReferencePredefinedAny: Defaults["IntersectionType"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithUnionTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithUnionTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithUnionTypeString: Defaults["IntersectionType"]["Any"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithUnionTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithUnionTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithUnionTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithIntersectionTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithIntersectionTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithIntersectionTypeString: Defaults["IntersectionType"]["Any"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithIntersectionTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithIntersectionTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithIntersectionTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithTypeLiteralLiteral: Defaults["IntersectionType"]["Any"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeLiteralObject: Defaults["IntersectionType"]["Any"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeLiteralString: Defaults["IntersectionType"]["Any"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeLiteralNumber: Defaults["IntersectionType"]["Any"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeLiteralBoolean: Defaults["IntersectionType"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTypeLiteralAny: Defaults["IntersectionType"]["Any"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithTupleTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTupleTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTupleTypeString: Defaults["IntersectionType"]["Any"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTupleTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTupleTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithTupleTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithArrayTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithArrayTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithArrayTypeString: Defaults["IntersectionType"]["Any"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithArrayTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithArrayTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithArrayTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithFunctionTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithFunctionTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithFunctionTypeString: Defaults["IntersectionType"]["Any"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithFunctionTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithFunctionTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithFunctionTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

const IntersectionTypeIntersectionTypeAnyWithConstructorTypeLiteral: Defaults["IntersectionType"]["Any"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithConstructorTypeObject: Defaults["IntersectionType"]["Any"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithConstructorTypeString: Defaults["IntersectionType"]["Any"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithConstructorTypeNumber: Defaults["IntersectionType"]["Any"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithConstructorTypeBoolean: Defaults["IntersectionType"]["Any"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2
const IntersectionTypeIntersectionTypeAnyWithConstructorTypeAny: Defaults["IntersectionType"]["Any"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromIntersectionTypeAny: Defaults["IntersectionType"]["Any"]= 2

