import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - ArrayType
const IntersectionTypeArrayTypeLiteralWithParenthesizedTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = [1,1];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithParenthesizedTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = [1,1];
const RemoveIntersectionTypeParenthesizedTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithParenthesizedTypeString: Defaults["ArrayType"]["Literal"] & Defaults["ParenthesizedType"]["String"] = [1,1];
const RemoveIntersectionTypeParenthesizedTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithParenthesizedTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = [1,1];
const RemoveIntersectionTypeParenthesizedTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithParenthesizedTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithParenthesizedTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = [1,1];
const RemoveIntersectionTypeParenthesizedTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithTypeReferenceBuiltinLiteral: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [1,1];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferenceBuiltinObject: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = [1,1];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferenceBuiltinString: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = [1,1];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferenceBuiltinNumber: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = [1,1];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferenceBuiltinBoolean: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [1,1];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferenceBuiltinAny: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = [1,1];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithTypeReferencePredefinedLiteral: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = [1,1];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferencePredefinedObject: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = [1,1];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferencePredefinedString: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = [1,1];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferencePredefinedNumber: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = [1,1];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferencePredefinedBoolean: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = [1,1];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeReferencePredefinedAny: Defaults["ArrayType"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = [1,1];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithUnionTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["UnionType"]["Literal"] = [1,1];
const RemoveIntersectionTypeUnionTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithUnionTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["UnionType"]["Object"] = [1,1];
const RemoveIntersectionTypeUnionTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithUnionTypeString: Defaults["ArrayType"]["Literal"] & Defaults["UnionType"]["String"] = [1,1];
const RemoveIntersectionTypeUnionTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithUnionTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["UnionType"]["Number"] = [1,1];
const RemoveIntersectionTypeUnionTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithUnionTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["UnionType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeUnionTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithUnionTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["UnionType"]["Any"] = [1,1];
const RemoveIntersectionTypeUnionTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithIntersectionTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["IntersectionType"]["Literal"] = [1,1];
const RemoveIntersectionTypeIntersectionTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithIntersectionTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["IntersectionType"]["Object"] = [1,1];
const RemoveIntersectionTypeIntersectionTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithIntersectionTypeString: Defaults["ArrayType"]["Literal"] & Defaults["IntersectionType"]["String"] = [1,1];
const RemoveIntersectionTypeIntersectionTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithIntersectionTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["IntersectionType"]["Number"] = [1,1];
const RemoveIntersectionTypeIntersectionTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithIntersectionTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeIntersectionTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithIntersectionTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["IntersectionType"]["Any"] = [1,1];
const RemoveIntersectionTypeIntersectionTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithTypeLiteralLiteral: Defaults["ArrayType"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = [1,1];
const RemoveIntersectionTypeTypeLiteralLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeLiteralObject: Defaults["ArrayType"]["Literal"] & Defaults["TypeLiteral"]["Object"] = [1,1];
const RemoveIntersectionTypeTypeLiteralObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeLiteralString: Defaults["ArrayType"]["Literal"] & Defaults["TypeLiteral"]["String"] = [1,1];
const RemoveIntersectionTypeTypeLiteralStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeLiteralNumber: Defaults["ArrayType"]["Literal"] & Defaults["TypeLiteral"]["Number"] = [1,1];
const RemoveIntersectionTypeTypeLiteralNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeLiteralBoolean: Defaults["ArrayType"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = [1,1];
const RemoveIntersectionTypeTypeLiteralBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTypeLiteralAny: Defaults["ArrayType"]["Literal"] & Defaults["TypeLiteral"]["Any"] = [1,1];
const RemoveIntersectionTypeTypeLiteralAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithTupleTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["TupleType"]["Literal"] = [1,1];
const RemoveIntersectionTypeTupleTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTupleTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["TupleType"]["Object"] = [1,1];
const RemoveIntersectionTypeTupleTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTupleTypeString: Defaults["ArrayType"]["Literal"] & Defaults["TupleType"]["String"] = [1,1];
const RemoveIntersectionTypeTupleTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTupleTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["TupleType"]["Number"] = [1,1];
const RemoveIntersectionTypeTupleTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTupleTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["TupleType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeTupleTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithTupleTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["TupleType"]["Any"] = [1,1];
const RemoveIntersectionTypeTupleTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithArrayTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["ArrayType"]["Literal"] = [1,1];
const RemoveIntersectionTypeArrayTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithArrayTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["ArrayType"]["Object"] = [1,1];
const RemoveIntersectionTypeArrayTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithArrayTypeString: Defaults["ArrayType"]["Literal"] & Defaults["ArrayType"]["String"] = [1,1];
const RemoveIntersectionTypeArrayTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithArrayTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["ArrayType"]["Number"] = [1,1];
const RemoveIntersectionTypeArrayTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithArrayTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["ArrayType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeArrayTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithArrayTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["ArrayType"]["Any"] = [1,1];
const RemoveIntersectionTypeArrayTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithFunctionTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["FunctionType"]["Literal"] = [1,1];
const RemoveIntersectionTypeFunctionTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithFunctionTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["FunctionType"]["Object"] = [1,1];
const RemoveIntersectionTypeFunctionTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithFunctionTypeString: Defaults["ArrayType"]["Literal"] & Defaults["FunctionType"]["String"] = [1,1];
const RemoveIntersectionTypeFunctionTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithFunctionTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["FunctionType"]["Number"] = [1,1];
const RemoveIntersectionTypeFunctionTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithFunctionTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["FunctionType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeFunctionTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithFunctionTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["FunctionType"]["Any"] = [1,1];
const RemoveIntersectionTypeFunctionTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeLiteralWithConstructorTypeLiteral: Defaults["ArrayType"]["Literal"] & Defaults["ConstructorType"]["Literal"] = [1,1];
const RemoveIntersectionTypeConstructorTypeLiteralFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithConstructorTypeObject: Defaults["ArrayType"]["Literal"] & Defaults["ConstructorType"]["Object"] = [1,1];
const RemoveIntersectionTypeConstructorTypeObjectFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithConstructorTypeString: Defaults["ArrayType"]["Literal"] & Defaults["ConstructorType"]["String"] = [1,1];
const RemoveIntersectionTypeConstructorTypeStringFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithConstructorTypeNumber: Defaults["ArrayType"]["Literal"] & Defaults["ConstructorType"]["Number"] = [1,1];
const RemoveIntersectionTypeConstructorTypeNumberFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithConstructorTypeBoolean: Defaults["ArrayType"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = [1,1];
const RemoveIntersectionTypeConstructorTypeBooleanFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]
const IntersectionTypeArrayTypeLiteralWithConstructorTypeAny: Defaults["ArrayType"]["Literal"] & Defaults["ConstructorType"]["Any"] = [1,1];
const RemoveIntersectionTypeConstructorTypeAnyFromArrayTypeLiteral: Defaults["ArrayType"]["Literal"]= [1,1]

const IntersectionTypeArrayTypeObjectWithParenthesizedTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithParenthesizedTypeObject: Defaults["ArrayType"]["Object"] & Defaults["ParenthesizedType"]["Object"] = [{},{}];
const RemoveIntersectionTypeParenthesizedTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithParenthesizedTypeString: Defaults["ArrayType"]["Object"] & Defaults["ParenthesizedType"]["String"] = [{},{}];
const RemoveIntersectionTypeParenthesizedTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithParenthesizedTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["ParenthesizedType"]["Number"] = [{},{}];
const RemoveIntersectionTypeParenthesizedTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithParenthesizedTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithParenthesizedTypeAny: Defaults["ArrayType"]["Object"] & Defaults["ParenthesizedType"]["Any"] = [{},{}];
const RemoveIntersectionTypeParenthesizedTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithTypeReferenceBuiltinLiteral: Defaults["ArrayType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [{},{}];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferenceBuiltinObject: Defaults["ArrayType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = [{},{}];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferenceBuiltinString: Defaults["ArrayType"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = [{},{}];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferenceBuiltinNumber: Defaults["ArrayType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = [{},{}];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferenceBuiltinBoolean: Defaults["ArrayType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferenceBuiltinAny: Defaults["ArrayType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = [{},{}];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithTypeReferencePredefinedLiteral: Defaults["ArrayType"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = [{},{}];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferencePredefinedObject: Defaults["ArrayType"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = [{},{}];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferencePredefinedString: Defaults["ArrayType"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = [{},{}];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferencePredefinedNumber: Defaults["ArrayType"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = [{},{}];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferencePredefinedBoolean: Defaults["ArrayType"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeReferencePredefinedAny: Defaults["ArrayType"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = [{},{}];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithUnionTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["UnionType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeUnionTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithUnionTypeObject: Defaults["ArrayType"]["Object"] & Defaults["UnionType"]["Object"] = [{},{}];
const RemoveIntersectionTypeUnionTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithUnionTypeString: Defaults["ArrayType"]["Object"] & Defaults["UnionType"]["String"] = [{},{}];
const RemoveIntersectionTypeUnionTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithUnionTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["UnionType"]["Number"] = [{},{}];
const RemoveIntersectionTypeUnionTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithUnionTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["UnionType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeUnionTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithUnionTypeAny: Defaults["ArrayType"]["Object"] & Defaults["UnionType"]["Any"] = [{},{}];
const RemoveIntersectionTypeUnionTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithIntersectionTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["IntersectionType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeIntersectionTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithIntersectionTypeObject: Defaults["ArrayType"]["Object"] & Defaults["IntersectionType"]["Object"] = [{},{}];
const RemoveIntersectionTypeIntersectionTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithIntersectionTypeString: Defaults["ArrayType"]["Object"] & Defaults["IntersectionType"]["String"] = [{},{}];
const RemoveIntersectionTypeIntersectionTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithIntersectionTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["IntersectionType"]["Number"] = [{},{}];
const RemoveIntersectionTypeIntersectionTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithIntersectionTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["IntersectionType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeIntersectionTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithIntersectionTypeAny: Defaults["ArrayType"]["Object"] & Defaults["IntersectionType"]["Any"] = [{},{}];
const RemoveIntersectionTypeIntersectionTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithTypeLiteralLiteral: Defaults["ArrayType"]["Object"] & Defaults["TypeLiteral"]["Literal"] = [{},{}];
const RemoveIntersectionTypeTypeLiteralLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeLiteralObject: Defaults["ArrayType"]["Object"] & Defaults["TypeLiteral"]["Object"] = [{},{}];
const RemoveIntersectionTypeTypeLiteralObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeLiteralString: Defaults["ArrayType"]["Object"] & Defaults["TypeLiteral"]["String"] = [{},{}];
const RemoveIntersectionTypeTypeLiteralStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeLiteralNumber: Defaults["ArrayType"]["Object"] & Defaults["TypeLiteral"]["Number"] = [{},{}];
const RemoveIntersectionTypeTypeLiteralNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeLiteralBoolean: Defaults["ArrayType"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeTypeLiteralBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTypeLiteralAny: Defaults["ArrayType"]["Object"] & Defaults["TypeLiteral"]["Any"] = [{},{}];
const RemoveIntersectionTypeTypeLiteralAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithTupleTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["TupleType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeTupleTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTupleTypeObject: Defaults["ArrayType"]["Object"] & Defaults["TupleType"]["Object"] = [{},{}];
const RemoveIntersectionTypeTupleTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTupleTypeString: Defaults["ArrayType"]["Object"] & Defaults["TupleType"]["String"] = [{},{}];
const RemoveIntersectionTypeTupleTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTupleTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["TupleType"]["Number"] = [{},{}];
const RemoveIntersectionTypeTupleTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTupleTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["TupleType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeTupleTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithTupleTypeAny: Defaults["ArrayType"]["Object"] & Defaults["TupleType"]["Any"] = [{},{}];
const RemoveIntersectionTypeTupleTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithArrayTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["ArrayType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeArrayTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithArrayTypeObject: Defaults["ArrayType"]["Object"] & Defaults["ArrayType"]["Object"] = [{},{}];
const RemoveIntersectionTypeArrayTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithArrayTypeString: Defaults["ArrayType"]["Object"] & Defaults["ArrayType"]["String"] = [{},{}];
const RemoveIntersectionTypeArrayTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithArrayTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["ArrayType"]["Number"] = [{},{}];
const RemoveIntersectionTypeArrayTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithArrayTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["ArrayType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeArrayTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithArrayTypeAny: Defaults["ArrayType"]["Object"] & Defaults["ArrayType"]["Any"] = [{},{}];
const RemoveIntersectionTypeArrayTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithFunctionTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["FunctionType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeFunctionTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithFunctionTypeObject: Defaults["ArrayType"]["Object"] & Defaults["FunctionType"]["Object"] = [{},{}];
const RemoveIntersectionTypeFunctionTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithFunctionTypeString: Defaults["ArrayType"]["Object"] & Defaults["FunctionType"]["String"] = [{},{}];
const RemoveIntersectionTypeFunctionTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithFunctionTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["FunctionType"]["Number"] = [{},{}];
const RemoveIntersectionTypeFunctionTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithFunctionTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["FunctionType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeFunctionTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithFunctionTypeAny: Defaults["ArrayType"]["Object"] & Defaults["FunctionType"]["Any"] = [{},{}];
const RemoveIntersectionTypeFunctionTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeObjectWithConstructorTypeLiteral: Defaults["ArrayType"]["Object"] & Defaults["ConstructorType"]["Literal"] = [{},{}];
const RemoveIntersectionTypeConstructorTypeLiteralFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithConstructorTypeObject: Defaults["ArrayType"]["Object"] & Defaults["ConstructorType"]["Object"] = [{},{}];
const RemoveIntersectionTypeConstructorTypeObjectFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithConstructorTypeString: Defaults["ArrayType"]["Object"] & Defaults["ConstructorType"]["String"] = [{},{}];
const RemoveIntersectionTypeConstructorTypeStringFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithConstructorTypeNumber: Defaults["ArrayType"]["Object"] & Defaults["ConstructorType"]["Number"] = [{},{}];
const RemoveIntersectionTypeConstructorTypeNumberFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithConstructorTypeBoolean: Defaults["ArrayType"]["Object"] & Defaults["ConstructorType"]["Boolean"] = [{},{}];
const RemoveIntersectionTypeConstructorTypeBooleanFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]
const IntersectionTypeArrayTypeObjectWithConstructorTypeAny: Defaults["ArrayType"]["Object"] & Defaults["ConstructorType"]["Any"] = [{},{}];
const RemoveIntersectionTypeConstructorTypeAnyFromArrayTypeObject: Defaults["ArrayType"]["Object"]= [{},{}]

const IntersectionTypeArrayTypeStringWithParenthesizedTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["ParenthesizedType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithParenthesizedTypeObject: Defaults["ArrayType"]["String"] & Defaults["ParenthesizedType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeParenthesizedTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithParenthesizedTypeString: Defaults["ArrayType"]["String"] & Defaults["ParenthesizedType"]["String"] = ["two","two"];
const RemoveIntersectionTypeParenthesizedTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithParenthesizedTypeNumber: Defaults["ArrayType"]["String"] & Defaults["ParenthesizedType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeParenthesizedTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithParenthesizedTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithParenthesizedTypeAny: Defaults["ArrayType"]["String"] & Defaults["ParenthesizedType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeParenthesizedTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithTypeReferenceBuiltinLiteral: Defaults["ArrayType"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferenceBuiltinObject: Defaults["ArrayType"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = ["two","two"];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferenceBuiltinString: Defaults["ArrayType"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = ["two","two"];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferenceBuiltinNumber: Defaults["ArrayType"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = ["two","two"];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferenceBuiltinBoolean: Defaults["ArrayType"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferenceBuiltinAny: Defaults["ArrayType"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = ["two","two"];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithTypeReferencePredefinedLiteral: Defaults["ArrayType"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferencePredefinedObject: Defaults["ArrayType"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = ["two","two"];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferencePredefinedString: Defaults["ArrayType"]["String"] & Defaults["TypeReferencePredefined"]["String"] = ["two","two"];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferencePredefinedNumber: Defaults["ArrayType"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = ["two","two"];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferencePredefinedBoolean: Defaults["ArrayType"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeReferencePredefinedAny: Defaults["ArrayType"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = ["two","two"];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithUnionTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["UnionType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeUnionTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithUnionTypeObject: Defaults["ArrayType"]["String"] & Defaults["UnionType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeUnionTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithUnionTypeString: Defaults["ArrayType"]["String"] & Defaults["UnionType"]["String"] = ["two","two"];
const RemoveIntersectionTypeUnionTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithUnionTypeNumber: Defaults["ArrayType"]["String"] & Defaults["UnionType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeUnionTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithUnionTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["UnionType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeUnionTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithUnionTypeAny: Defaults["ArrayType"]["String"] & Defaults["UnionType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeUnionTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithIntersectionTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["IntersectionType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeIntersectionTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithIntersectionTypeObject: Defaults["ArrayType"]["String"] & Defaults["IntersectionType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeIntersectionTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithIntersectionTypeString: Defaults["ArrayType"]["String"] & Defaults["IntersectionType"]["String"] = ["two","two"];
const RemoveIntersectionTypeIntersectionTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithIntersectionTypeNumber: Defaults["ArrayType"]["String"] & Defaults["IntersectionType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeIntersectionTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithIntersectionTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["IntersectionType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeIntersectionTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithIntersectionTypeAny: Defaults["ArrayType"]["String"] & Defaults["IntersectionType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeIntersectionTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithTypeLiteralLiteral: Defaults["ArrayType"]["String"] & Defaults["TypeLiteral"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeTypeLiteralLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeLiteralObject: Defaults["ArrayType"]["String"] & Defaults["TypeLiteral"]["Object"] = ["two","two"];
const RemoveIntersectionTypeTypeLiteralObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeLiteralString: Defaults["ArrayType"]["String"] & Defaults["TypeLiteral"]["String"] = ["two","two"];
const RemoveIntersectionTypeTypeLiteralStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeLiteralNumber: Defaults["ArrayType"]["String"] & Defaults["TypeLiteral"]["Number"] = ["two","two"];
const RemoveIntersectionTypeTypeLiteralNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeLiteralBoolean: Defaults["ArrayType"]["String"] & Defaults["TypeLiteral"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeTypeLiteralBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTypeLiteralAny: Defaults["ArrayType"]["String"] & Defaults["TypeLiteral"]["Any"] = ["two","two"];
const RemoveIntersectionTypeTypeLiteralAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithTupleTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["TupleType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeTupleTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTupleTypeObject: Defaults["ArrayType"]["String"] & Defaults["TupleType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeTupleTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTupleTypeString: Defaults["ArrayType"]["String"] & Defaults["TupleType"]["String"] = ["two","two"];
const RemoveIntersectionTypeTupleTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTupleTypeNumber: Defaults["ArrayType"]["String"] & Defaults["TupleType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeTupleTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTupleTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["TupleType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeTupleTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithTupleTypeAny: Defaults["ArrayType"]["String"] & Defaults["TupleType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeTupleTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithArrayTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["ArrayType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeArrayTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithArrayTypeObject: Defaults["ArrayType"]["String"] & Defaults["ArrayType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeArrayTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithArrayTypeString: Defaults["ArrayType"]["String"] & Defaults["ArrayType"]["String"] = ["two","two"];
const RemoveIntersectionTypeArrayTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithArrayTypeNumber: Defaults["ArrayType"]["String"] & Defaults["ArrayType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeArrayTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithArrayTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["ArrayType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeArrayTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithArrayTypeAny: Defaults["ArrayType"]["String"] & Defaults["ArrayType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeArrayTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithFunctionTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["FunctionType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeFunctionTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithFunctionTypeObject: Defaults["ArrayType"]["String"] & Defaults["FunctionType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeFunctionTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithFunctionTypeString: Defaults["ArrayType"]["String"] & Defaults["FunctionType"]["String"] = ["two","two"];
const RemoveIntersectionTypeFunctionTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithFunctionTypeNumber: Defaults["ArrayType"]["String"] & Defaults["FunctionType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeFunctionTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithFunctionTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["FunctionType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeFunctionTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithFunctionTypeAny: Defaults["ArrayType"]["String"] & Defaults["FunctionType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeFunctionTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeStringWithConstructorTypeLiteral: Defaults["ArrayType"]["String"] & Defaults["ConstructorType"]["Literal"] = ["two","two"];
const RemoveIntersectionTypeConstructorTypeLiteralFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithConstructorTypeObject: Defaults["ArrayType"]["String"] & Defaults["ConstructorType"]["Object"] = ["two","two"];
const RemoveIntersectionTypeConstructorTypeObjectFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithConstructorTypeString: Defaults["ArrayType"]["String"] & Defaults["ConstructorType"]["String"] = ["two","two"];
const RemoveIntersectionTypeConstructorTypeStringFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithConstructorTypeNumber: Defaults["ArrayType"]["String"] & Defaults["ConstructorType"]["Number"] = ["two","two"];
const RemoveIntersectionTypeConstructorTypeNumberFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithConstructorTypeBoolean: Defaults["ArrayType"]["String"] & Defaults["ConstructorType"]["Boolean"] = ["two","two"];
const RemoveIntersectionTypeConstructorTypeBooleanFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]
const IntersectionTypeArrayTypeStringWithConstructorTypeAny: Defaults["ArrayType"]["String"] & Defaults["ConstructorType"]["Any"] = ["two","two"];
const RemoveIntersectionTypeConstructorTypeAnyFromArrayTypeString: Defaults["ArrayType"]["String"]= ["two","two"]

const IntersectionTypeArrayTypeNumberWithParenthesizedTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithParenthesizedTypeObject: Defaults["ArrayType"]["Number"] & Defaults["ParenthesizedType"]["Object"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithParenthesizedTypeString: Defaults["ArrayType"]["Number"] & Defaults["ParenthesizedType"]["String"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithParenthesizedTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["ParenthesizedType"]["Number"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithParenthesizedTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithParenthesizedTypeAny: Defaults["ArrayType"]["Number"] & Defaults["ParenthesizedType"]["Any"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithTypeReferenceBuiltinLiteral: Defaults["ArrayType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferenceBuiltinObject: Defaults["ArrayType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferenceBuiltinString: Defaults["ArrayType"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferenceBuiltinNumber: Defaults["ArrayType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferenceBuiltinBoolean: Defaults["ArrayType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferenceBuiltinAny: Defaults["ArrayType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithTypeReferencePredefinedLiteral: Defaults["ArrayType"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferencePredefinedObject: Defaults["ArrayType"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferencePredefinedString: Defaults["ArrayType"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferencePredefinedNumber: Defaults["ArrayType"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferencePredefinedBoolean: Defaults["ArrayType"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeReferencePredefinedAny: Defaults["ArrayType"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithUnionTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["UnionType"]["Literal"] = [2,2];
const RemoveIntersectionTypeUnionTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithUnionTypeObject: Defaults["ArrayType"]["Number"] & Defaults["UnionType"]["Object"] = [2,2];
const RemoveIntersectionTypeUnionTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithUnionTypeString: Defaults["ArrayType"]["Number"] & Defaults["UnionType"]["String"] = [2,2];
const RemoveIntersectionTypeUnionTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithUnionTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["UnionType"]["Number"] = [2,2];
const RemoveIntersectionTypeUnionTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithUnionTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["UnionType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeUnionTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithUnionTypeAny: Defaults["ArrayType"]["Number"] & Defaults["UnionType"]["Any"] = [2,2];
const RemoveIntersectionTypeUnionTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithIntersectionTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["IntersectionType"]["Literal"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithIntersectionTypeObject: Defaults["ArrayType"]["Number"] & Defaults["IntersectionType"]["Object"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithIntersectionTypeString: Defaults["ArrayType"]["Number"] & Defaults["IntersectionType"]["String"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithIntersectionTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["IntersectionType"]["Number"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithIntersectionTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["IntersectionType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithIntersectionTypeAny: Defaults["ArrayType"]["Number"] & Defaults["IntersectionType"]["Any"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithTypeLiteralLiteral: Defaults["ArrayType"]["Number"] & Defaults["TypeLiteral"]["Literal"] = [2,2];
const RemoveIntersectionTypeTypeLiteralLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeLiteralObject: Defaults["ArrayType"]["Number"] & Defaults["TypeLiteral"]["Object"] = [2,2];
const RemoveIntersectionTypeTypeLiteralObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeLiteralString: Defaults["ArrayType"]["Number"] & Defaults["TypeLiteral"]["String"] = [2,2];
const RemoveIntersectionTypeTypeLiteralStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeLiteralNumber: Defaults["ArrayType"]["Number"] & Defaults["TypeLiteral"]["Number"] = [2,2];
const RemoveIntersectionTypeTypeLiteralNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeLiteralBoolean: Defaults["ArrayType"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTypeLiteralBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTypeLiteralAny: Defaults["ArrayType"]["Number"] & Defaults["TypeLiteral"]["Any"] = [2,2];
const RemoveIntersectionTypeTypeLiteralAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithTupleTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["TupleType"]["Literal"] = [2,2];
const RemoveIntersectionTypeTupleTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTupleTypeObject: Defaults["ArrayType"]["Number"] & Defaults["TupleType"]["Object"] = [2,2];
const RemoveIntersectionTypeTupleTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTupleTypeString: Defaults["ArrayType"]["Number"] & Defaults["TupleType"]["String"] = [2,2];
const RemoveIntersectionTypeTupleTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTupleTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["TupleType"]["Number"] = [2,2];
const RemoveIntersectionTypeTupleTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTupleTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["TupleType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTupleTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithTupleTypeAny: Defaults["ArrayType"]["Number"] & Defaults["TupleType"]["Any"] = [2,2];
const RemoveIntersectionTypeTupleTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithArrayTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["ArrayType"]["Literal"] = [2,2];
const RemoveIntersectionTypeArrayTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithArrayTypeObject: Defaults["ArrayType"]["Number"] & Defaults["ArrayType"]["Object"] = [2,2];
const RemoveIntersectionTypeArrayTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithArrayTypeString: Defaults["ArrayType"]["Number"] & Defaults["ArrayType"]["String"] = [2,2];
const RemoveIntersectionTypeArrayTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithArrayTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["ArrayType"]["Number"] = [2,2];
const RemoveIntersectionTypeArrayTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithArrayTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["ArrayType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeArrayTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithArrayTypeAny: Defaults["ArrayType"]["Number"] & Defaults["ArrayType"]["Any"] = [2,2];
const RemoveIntersectionTypeArrayTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithFunctionTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["FunctionType"]["Literal"] = [2,2];
const RemoveIntersectionTypeFunctionTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithFunctionTypeObject: Defaults["ArrayType"]["Number"] & Defaults["FunctionType"]["Object"] = [2,2];
const RemoveIntersectionTypeFunctionTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithFunctionTypeString: Defaults["ArrayType"]["Number"] & Defaults["FunctionType"]["String"] = [2,2];
const RemoveIntersectionTypeFunctionTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithFunctionTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["FunctionType"]["Number"] = [2,2];
const RemoveIntersectionTypeFunctionTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithFunctionTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["FunctionType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeFunctionTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithFunctionTypeAny: Defaults["ArrayType"]["Number"] & Defaults["FunctionType"]["Any"] = [2,2];
const RemoveIntersectionTypeFunctionTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeNumberWithConstructorTypeLiteral: Defaults["ArrayType"]["Number"] & Defaults["ConstructorType"]["Literal"] = [2,2];
const RemoveIntersectionTypeConstructorTypeLiteralFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithConstructorTypeObject: Defaults["ArrayType"]["Number"] & Defaults["ConstructorType"]["Object"] = [2,2];
const RemoveIntersectionTypeConstructorTypeObjectFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithConstructorTypeString: Defaults["ArrayType"]["Number"] & Defaults["ConstructorType"]["String"] = [2,2];
const RemoveIntersectionTypeConstructorTypeStringFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithConstructorTypeNumber: Defaults["ArrayType"]["Number"] & Defaults["ConstructorType"]["Number"] = [2,2];
const RemoveIntersectionTypeConstructorTypeNumberFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithConstructorTypeBoolean: Defaults["ArrayType"]["Number"] & Defaults["ConstructorType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeConstructorTypeBooleanFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]
const IntersectionTypeArrayTypeNumberWithConstructorTypeAny: Defaults["ArrayType"]["Number"] & Defaults["ConstructorType"]["Any"] = [2,2];
const RemoveIntersectionTypeConstructorTypeAnyFromArrayTypeNumber: Defaults["ArrayType"]["Number"]= [2,2]

const IntersectionTypeArrayTypeBooleanWithParenthesizedTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = [true,true];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithParenthesizedTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = [true,true];
const RemoveIntersectionTypeParenthesizedTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithParenthesizedTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = [true,true];
const RemoveIntersectionTypeParenthesizedTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithParenthesizedTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = [true,true];
const RemoveIntersectionTypeParenthesizedTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithParenthesizedTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithParenthesizedTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = [true,true];
const RemoveIntersectionTypeParenthesizedTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithTypeReferenceBuiltinLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [true,true];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferenceBuiltinObject: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = [true,true];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferenceBuiltinString: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = [true,true];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferenceBuiltinNumber: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = [true,true];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferenceBuiltinBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [true,true];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferenceBuiltinAny: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = [true,true];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithTypeReferencePredefinedLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = [true,true];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferencePredefinedObject: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = [true,true];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferencePredefinedString: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = [true,true];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferencePredefinedNumber: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = [true,true];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferencePredefinedBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = [true,true];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeReferencePredefinedAny: Defaults["ArrayType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = [true,true];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithUnionTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["UnionType"]["Literal"] = [true,true];
const RemoveIntersectionTypeUnionTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithUnionTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["UnionType"]["Object"] = [true,true];
const RemoveIntersectionTypeUnionTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithUnionTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["UnionType"]["String"] = [true,true];
const RemoveIntersectionTypeUnionTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithUnionTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["UnionType"]["Number"] = [true,true];
const RemoveIntersectionTypeUnionTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithUnionTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["UnionType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeUnionTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithUnionTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["UnionType"]["Any"] = [true,true];
const RemoveIntersectionTypeUnionTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithIntersectionTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = [true,true];
const RemoveIntersectionTypeIntersectionTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithIntersectionTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["IntersectionType"]["Object"] = [true,true];
const RemoveIntersectionTypeIntersectionTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithIntersectionTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["IntersectionType"]["String"] = [true,true];
const RemoveIntersectionTypeIntersectionTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithIntersectionTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["IntersectionType"]["Number"] = [true,true];
const RemoveIntersectionTypeIntersectionTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithIntersectionTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeIntersectionTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithIntersectionTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["IntersectionType"]["Any"] = [true,true];
const RemoveIntersectionTypeIntersectionTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithTypeLiteralLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = [true,true];
const RemoveIntersectionTypeTypeLiteralLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeLiteralObject: Defaults["ArrayType"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = [true,true];
const RemoveIntersectionTypeTypeLiteralObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeLiteralString: Defaults["ArrayType"]["Boolean"] & Defaults["TypeLiteral"]["String"] = [true,true];
const RemoveIntersectionTypeTypeLiteralStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeLiteralNumber: Defaults["ArrayType"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = [true,true];
const RemoveIntersectionTypeTypeLiteralNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeLiteralBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = [true,true];
const RemoveIntersectionTypeTypeLiteralBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTypeLiteralAny: Defaults["ArrayType"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = [true,true];
const RemoveIntersectionTypeTypeLiteralAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithTupleTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["TupleType"]["Literal"] = [true,true];
const RemoveIntersectionTypeTupleTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTupleTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["TupleType"]["Object"] = [true,true];
const RemoveIntersectionTypeTupleTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTupleTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["TupleType"]["String"] = [true,true];
const RemoveIntersectionTypeTupleTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTupleTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["TupleType"]["Number"] = [true,true];
const RemoveIntersectionTypeTupleTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTupleTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["TupleType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeTupleTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithTupleTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["TupleType"]["Any"] = [true,true];
const RemoveIntersectionTypeTupleTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithArrayTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["ArrayType"]["Literal"] = [true,true];
const RemoveIntersectionTypeArrayTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithArrayTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["ArrayType"]["Object"] = [true,true];
const RemoveIntersectionTypeArrayTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithArrayTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["ArrayType"]["String"] = [true,true];
const RemoveIntersectionTypeArrayTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithArrayTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["ArrayType"]["Number"] = [true,true];
const RemoveIntersectionTypeArrayTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithArrayTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeArrayTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithArrayTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["ArrayType"]["Any"] = [true,true];
const RemoveIntersectionTypeArrayTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithFunctionTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["FunctionType"]["Literal"] = [true,true];
const RemoveIntersectionTypeFunctionTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithFunctionTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["FunctionType"]["Object"] = [true,true];
const RemoveIntersectionTypeFunctionTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithFunctionTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["FunctionType"]["String"] = [true,true];
const RemoveIntersectionTypeFunctionTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithFunctionTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["FunctionType"]["Number"] = [true,true];
const RemoveIntersectionTypeFunctionTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithFunctionTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeFunctionTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithFunctionTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["FunctionType"]["Any"] = [true,true];
const RemoveIntersectionTypeFunctionTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeBooleanWithConstructorTypeLiteral: Defaults["ArrayType"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = [true,true];
const RemoveIntersectionTypeConstructorTypeLiteralFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithConstructorTypeObject: Defaults["ArrayType"]["Boolean"] & Defaults["ConstructorType"]["Object"] = [true,true];
const RemoveIntersectionTypeConstructorTypeObjectFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithConstructorTypeString: Defaults["ArrayType"]["Boolean"] & Defaults["ConstructorType"]["String"] = [true,true];
const RemoveIntersectionTypeConstructorTypeStringFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithConstructorTypeNumber: Defaults["ArrayType"]["Boolean"] & Defaults["ConstructorType"]["Number"] = [true,true];
const RemoveIntersectionTypeConstructorTypeNumberFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithConstructorTypeBoolean: Defaults["ArrayType"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = [true,true];
const RemoveIntersectionTypeConstructorTypeBooleanFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]
const IntersectionTypeArrayTypeBooleanWithConstructorTypeAny: Defaults["ArrayType"]["Boolean"] & Defaults["ConstructorType"]["Any"] = [true,true];
const RemoveIntersectionTypeConstructorTypeAnyFromArrayTypeBoolean: Defaults["ArrayType"]["Boolean"]= [true,true]

const IntersectionTypeArrayTypeAnyWithParenthesizedTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithParenthesizedTypeObject: Defaults["ArrayType"]["Any"] & Defaults["ParenthesizedType"]["Object"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithParenthesizedTypeString: Defaults["ArrayType"]["Any"] & Defaults["ParenthesizedType"]["String"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithParenthesizedTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["ParenthesizedType"]["Number"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithParenthesizedTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithParenthesizedTypeAny: Defaults["ArrayType"]["Any"] & Defaults["ParenthesizedType"]["Any"] = [2,2];
const RemoveIntersectionTypeParenthesizedTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithTypeReferenceBuiltinLiteral: Defaults["ArrayType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferenceBuiltinObject: Defaults["ArrayType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferenceBuiltinString: Defaults["ArrayType"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferenceBuiltinNumber: Defaults["ArrayType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferenceBuiltinBoolean: Defaults["ArrayType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferenceBuiltinAny: Defaults["ArrayType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = [2,2];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithTypeReferencePredefinedLiteral: Defaults["ArrayType"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferencePredefinedObject: Defaults["ArrayType"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferencePredefinedString: Defaults["ArrayType"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferencePredefinedNumber: Defaults["ArrayType"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferencePredefinedBoolean: Defaults["ArrayType"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeReferencePredefinedAny: Defaults["ArrayType"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = [2,2];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithUnionTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["UnionType"]["Literal"] = [2,2];
const RemoveIntersectionTypeUnionTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithUnionTypeObject: Defaults["ArrayType"]["Any"] & Defaults["UnionType"]["Object"] = [2,2];
const RemoveIntersectionTypeUnionTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithUnionTypeString: Defaults["ArrayType"]["Any"] & Defaults["UnionType"]["String"] = [2,2];
const RemoveIntersectionTypeUnionTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithUnionTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["UnionType"]["Number"] = [2,2];
const RemoveIntersectionTypeUnionTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithUnionTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["UnionType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeUnionTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithUnionTypeAny: Defaults["ArrayType"]["Any"] & Defaults["UnionType"]["Any"] = [2,2];
const RemoveIntersectionTypeUnionTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithIntersectionTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["IntersectionType"]["Literal"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithIntersectionTypeObject: Defaults["ArrayType"]["Any"] & Defaults["IntersectionType"]["Object"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithIntersectionTypeString: Defaults["ArrayType"]["Any"] & Defaults["IntersectionType"]["String"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithIntersectionTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["IntersectionType"]["Number"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithIntersectionTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["IntersectionType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithIntersectionTypeAny: Defaults["ArrayType"]["Any"] & Defaults["IntersectionType"]["Any"] = [2,2];
const RemoveIntersectionTypeIntersectionTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithTypeLiteralLiteral: Defaults["ArrayType"]["Any"] & Defaults["TypeLiteral"]["Literal"] = [2,2];
const RemoveIntersectionTypeTypeLiteralLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeLiteralObject: Defaults["ArrayType"]["Any"] & Defaults["TypeLiteral"]["Object"] = [2,2];
const RemoveIntersectionTypeTypeLiteralObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeLiteralString: Defaults["ArrayType"]["Any"] & Defaults["TypeLiteral"]["String"] = [2,2];
const RemoveIntersectionTypeTypeLiteralStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeLiteralNumber: Defaults["ArrayType"]["Any"] & Defaults["TypeLiteral"]["Number"] = [2,2];
const RemoveIntersectionTypeTypeLiteralNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeLiteralBoolean: Defaults["ArrayType"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTypeLiteralBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTypeLiteralAny: Defaults["ArrayType"]["Any"] & Defaults["TypeLiteral"]["Any"] = [2,2];
const RemoveIntersectionTypeTypeLiteralAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithTupleTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["TupleType"]["Literal"] = [2,2];
const RemoveIntersectionTypeTupleTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTupleTypeObject: Defaults["ArrayType"]["Any"] & Defaults["TupleType"]["Object"] = [2,2];
const RemoveIntersectionTypeTupleTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTupleTypeString: Defaults["ArrayType"]["Any"] & Defaults["TupleType"]["String"] = [2,2];
const RemoveIntersectionTypeTupleTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTupleTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["TupleType"]["Number"] = [2,2];
const RemoveIntersectionTypeTupleTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTupleTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["TupleType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeTupleTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithTupleTypeAny: Defaults["ArrayType"]["Any"] & Defaults["TupleType"]["Any"] = [2,2];
const RemoveIntersectionTypeTupleTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithArrayTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["ArrayType"]["Literal"] = [2,2];
const RemoveIntersectionTypeArrayTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithArrayTypeObject: Defaults["ArrayType"]["Any"] & Defaults["ArrayType"]["Object"] = [2,2];
const RemoveIntersectionTypeArrayTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithArrayTypeString: Defaults["ArrayType"]["Any"] & Defaults["ArrayType"]["String"] = [2,2];
const RemoveIntersectionTypeArrayTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithArrayTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["ArrayType"]["Number"] = [2,2];
const RemoveIntersectionTypeArrayTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithArrayTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["ArrayType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeArrayTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithArrayTypeAny: Defaults["ArrayType"]["Any"] & Defaults["ArrayType"]["Any"] = [2,2];
const RemoveIntersectionTypeArrayTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithFunctionTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["FunctionType"]["Literal"] = [2,2];
const RemoveIntersectionTypeFunctionTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithFunctionTypeObject: Defaults["ArrayType"]["Any"] & Defaults["FunctionType"]["Object"] = [2,2];
const RemoveIntersectionTypeFunctionTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithFunctionTypeString: Defaults["ArrayType"]["Any"] & Defaults["FunctionType"]["String"] = [2,2];
const RemoveIntersectionTypeFunctionTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithFunctionTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["FunctionType"]["Number"] = [2,2];
const RemoveIntersectionTypeFunctionTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithFunctionTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["FunctionType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeFunctionTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithFunctionTypeAny: Defaults["ArrayType"]["Any"] & Defaults["FunctionType"]["Any"] = [2,2];
const RemoveIntersectionTypeFunctionTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

const IntersectionTypeArrayTypeAnyWithConstructorTypeLiteral: Defaults["ArrayType"]["Any"] & Defaults["ConstructorType"]["Literal"] = [2,2];
const RemoveIntersectionTypeConstructorTypeLiteralFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithConstructorTypeObject: Defaults["ArrayType"]["Any"] & Defaults["ConstructorType"]["Object"] = [2,2];
const RemoveIntersectionTypeConstructorTypeObjectFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithConstructorTypeString: Defaults["ArrayType"]["Any"] & Defaults["ConstructorType"]["String"] = [2,2];
const RemoveIntersectionTypeConstructorTypeStringFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithConstructorTypeNumber: Defaults["ArrayType"]["Any"] & Defaults["ConstructorType"]["Number"] = [2,2];
const RemoveIntersectionTypeConstructorTypeNumberFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithConstructorTypeBoolean: Defaults["ArrayType"]["Any"] & Defaults["ConstructorType"]["Boolean"] = [2,2];
const RemoveIntersectionTypeConstructorTypeBooleanFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]
const IntersectionTypeArrayTypeAnyWithConstructorTypeAny: Defaults["ArrayType"]["Any"] & Defaults["ConstructorType"]["Any"] = [2,2];
const RemoveIntersectionTypeConstructorTypeAnyFromArrayTypeAny: Defaults["ArrayType"]["Any"]= [2,2]

