import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - TupleType
const IntersectionTypeTupleTypeLiteralWithParenthesizedTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = [1];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithParenthesizedTypeObject: Defaults["TupleType"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = [1];
const RemoveIntersectionTypeParenthesizedTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithParenthesizedTypeString: Defaults["TupleType"]["Literal"] & Defaults["ParenthesizedType"]["String"] = [1];
const RemoveIntersectionTypeParenthesizedTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithParenthesizedTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = [1];
const RemoveIntersectionTypeParenthesizedTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithParenthesizedTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = [1];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithParenthesizedTypeAny: Defaults["TupleType"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = [1];
const RemoveIntersectionTypeParenthesizedTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithTypeReferenceBuiltinLiteral: Defaults["TupleType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [1];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferenceBuiltinObject: Defaults["TupleType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = [1];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferenceBuiltinString: Defaults["TupleType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = [1];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferenceBuiltinNumber: Defaults["TupleType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = [1];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferenceBuiltinBoolean: Defaults["TupleType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [1];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferenceBuiltinAny: Defaults["TupleType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = [1];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithTypeReferencePredefinedLiteral: Defaults["TupleType"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = [1];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferencePredefinedObject: Defaults["TupleType"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = [1];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferencePredefinedString: Defaults["TupleType"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = [1];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferencePredefinedNumber: Defaults["TupleType"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = [1];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferencePredefinedBoolean: Defaults["TupleType"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = [1];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeReferencePredefinedAny: Defaults["TupleType"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = [1];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithUnionTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["UnionType"]["Literal"] = [1];
const RemoveIntersectionTypeUnionTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithUnionTypeObject: Defaults["TupleType"]["Literal"] & Defaults["UnionType"]["Object"] = [1];
const RemoveIntersectionTypeUnionTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithUnionTypeString: Defaults["TupleType"]["Literal"] & Defaults["UnionType"]["String"] = [1];
const RemoveIntersectionTypeUnionTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithUnionTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["UnionType"]["Number"] = [1];
const RemoveIntersectionTypeUnionTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithUnionTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["UnionType"]["Boolean"] = [1];
const RemoveIntersectionTypeUnionTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithUnionTypeAny: Defaults["TupleType"]["Literal"] & Defaults["UnionType"]["Any"] = [1];
const RemoveIntersectionTypeUnionTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithIntersectionTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["IntersectionType"]["Literal"] = [1];
const RemoveIntersectionTypeIntersectionTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithIntersectionTypeObject: Defaults["TupleType"]["Literal"] & Defaults["IntersectionType"]["Object"] = [1];
const RemoveIntersectionTypeIntersectionTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithIntersectionTypeString: Defaults["TupleType"]["Literal"] & Defaults["IntersectionType"]["String"] = [1];
const RemoveIntersectionTypeIntersectionTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithIntersectionTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["IntersectionType"]["Number"] = [1];
const RemoveIntersectionTypeIntersectionTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithIntersectionTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = [1];
const RemoveIntersectionTypeIntersectionTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithIntersectionTypeAny: Defaults["TupleType"]["Literal"] & Defaults["IntersectionType"]["Any"] = [1];
const RemoveIntersectionTypeIntersectionTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithTypeLiteralLiteral: Defaults["TupleType"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = [1];
const RemoveIntersectionTypeTypeLiteralLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeLiteralObject: Defaults["TupleType"]["Literal"] & Defaults["TypeLiteral"]["Object"] = [1];
const RemoveIntersectionTypeTypeLiteralObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeLiteralString: Defaults["TupleType"]["Literal"] & Defaults["TypeLiteral"]["String"] = [1];
const RemoveIntersectionTypeTypeLiteralStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeLiteralNumber: Defaults["TupleType"]["Literal"] & Defaults["TypeLiteral"]["Number"] = [1];
const RemoveIntersectionTypeTypeLiteralNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeLiteralBoolean: Defaults["TupleType"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = [1];
const RemoveIntersectionTypeTypeLiteralBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTypeLiteralAny: Defaults["TupleType"]["Literal"] & Defaults["TypeLiteral"]["Any"] = [1];
const RemoveIntersectionTypeTypeLiteralAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithTupleTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["TupleType"]["Literal"] = [1];
const RemoveIntersectionTypeTupleTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTupleTypeObject: Defaults["TupleType"]["Literal"] & Defaults["TupleType"]["Object"] = [1];
const RemoveIntersectionTypeTupleTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTupleTypeString: Defaults["TupleType"]["Literal"] & Defaults["TupleType"]["String"] = [1];
const RemoveIntersectionTypeTupleTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTupleTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["TupleType"]["Number"] = [1];
const RemoveIntersectionTypeTupleTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTupleTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["TupleType"]["Boolean"] = [1];
const RemoveIntersectionTypeTupleTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithTupleTypeAny: Defaults["TupleType"]["Literal"] & Defaults["TupleType"]["Any"] = [1];
const RemoveIntersectionTypeTupleTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithArrayTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["ArrayType"]["Literal"] = [1];
const RemoveIntersectionTypeArrayTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithArrayTypeObject: Defaults["TupleType"]["Literal"] & Defaults["ArrayType"]["Object"] = [1];
const RemoveIntersectionTypeArrayTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithArrayTypeString: Defaults["TupleType"]["Literal"] & Defaults["ArrayType"]["String"] = [1];
const RemoveIntersectionTypeArrayTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithArrayTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["ArrayType"]["Number"] = [1];
const RemoveIntersectionTypeArrayTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithArrayTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["ArrayType"]["Boolean"] = [1];
const RemoveIntersectionTypeArrayTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithArrayTypeAny: Defaults["TupleType"]["Literal"] & Defaults["ArrayType"]["Any"] = [1];
const RemoveIntersectionTypeArrayTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithFunctionTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["FunctionType"]["Literal"] = [1];
const RemoveIntersectionTypeFunctionTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithFunctionTypeObject: Defaults["TupleType"]["Literal"] & Defaults["FunctionType"]["Object"] = [1];
const RemoveIntersectionTypeFunctionTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithFunctionTypeString: Defaults["TupleType"]["Literal"] & Defaults["FunctionType"]["String"] = [1];
const RemoveIntersectionTypeFunctionTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithFunctionTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["FunctionType"]["Number"] = [1];
const RemoveIntersectionTypeFunctionTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithFunctionTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["FunctionType"]["Boolean"] = [1];
const RemoveIntersectionTypeFunctionTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithFunctionTypeAny: Defaults["TupleType"]["Literal"] & Defaults["FunctionType"]["Any"] = [1];
const RemoveIntersectionTypeFunctionTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeLiteralWithConstructorTypeLiteral: Defaults["TupleType"]["Literal"] & Defaults["ConstructorType"]["Literal"] = [1];
const RemoveIntersectionTypeConstructorTypeLiteralFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithConstructorTypeObject: Defaults["TupleType"]["Literal"] & Defaults["ConstructorType"]["Object"] = [1];
const RemoveIntersectionTypeConstructorTypeObjectFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithConstructorTypeString: Defaults["TupleType"]["Literal"] & Defaults["ConstructorType"]["String"] = [1];
const RemoveIntersectionTypeConstructorTypeStringFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithConstructorTypeNumber: Defaults["TupleType"]["Literal"] & Defaults["ConstructorType"]["Number"] = [1];
const RemoveIntersectionTypeConstructorTypeNumberFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithConstructorTypeBoolean: Defaults["TupleType"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = [1];
const RemoveIntersectionTypeConstructorTypeBooleanFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]
const IntersectionTypeTupleTypeLiteralWithConstructorTypeAny: Defaults["TupleType"]["Literal"] & Defaults["ConstructorType"]["Any"] = [1];
const RemoveIntersectionTypeConstructorTypeAnyFromTupleTypeLiteral: Defaults["TupleType"]["Literal"]= [1]

const IntersectionTypeTupleTypeObjectWithParenthesizedTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = [{}];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithParenthesizedTypeObject: Defaults["TupleType"]["Object"] & Defaults["ParenthesizedType"]["Object"] = [{}];
const RemoveIntersectionTypeParenthesizedTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithParenthesizedTypeString: Defaults["TupleType"]["Object"] & Defaults["ParenthesizedType"]["String"] = [{}];
const RemoveIntersectionTypeParenthesizedTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithParenthesizedTypeNumber: Defaults["TupleType"]["Object"] & Defaults["ParenthesizedType"]["Number"] = [{}];
const RemoveIntersectionTypeParenthesizedTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithParenthesizedTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = [{}];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithParenthesizedTypeAny: Defaults["TupleType"]["Object"] & Defaults["ParenthesizedType"]["Any"] = [{}];
const RemoveIntersectionTypeParenthesizedTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithTypeReferenceBuiltinLiteral: Defaults["TupleType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [{}];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferenceBuiltinObject: Defaults["TupleType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = [{}];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferenceBuiltinString: Defaults["TupleType"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = [{}];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferenceBuiltinNumber: Defaults["TupleType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = [{}];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferenceBuiltinBoolean: Defaults["TupleType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [{}];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferenceBuiltinAny: Defaults["TupleType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = [{}];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithTypeReferencePredefinedLiteral: Defaults["TupleType"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = [{}];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferencePredefinedObject: Defaults["TupleType"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = [{}];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferencePredefinedString: Defaults["TupleType"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = [{}];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferencePredefinedNumber: Defaults["TupleType"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = [{}];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferencePredefinedBoolean: Defaults["TupleType"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = [{}];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeReferencePredefinedAny: Defaults["TupleType"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = [{}];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithUnionTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["UnionType"]["Literal"] = [{}];
const RemoveIntersectionTypeUnionTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithUnionTypeObject: Defaults["TupleType"]["Object"] & Defaults["UnionType"]["Object"] = [{}];
const RemoveIntersectionTypeUnionTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithUnionTypeString: Defaults["TupleType"]["Object"] & Defaults["UnionType"]["String"] = [{}];
const RemoveIntersectionTypeUnionTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithUnionTypeNumber: Defaults["TupleType"]["Object"] & Defaults["UnionType"]["Number"] = [{}];
const RemoveIntersectionTypeUnionTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithUnionTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["UnionType"]["Boolean"] = [{}];
const RemoveIntersectionTypeUnionTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithUnionTypeAny: Defaults["TupleType"]["Object"] & Defaults["UnionType"]["Any"] = [{}];
const RemoveIntersectionTypeUnionTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithIntersectionTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["IntersectionType"]["Literal"] = [{}];
const RemoveIntersectionTypeIntersectionTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithIntersectionTypeObject: Defaults["TupleType"]["Object"] & Defaults["IntersectionType"]["Object"] = [{}];
const RemoveIntersectionTypeIntersectionTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithIntersectionTypeString: Defaults["TupleType"]["Object"] & Defaults["IntersectionType"]["String"] = [{}];
const RemoveIntersectionTypeIntersectionTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithIntersectionTypeNumber: Defaults["TupleType"]["Object"] & Defaults["IntersectionType"]["Number"] = [{}];
const RemoveIntersectionTypeIntersectionTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithIntersectionTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["IntersectionType"]["Boolean"] = [{}];
const RemoveIntersectionTypeIntersectionTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithIntersectionTypeAny: Defaults["TupleType"]["Object"] & Defaults["IntersectionType"]["Any"] = [{}];
const RemoveIntersectionTypeIntersectionTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithTypeLiteralLiteral: Defaults["TupleType"]["Object"] & Defaults["TypeLiteral"]["Literal"] = [{}];
const RemoveIntersectionTypeTypeLiteralLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeLiteralObject: Defaults["TupleType"]["Object"] & Defaults["TypeLiteral"]["Object"] = [{}];
const RemoveIntersectionTypeTypeLiteralObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeLiteralString: Defaults["TupleType"]["Object"] & Defaults["TypeLiteral"]["String"] = [{}];
const RemoveIntersectionTypeTypeLiteralStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeLiteralNumber: Defaults["TupleType"]["Object"] & Defaults["TypeLiteral"]["Number"] = [{}];
const RemoveIntersectionTypeTypeLiteralNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeLiteralBoolean: Defaults["TupleType"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = [{}];
const RemoveIntersectionTypeTypeLiteralBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTypeLiteralAny: Defaults["TupleType"]["Object"] & Defaults["TypeLiteral"]["Any"] = [{}];
const RemoveIntersectionTypeTypeLiteralAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithTupleTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["TupleType"]["Literal"] = [{}];
const RemoveIntersectionTypeTupleTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTupleTypeObject: Defaults["TupleType"]["Object"] & Defaults["TupleType"]["Object"] = [{}];
const RemoveIntersectionTypeTupleTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTupleTypeString: Defaults["TupleType"]["Object"] & Defaults["TupleType"]["String"] = [{}];
const RemoveIntersectionTypeTupleTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTupleTypeNumber: Defaults["TupleType"]["Object"] & Defaults["TupleType"]["Number"] = [{}];
const RemoveIntersectionTypeTupleTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTupleTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["TupleType"]["Boolean"] = [{}];
const RemoveIntersectionTypeTupleTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithTupleTypeAny: Defaults["TupleType"]["Object"] & Defaults["TupleType"]["Any"] = [{}];
const RemoveIntersectionTypeTupleTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithArrayTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["ArrayType"]["Literal"] = [{}];
const RemoveIntersectionTypeArrayTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithArrayTypeObject: Defaults["TupleType"]["Object"] & Defaults["ArrayType"]["Object"] = [{}];
const RemoveIntersectionTypeArrayTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithArrayTypeString: Defaults["TupleType"]["Object"] & Defaults["ArrayType"]["String"] = [{}];
const RemoveIntersectionTypeArrayTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithArrayTypeNumber: Defaults["TupleType"]["Object"] & Defaults["ArrayType"]["Number"] = [{}];
const RemoveIntersectionTypeArrayTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithArrayTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["ArrayType"]["Boolean"] = [{}];
const RemoveIntersectionTypeArrayTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithArrayTypeAny: Defaults["TupleType"]["Object"] & Defaults["ArrayType"]["Any"] = [{}];
const RemoveIntersectionTypeArrayTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithFunctionTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["FunctionType"]["Literal"] = [{}];
const RemoveIntersectionTypeFunctionTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithFunctionTypeObject: Defaults["TupleType"]["Object"] & Defaults["FunctionType"]["Object"] = [{}];
const RemoveIntersectionTypeFunctionTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithFunctionTypeString: Defaults["TupleType"]["Object"] & Defaults["FunctionType"]["String"] = [{}];
const RemoveIntersectionTypeFunctionTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithFunctionTypeNumber: Defaults["TupleType"]["Object"] & Defaults["FunctionType"]["Number"] = [{}];
const RemoveIntersectionTypeFunctionTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithFunctionTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["FunctionType"]["Boolean"] = [{}];
const RemoveIntersectionTypeFunctionTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithFunctionTypeAny: Defaults["TupleType"]["Object"] & Defaults["FunctionType"]["Any"] = [{}];
const RemoveIntersectionTypeFunctionTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeObjectWithConstructorTypeLiteral: Defaults["TupleType"]["Object"] & Defaults["ConstructorType"]["Literal"] = [{}];
const RemoveIntersectionTypeConstructorTypeLiteralFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithConstructorTypeObject: Defaults["TupleType"]["Object"] & Defaults["ConstructorType"]["Object"] = [{}];
const RemoveIntersectionTypeConstructorTypeObjectFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithConstructorTypeString: Defaults["TupleType"]["Object"] & Defaults["ConstructorType"]["String"] = [{}];
const RemoveIntersectionTypeConstructorTypeStringFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithConstructorTypeNumber: Defaults["TupleType"]["Object"] & Defaults["ConstructorType"]["Number"] = [{}];
const RemoveIntersectionTypeConstructorTypeNumberFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithConstructorTypeBoolean: Defaults["TupleType"]["Object"] & Defaults["ConstructorType"]["Boolean"] = [{}];
const RemoveIntersectionTypeConstructorTypeBooleanFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]
const IntersectionTypeTupleTypeObjectWithConstructorTypeAny: Defaults["TupleType"]["Object"] & Defaults["ConstructorType"]["Any"] = [{}];
const RemoveIntersectionTypeConstructorTypeAnyFromTupleTypeObject: Defaults["TupleType"]["Object"]= [{}]

const IntersectionTypeTupleTypeStringWithParenthesizedTypeLiteral: Defaults["TupleType"]["String"] & Defaults["ParenthesizedType"]["Literal"] = ["two"];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithParenthesizedTypeObject: Defaults["TupleType"]["String"] & Defaults["ParenthesizedType"]["Object"] = ["two"];
const RemoveIntersectionTypeParenthesizedTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithParenthesizedTypeString: Defaults["TupleType"]["String"] & Defaults["ParenthesizedType"]["String"] = ["two"];
const RemoveIntersectionTypeParenthesizedTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithParenthesizedTypeNumber: Defaults["TupleType"]["String"] & Defaults["ParenthesizedType"]["Number"] = ["two"];
const RemoveIntersectionTypeParenthesizedTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithParenthesizedTypeBoolean: Defaults["TupleType"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithParenthesizedTypeAny: Defaults["TupleType"]["String"] & Defaults["ParenthesizedType"]["Any"] = ["two"];
const RemoveIntersectionTypeParenthesizedTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithTypeReferenceBuiltinLiteral: Defaults["TupleType"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = ["two"];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferenceBuiltinObject: Defaults["TupleType"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = ["two"];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferenceBuiltinString: Defaults["TupleType"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = ["two"];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferenceBuiltinNumber: Defaults["TupleType"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = ["two"];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferenceBuiltinBoolean: Defaults["TupleType"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = ["two"];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferenceBuiltinAny: Defaults["TupleType"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = ["two"];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithTypeReferencePredefinedLiteral: Defaults["TupleType"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = ["two"];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferencePredefinedObject: Defaults["TupleType"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = ["two"];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferencePredefinedString: Defaults["TupleType"]["String"] & Defaults["TypeReferencePredefined"]["String"] = ["two"];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferencePredefinedNumber: Defaults["TupleType"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = ["two"];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferencePredefinedBoolean: Defaults["TupleType"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = ["two"];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeReferencePredefinedAny: Defaults["TupleType"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = ["two"];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithUnionTypeLiteral: Defaults["TupleType"]["String"] & Defaults["UnionType"]["Literal"] = ["two"];
const RemoveIntersectionTypeUnionTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithUnionTypeObject: Defaults["TupleType"]["String"] & Defaults["UnionType"]["Object"] = ["two"];
const RemoveIntersectionTypeUnionTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithUnionTypeString: Defaults["TupleType"]["String"] & Defaults["UnionType"]["String"] = ["two"];
const RemoveIntersectionTypeUnionTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithUnionTypeNumber: Defaults["TupleType"]["String"] & Defaults["UnionType"]["Number"] = ["two"];
const RemoveIntersectionTypeUnionTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithUnionTypeBoolean: Defaults["TupleType"]["String"] & Defaults["UnionType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeUnionTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithUnionTypeAny: Defaults["TupleType"]["String"] & Defaults["UnionType"]["Any"] = ["two"];
const RemoveIntersectionTypeUnionTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithIntersectionTypeLiteral: Defaults["TupleType"]["String"] & Defaults["IntersectionType"]["Literal"] = ["two"];
const RemoveIntersectionTypeIntersectionTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithIntersectionTypeObject: Defaults["TupleType"]["String"] & Defaults["IntersectionType"]["Object"] = ["two"];
const RemoveIntersectionTypeIntersectionTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithIntersectionTypeString: Defaults["TupleType"]["String"] & Defaults["IntersectionType"]["String"] = ["two"];
const RemoveIntersectionTypeIntersectionTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithIntersectionTypeNumber: Defaults["TupleType"]["String"] & Defaults["IntersectionType"]["Number"] = ["two"];
const RemoveIntersectionTypeIntersectionTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithIntersectionTypeBoolean: Defaults["TupleType"]["String"] & Defaults["IntersectionType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeIntersectionTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithIntersectionTypeAny: Defaults["TupleType"]["String"] & Defaults["IntersectionType"]["Any"] = ["two"];
const RemoveIntersectionTypeIntersectionTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithTypeLiteralLiteral: Defaults["TupleType"]["String"] & Defaults["TypeLiteral"]["Literal"] = ["two"];
const RemoveIntersectionTypeTypeLiteralLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeLiteralObject: Defaults["TupleType"]["String"] & Defaults["TypeLiteral"]["Object"] = ["two"];
const RemoveIntersectionTypeTypeLiteralObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeLiteralString: Defaults["TupleType"]["String"] & Defaults["TypeLiteral"]["String"] = ["two"];
const RemoveIntersectionTypeTypeLiteralStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeLiteralNumber: Defaults["TupleType"]["String"] & Defaults["TypeLiteral"]["Number"] = ["two"];
const RemoveIntersectionTypeTypeLiteralNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeLiteralBoolean: Defaults["TupleType"]["String"] & Defaults["TypeLiteral"]["Boolean"] = ["two"];
const RemoveIntersectionTypeTypeLiteralBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTypeLiteralAny: Defaults["TupleType"]["String"] & Defaults["TypeLiteral"]["Any"] = ["two"];
const RemoveIntersectionTypeTypeLiteralAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithTupleTypeLiteral: Defaults["TupleType"]["String"] & Defaults["TupleType"]["Literal"] = ["two"];
const RemoveIntersectionTypeTupleTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTupleTypeObject: Defaults["TupleType"]["String"] & Defaults["TupleType"]["Object"] = ["two"];
const RemoveIntersectionTypeTupleTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTupleTypeString: Defaults["TupleType"]["String"] & Defaults["TupleType"]["String"] = ["two"];
const RemoveIntersectionTypeTupleTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTupleTypeNumber: Defaults["TupleType"]["String"] & Defaults["TupleType"]["Number"] = ["two"];
const RemoveIntersectionTypeTupleTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTupleTypeBoolean: Defaults["TupleType"]["String"] & Defaults["TupleType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeTupleTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithTupleTypeAny: Defaults["TupleType"]["String"] & Defaults["TupleType"]["Any"] = ["two"];
const RemoveIntersectionTypeTupleTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithArrayTypeLiteral: Defaults["TupleType"]["String"] & Defaults["ArrayType"]["Literal"] = ["two"];
const RemoveIntersectionTypeArrayTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithArrayTypeObject: Defaults["TupleType"]["String"] & Defaults["ArrayType"]["Object"] = ["two"];
const RemoveIntersectionTypeArrayTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithArrayTypeString: Defaults["TupleType"]["String"] & Defaults["ArrayType"]["String"] = ["two"];
const RemoveIntersectionTypeArrayTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithArrayTypeNumber: Defaults["TupleType"]["String"] & Defaults["ArrayType"]["Number"] = ["two"];
const RemoveIntersectionTypeArrayTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithArrayTypeBoolean: Defaults["TupleType"]["String"] & Defaults["ArrayType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeArrayTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithArrayTypeAny: Defaults["TupleType"]["String"] & Defaults["ArrayType"]["Any"] = ["two"];
const RemoveIntersectionTypeArrayTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithFunctionTypeLiteral: Defaults["TupleType"]["String"] & Defaults["FunctionType"]["Literal"] = ["two"];
const RemoveIntersectionTypeFunctionTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithFunctionTypeObject: Defaults["TupleType"]["String"] & Defaults["FunctionType"]["Object"] = ["two"];
const RemoveIntersectionTypeFunctionTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithFunctionTypeString: Defaults["TupleType"]["String"] & Defaults["FunctionType"]["String"] = ["two"];
const RemoveIntersectionTypeFunctionTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithFunctionTypeNumber: Defaults["TupleType"]["String"] & Defaults["FunctionType"]["Number"] = ["two"];
const RemoveIntersectionTypeFunctionTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithFunctionTypeBoolean: Defaults["TupleType"]["String"] & Defaults["FunctionType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeFunctionTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithFunctionTypeAny: Defaults["TupleType"]["String"] & Defaults["FunctionType"]["Any"] = ["two"];
const RemoveIntersectionTypeFunctionTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeStringWithConstructorTypeLiteral: Defaults["TupleType"]["String"] & Defaults["ConstructorType"]["Literal"] = ["two"];
const RemoveIntersectionTypeConstructorTypeLiteralFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithConstructorTypeObject: Defaults["TupleType"]["String"] & Defaults["ConstructorType"]["Object"] = ["two"];
const RemoveIntersectionTypeConstructorTypeObjectFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithConstructorTypeString: Defaults["TupleType"]["String"] & Defaults["ConstructorType"]["String"] = ["two"];
const RemoveIntersectionTypeConstructorTypeStringFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithConstructorTypeNumber: Defaults["TupleType"]["String"] & Defaults["ConstructorType"]["Number"] = ["two"];
const RemoveIntersectionTypeConstructorTypeNumberFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithConstructorTypeBoolean: Defaults["TupleType"]["String"] & Defaults["ConstructorType"]["Boolean"] = ["two"];
const RemoveIntersectionTypeConstructorTypeBooleanFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]
const IntersectionTypeTupleTypeStringWithConstructorTypeAny: Defaults["TupleType"]["String"] & Defaults["ConstructorType"]["Any"] = ["two"];
const RemoveIntersectionTypeConstructorTypeAnyFromTupleTypeString: Defaults["TupleType"]["String"]= ["two"]

const IntersectionTypeTupleTypeNumberWithParenthesizedTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = [2];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithParenthesizedTypeObject: Defaults["TupleType"]["Number"] & Defaults["ParenthesizedType"]["Object"] = [2];
const RemoveIntersectionTypeParenthesizedTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithParenthesizedTypeString: Defaults["TupleType"]["Number"] & Defaults["ParenthesizedType"]["String"] = [2];
const RemoveIntersectionTypeParenthesizedTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithParenthesizedTypeNumber: Defaults["TupleType"]["Number"] & Defaults["ParenthesizedType"]["Number"] = [2];
const RemoveIntersectionTypeParenthesizedTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithParenthesizedTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = [2];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithParenthesizedTypeAny: Defaults["TupleType"]["Number"] & Defaults["ParenthesizedType"]["Any"] = [2];
const RemoveIntersectionTypeParenthesizedTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithTypeReferenceBuiltinLiteral: Defaults["TupleType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferenceBuiltinObject: Defaults["TupleType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferenceBuiltinString: Defaults["TupleType"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferenceBuiltinNumber: Defaults["TupleType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferenceBuiltinBoolean: Defaults["TupleType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferenceBuiltinAny: Defaults["TupleType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithTypeReferencePredefinedLiteral: Defaults["TupleType"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferencePredefinedObject: Defaults["TupleType"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferencePredefinedString: Defaults["TupleType"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferencePredefinedNumber: Defaults["TupleType"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferencePredefinedBoolean: Defaults["TupleType"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeReferencePredefinedAny: Defaults["TupleType"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithUnionTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["UnionType"]["Literal"] = [2];
const RemoveIntersectionTypeUnionTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithUnionTypeObject: Defaults["TupleType"]["Number"] & Defaults["UnionType"]["Object"] = [2];
const RemoveIntersectionTypeUnionTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithUnionTypeString: Defaults["TupleType"]["Number"] & Defaults["UnionType"]["String"] = [2];
const RemoveIntersectionTypeUnionTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithUnionTypeNumber: Defaults["TupleType"]["Number"] & Defaults["UnionType"]["Number"] = [2];
const RemoveIntersectionTypeUnionTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithUnionTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["UnionType"]["Boolean"] = [2];
const RemoveIntersectionTypeUnionTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithUnionTypeAny: Defaults["TupleType"]["Number"] & Defaults["UnionType"]["Any"] = [2];
const RemoveIntersectionTypeUnionTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithIntersectionTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["IntersectionType"]["Literal"] = [2];
const RemoveIntersectionTypeIntersectionTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithIntersectionTypeObject: Defaults["TupleType"]["Number"] & Defaults["IntersectionType"]["Object"] = [2];
const RemoveIntersectionTypeIntersectionTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithIntersectionTypeString: Defaults["TupleType"]["Number"] & Defaults["IntersectionType"]["String"] = [2];
const RemoveIntersectionTypeIntersectionTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithIntersectionTypeNumber: Defaults["TupleType"]["Number"] & Defaults["IntersectionType"]["Number"] = [2];
const RemoveIntersectionTypeIntersectionTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithIntersectionTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["IntersectionType"]["Boolean"] = [2];
const RemoveIntersectionTypeIntersectionTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithIntersectionTypeAny: Defaults["TupleType"]["Number"] & Defaults["IntersectionType"]["Any"] = [2];
const RemoveIntersectionTypeIntersectionTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithTypeLiteralLiteral: Defaults["TupleType"]["Number"] & Defaults["TypeLiteral"]["Literal"] = [2];
const RemoveIntersectionTypeTypeLiteralLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeLiteralObject: Defaults["TupleType"]["Number"] & Defaults["TypeLiteral"]["Object"] = [2];
const RemoveIntersectionTypeTypeLiteralObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeLiteralString: Defaults["TupleType"]["Number"] & Defaults["TypeLiteral"]["String"] = [2];
const RemoveIntersectionTypeTypeLiteralStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeLiteralNumber: Defaults["TupleType"]["Number"] & Defaults["TypeLiteral"]["Number"] = [2];
const RemoveIntersectionTypeTypeLiteralNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeLiteralBoolean: Defaults["TupleType"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = [2];
const RemoveIntersectionTypeTypeLiteralBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTypeLiteralAny: Defaults["TupleType"]["Number"] & Defaults["TypeLiteral"]["Any"] = [2];
const RemoveIntersectionTypeTypeLiteralAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithTupleTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["TupleType"]["Literal"] = [2];
const RemoveIntersectionTypeTupleTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTupleTypeObject: Defaults["TupleType"]["Number"] & Defaults["TupleType"]["Object"] = [2];
const RemoveIntersectionTypeTupleTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTupleTypeString: Defaults["TupleType"]["Number"] & Defaults["TupleType"]["String"] = [2];
const RemoveIntersectionTypeTupleTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTupleTypeNumber: Defaults["TupleType"]["Number"] & Defaults["TupleType"]["Number"] = [2];
const RemoveIntersectionTypeTupleTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTupleTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["TupleType"]["Boolean"] = [2];
const RemoveIntersectionTypeTupleTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithTupleTypeAny: Defaults["TupleType"]["Number"] & Defaults["TupleType"]["Any"] = [2];
const RemoveIntersectionTypeTupleTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithArrayTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["ArrayType"]["Literal"] = [2];
const RemoveIntersectionTypeArrayTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithArrayTypeObject: Defaults["TupleType"]["Number"] & Defaults["ArrayType"]["Object"] = [2];
const RemoveIntersectionTypeArrayTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithArrayTypeString: Defaults["TupleType"]["Number"] & Defaults["ArrayType"]["String"] = [2];
const RemoveIntersectionTypeArrayTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithArrayTypeNumber: Defaults["TupleType"]["Number"] & Defaults["ArrayType"]["Number"] = [2];
const RemoveIntersectionTypeArrayTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithArrayTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["ArrayType"]["Boolean"] = [2];
const RemoveIntersectionTypeArrayTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithArrayTypeAny: Defaults["TupleType"]["Number"] & Defaults["ArrayType"]["Any"] = [2];
const RemoveIntersectionTypeArrayTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithFunctionTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["FunctionType"]["Literal"] = [2];
const RemoveIntersectionTypeFunctionTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithFunctionTypeObject: Defaults["TupleType"]["Number"] & Defaults["FunctionType"]["Object"] = [2];
const RemoveIntersectionTypeFunctionTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithFunctionTypeString: Defaults["TupleType"]["Number"] & Defaults["FunctionType"]["String"] = [2];
const RemoveIntersectionTypeFunctionTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithFunctionTypeNumber: Defaults["TupleType"]["Number"] & Defaults["FunctionType"]["Number"] = [2];
const RemoveIntersectionTypeFunctionTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithFunctionTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["FunctionType"]["Boolean"] = [2];
const RemoveIntersectionTypeFunctionTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithFunctionTypeAny: Defaults["TupleType"]["Number"] & Defaults["FunctionType"]["Any"] = [2];
const RemoveIntersectionTypeFunctionTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeNumberWithConstructorTypeLiteral: Defaults["TupleType"]["Number"] & Defaults["ConstructorType"]["Literal"] = [2];
const RemoveIntersectionTypeConstructorTypeLiteralFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithConstructorTypeObject: Defaults["TupleType"]["Number"] & Defaults["ConstructorType"]["Object"] = [2];
const RemoveIntersectionTypeConstructorTypeObjectFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithConstructorTypeString: Defaults["TupleType"]["Number"] & Defaults["ConstructorType"]["String"] = [2];
const RemoveIntersectionTypeConstructorTypeStringFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithConstructorTypeNumber: Defaults["TupleType"]["Number"] & Defaults["ConstructorType"]["Number"] = [2];
const RemoveIntersectionTypeConstructorTypeNumberFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithConstructorTypeBoolean: Defaults["TupleType"]["Number"] & Defaults["ConstructorType"]["Boolean"] = [2];
const RemoveIntersectionTypeConstructorTypeBooleanFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]
const IntersectionTypeTupleTypeNumberWithConstructorTypeAny: Defaults["TupleType"]["Number"] & Defaults["ConstructorType"]["Any"] = [2];
const RemoveIntersectionTypeConstructorTypeAnyFromTupleTypeNumber: Defaults["TupleType"]["Number"]= [2]

const IntersectionTypeTupleTypeBooleanWithParenthesizedTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = [true];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithParenthesizedTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = [true];
const RemoveIntersectionTypeParenthesizedTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithParenthesizedTypeString: Defaults["TupleType"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = [true];
const RemoveIntersectionTypeParenthesizedTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithParenthesizedTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = [true];
const RemoveIntersectionTypeParenthesizedTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithParenthesizedTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = [true];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithParenthesizedTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = [true];
const RemoveIntersectionTypeParenthesizedTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithTypeReferenceBuiltinLiteral: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [true];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferenceBuiltinObject: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = [true];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferenceBuiltinString: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = [true];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferenceBuiltinNumber: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = [true];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferenceBuiltinBoolean: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [true];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferenceBuiltinAny: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = [true];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithTypeReferencePredefinedLiteral: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = [true];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferencePredefinedObject: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = [true];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferencePredefinedString: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = [true];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferencePredefinedNumber: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = [true];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferencePredefinedBoolean: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = [true];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeReferencePredefinedAny: Defaults["TupleType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = [true];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithUnionTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["UnionType"]["Literal"] = [true];
const RemoveIntersectionTypeUnionTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithUnionTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["UnionType"]["Object"] = [true];
const RemoveIntersectionTypeUnionTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithUnionTypeString: Defaults["TupleType"]["Boolean"] & Defaults["UnionType"]["String"] = [true];
const RemoveIntersectionTypeUnionTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithUnionTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["UnionType"]["Number"] = [true];
const RemoveIntersectionTypeUnionTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithUnionTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["UnionType"]["Boolean"] = [true];
const RemoveIntersectionTypeUnionTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithUnionTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["UnionType"]["Any"] = [true];
const RemoveIntersectionTypeUnionTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithIntersectionTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = [true];
const RemoveIntersectionTypeIntersectionTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithIntersectionTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["IntersectionType"]["Object"] = [true];
const RemoveIntersectionTypeIntersectionTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithIntersectionTypeString: Defaults["TupleType"]["Boolean"] & Defaults["IntersectionType"]["String"] = [true];
const RemoveIntersectionTypeIntersectionTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithIntersectionTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["IntersectionType"]["Number"] = [true];
const RemoveIntersectionTypeIntersectionTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithIntersectionTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = [true];
const RemoveIntersectionTypeIntersectionTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithIntersectionTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["IntersectionType"]["Any"] = [true];
const RemoveIntersectionTypeIntersectionTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithTypeLiteralLiteral: Defaults["TupleType"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = [true];
const RemoveIntersectionTypeTypeLiteralLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeLiteralObject: Defaults["TupleType"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = [true];
const RemoveIntersectionTypeTypeLiteralObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeLiteralString: Defaults["TupleType"]["Boolean"] & Defaults["TypeLiteral"]["String"] = [true];
const RemoveIntersectionTypeTypeLiteralStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeLiteralNumber: Defaults["TupleType"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = [true];
const RemoveIntersectionTypeTypeLiteralNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeLiteralBoolean: Defaults["TupleType"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = [true];
const RemoveIntersectionTypeTypeLiteralBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTypeLiteralAny: Defaults["TupleType"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = [true];
const RemoveIntersectionTypeTypeLiteralAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithTupleTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["TupleType"]["Literal"] = [true];
const RemoveIntersectionTypeTupleTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTupleTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["TupleType"]["Object"] = [true];
const RemoveIntersectionTypeTupleTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTupleTypeString: Defaults["TupleType"]["Boolean"] & Defaults["TupleType"]["String"] = [true];
const RemoveIntersectionTypeTupleTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTupleTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["TupleType"]["Number"] = [true];
const RemoveIntersectionTypeTupleTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTupleTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["TupleType"]["Boolean"] = [true];
const RemoveIntersectionTypeTupleTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithTupleTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["TupleType"]["Any"] = [true];
const RemoveIntersectionTypeTupleTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithArrayTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["ArrayType"]["Literal"] = [true];
const RemoveIntersectionTypeArrayTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithArrayTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["ArrayType"]["Object"] = [true];
const RemoveIntersectionTypeArrayTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithArrayTypeString: Defaults["TupleType"]["Boolean"] & Defaults["ArrayType"]["String"] = [true];
const RemoveIntersectionTypeArrayTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithArrayTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["ArrayType"]["Number"] = [true];
const RemoveIntersectionTypeArrayTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithArrayTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = [true];
const RemoveIntersectionTypeArrayTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithArrayTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["ArrayType"]["Any"] = [true];
const RemoveIntersectionTypeArrayTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithFunctionTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["FunctionType"]["Literal"] = [true];
const RemoveIntersectionTypeFunctionTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithFunctionTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["FunctionType"]["Object"] = [true];
const RemoveIntersectionTypeFunctionTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithFunctionTypeString: Defaults["TupleType"]["Boolean"] & Defaults["FunctionType"]["String"] = [true];
const RemoveIntersectionTypeFunctionTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithFunctionTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["FunctionType"]["Number"] = [true];
const RemoveIntersectionTypeFunctionTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithFunctionTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = [true];
const RemoveIntersectionTypeFunctionTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithFunctionTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["FunctionType"]["Any"] = [true];
const RemoveIntersectionTypeFunctionTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeBooleanWithConstructorTypeLiteral: Defaults["TupleType"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = [true];
const RemoveIntersectionTypeConstructorTypeLiteralFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithConstructorTypeObject: Defaults["TupleType"]["Boolean"] & Defaults["ConstructorType"]["Object"] = [true];
const RemoveIntersectionTypeConstructorTypeObjectFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithConstructorTypeString: Defaults["TupleType"]["Boolean"] & Defaults["ConstructorType"]["String"] = [true];
const RemoveIntersectionTypeConstructorTypeStringFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithConstructorTypeNumber: Defaults["TupleType"]["Boolean"] & Defaults["ConstructorType"]["Number"] = [true];
const RemoveIntersectionTypeConstructorTypeNumberFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithConstructorTypeBoolean: Defaults["TupleType"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = [true];
const RemoveIntersectionTypeConstructorTypeBooleanFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]
const IntersectionTypeTupleTypeBooleanWithConstructorTypeAny: Defaults["TupleType"]["Boolean"] & Defaults["ConstructorType"]["Any"] = [true];
const RemoveIntersectionTypeConstructorTypeAnyFromTupleTypeBoolean: Defaults["TupleType"]["Boolean"]= [true]

const IntersectionTypeTupleTypeAnyWithParenthesizedTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = [2];
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithParenthesizedTypeObject: Defaults["TupleType"]["Any"] & Defaults["ParenthesizedType"]["Object"] = [2];
const RemoveIntersectionTypeParenthesizedTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithParenthesizedTypeString: Defaults["TupleType"]["Any"] & Defaults["ParenthesizedType"]["String"] = [2];
const RemoveIntersectionTypeParenthesizedTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithParenthesizedTypeNumber: Defaults["TupleType"]["Any"] & Defaults["ParenthesizedType"]["Number"] = [2];
const RemoveIntersectionTypeParenthesizedTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithParenthesizedTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = [2];
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithParenthesizedTypeAny: Defaults["TupleType"]["Any"] & Defaults["ParenthesizedType"]["Any"] = [2];
const RemoveIntersectionTypeParenthesizedTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithTypeReferenceBuiltinLiteral: Defaults["TupleType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferenceBuiltinObject: Defaults["TupleType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferenceBuiltinString: Defaults["TupleType"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferenceBuiltinNumber: Defaults["TupleType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferenceBuiltinBoolean: Defaults["TupleType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferenceBuiltinAny: Defaults["TupleType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = [2];
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithTypeReferencePredefinedLiteral: Defaults["TupleType"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferencePredefinedObject: Defaults["TupleType"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferencePredefinedString: Defaults["TupleType"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferencePredefinedNumber: Defaults["TupleType"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferencePredefinedBoolean: Defaults["TupleType"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeReferencePredefinedAny: Defaults["TupleType"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = [2];
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithUnionTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["UnionType"]["Literal"] = [2];
const RemoveIntersectionTypeUnionTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithUnionTypeObject: Defaults["TupleType"]["Any"] & Defaults["UnionType"]["Object"] = [2];
const RemoveIntersectionTypeUnionTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithUnionTypeString: Defaults["TupleType"]["Any"] & Defaults["UnionType"]["String"] = [2];
const RemoveIntersectionTypeUnionTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithUnionTypeNumber: Defaults["TupleType"]["Any"] & Defaults["UnionType"]["Number"] = [2];
const RemoveIntersectionTypeUnionTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithUnionTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["UnionType"]["Boolean"] = [2];
const RemoveIntersectionTypeUnionTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithUnionTypeAny: Defaults["TupleType"]["Any"] & Defaults["UnionType"]["Any"] = [2];
const RemoveIntersectionTypeUnionTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithIntersectionTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["IntersectionType"]["Literal"] = [2];
const RemoveIntersectionTypeIntersectionTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithIntersectionTypeObject: Defaults["TupleType"]["Any"] & Defaults["IntersectionType"]["Object"] = [2];
const RemoveIntersectionTypeIntersectionTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithIntersectionTypeString: Defaults["TupleType"]["Any"] & Defaults["IntersectionType"]["String"] = [2];
const RemoveIntersectionTypeIntersectionTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithIntersectionTypeNumber: Defaults["TupleType"]["Any"] & Defaults["IntersectionType"]["Number"] = [2];
const RemoveIntersectionTypeIntersectionTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithIntersectionTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["IntersectionType"]["Boolean"] = [2];
const RemoveIntersectionTypeIntersectionTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithIntersectionTypeAny: Defaults["TupleType"]["Any"] & Defaults["IntersectionType"]["Any"] = [2];
const RemoveIntersectionTypeIntersectionTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithTypeLiteralLiteral: Defaults["TupleType"]["Any"] & Defaults["TypeLiteral"]["Literal"] = [2];
const RemoveIntersectionTypeTypeLiteralLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeLiteralObject: Defaults["TupleType"]["Any"] & Defaults["TypeLiteral"]["Object"] = [2];
const RemoveIntersectionTypeTypeLiteralObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeLiteralString: Defaults["TupleType"]["Any"] & Defaults["TypeLiteral"]["String"] = [2];
const RemoveIntersectionTypeTypeLiteralStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeLiteralNumber: Defaults["TupleType"]["Any"] & Defaults["TypeLiteral"]["Number"] = [2];
const RemoveIntersectionTypeTypeLiteralNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeLiteralBoolean: Defaults["TupleType"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = [2];
const RemoveIntersectionTypeTypeLiteralBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTypeLiteralAny: Defaults["TupleType"]["Any"] & Defaults["TypeLiteral"]["Any"] = [2];
const RemoveIntersectionTypeTypeLiteralAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithTupleTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["TupleType"]["Literal"] = [2];
const RemoveIntersectionTypeTupleTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTupleTypeObject: Defaults["TupleType"]["Any"] & Defaults["TupleType"]["Object"] = [2];
const RemoveIntersectionTypeTupleTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTupleTypeString: Defaults["TupleType"]["Any"] & Defaults["TupleType"]["String"] = [2];
const RemoveIntersectionTypeTupleTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTupleTypeNumber: Defaults["TupleType"]["Any"] & Defaults["TupleType"]["Number"] = [2];
const RemoveIntersectionTypeTupleTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTupleTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["TupleType"]["Boolean"] = [2];
const RemoveIntersectionTypeTupleTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithTupleTypeAny: Defaults["TupleType"]["Any"] & Defaults["TupleType"]["Any"] = [2];
const RemoveIntersectionTypeTupleTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithArrayTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["ArrayType"]["Literal"] = [2];
const RemoveIntersectionTypeArrayTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithArrayTypeObject: Defaults["TupleType"]["Any"] & Defaults["ArrayType"]["Object"] = [2];
const RemoveIntersectionTypeArrayTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithArrayTypeString: Defaults["TupleType"]["Any"] & Defaults["ArrayType"]["String"] = [2];
const RemoveIntersectionTypeArrayTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithArrayTypeNumber: Defaults["TupleType"]["Any"] & Defaults["ArrayType"]["Number"] = [2];
const RemoveIntersectionTypeArrayTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithArrayTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["ArrayType"]["Boolean"] = [2];
const RemoveIntersectionTypeArrayTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithArrayTypeAny: Defaults["TupleType"]["Any"] & Defaults["ArrayType"]["Any"] = [2];
const RemoveIntersectionTypeArrayTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithFunctionTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["FunctionType"]["Literal"] = [2];
const RemoveIntersectionTypeFunctionTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithFunctionTypeObject: Defaults["TupleType"]["Any"] & Defaults["FunctionType"]["Object"] = [2];
const RemoveIntersectionTypeFunctionTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithFunctionTypeString: Defaults["TupleType"]["Any"] & Defaults["FunctionType"]["String"] = [2];
const RemoveIntersectionTypeFunctionTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithFunctionTypeNumber: Defaults["TupleType"]["Any"] & Defaults["FunctionType"]["Number"] = [2];
const RemoveIntersectionTypeFunctionTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithFunctionTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["FunctionType"]["Boolean"] = [2];
const RemoveIntersectionTypeFunctionTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithFunctionTypeAny: Defaults["TupleType"]["Any"] & Defaults["FunctionType"]["Any"] = [2];
const RemoveIntersectionTypeFunctionTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

const IntersectionTypeTupleTypeAnyWithConstructorTypeLiteral: Defaults["TupleType"]["Any"] & Defaults["ConstructorType"]["Literal"] = [2];
const RemoveIntersectionTypeConstructorTypeLiteralFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithConstructorTypeObject: Defaults["TupleType"]["Any"] & Defaults["ConstructorType"]["Object"] = [2];
const RemoveIntersectionTypeConstructorTypeObjectFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithConstructorTypeString: Defaults["TupleType"]["Any"] & Defaults["ConstructorType"]["String"] = [2];
const RemoveIntersectionTypeConstructorTypeStringFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithConstructorTypeNumber: Defaults["TupleType"]["Any"] & Defaults["ConstructorType"]["Number"] = [2];
const RemoveIntersectionTypeConstructorTypeNumberFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithConstructorTypeBoolean: Defaults["TupleType"]["Any"] & Defaults["ConstructorType"]["Boolean"] = [2];
const RemoveIntersectionTypeConstructorTypeBooleanFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]
const IntersectionTypeTupleTypeAnyWithConstructorTypeAny: Defaults["TupleType"]["Any"] & Defaults["ConstructorType"]["Any"] = [2];
const RemoveIntersectionTypeConstructorTypeAnyFromTupleTypeAny: Defaults["TupleType"]["Any"]= [2]

