import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - UnionType
const IntersectionTypeUnionTypeLiteralWithParenthesizedTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = 1;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithParenthesizedTypeObject: Defaults["UnionType"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = 1;
const RemoveIntersectionTypeParenthesizedTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithParenthesizedTypeString: Defaults["UnionType"]["Literal"] & Defaults["ParenthesizedType"]["String"] = 1;
const RemoveIntersectionTypeParenthesizedTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithParenthesizedTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = 1;
const RemoveIntersectionTypeParenthesizedTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithParenthesizedTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = 1;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithParenthesizedTypeAny: Defaults["UnionType"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = 1;
const RemoveIntersectionTypeParenthesizedTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithTypeReferenceBuiltinLiteral: Defaults["UnionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferenceBuiltinObject: Defaults["UnionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferenceBuiltinString: Defaults["UnionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferenceBuiltinNumber: Defaults["UnionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferenceBuiltinBoolean: Defaults["UnionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferenceBuiltinAny: Defaults["UnionType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithTypeReferencePredefinedLiteral: Defaults["UnionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferencePredefinedObject: Defaults["UnionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferencePredefinedString: Defaults["UnionType"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferencePredefinedNumber: Defaults["UnionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferencePredefinedBoolean: Defaults["UnionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeReferencePredefinedAny: Defaults["UnionType"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithUnionTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["UnionType"]["Literal"] = 1;
const RemoveIntersectionTypeUnionTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithUnionTypeObject: Defaults["UnionType"]["Literal"] & Defaults["UnionType"]["Object"] = 1;
const RemoveIntersectionTypeUnionTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithUnionTypeString: Defaults["UnionType"]["Literal"] & Defaults["UnionType"]["String"] = 1;
const RemoveIntersectionTypeUnionTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithUnionTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["UnionType"]["Number"] = 1;
const RemoveIntersectionTypeUnionTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithUnionTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["UnionType"]["Boolean"] = 1;
const RemoveIntersectionTypeUnionTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithUnionTypeAny: Defaults["UnionType"]["Literal"] & Defaults["UnionType"]["Any"] = 1;
const RemoveIntersectionTypeUnionTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithIntersectionTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["IntersectionType"]["Literal"] = 1;
const RemoveIntersectionTypeIntersectionTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithIntersectionTypeObject: Defaults["UnionType"]["Literal"] & Defaults["IntersectionType"]["Object"] = 1;
const RemoveIntersectionTypeIntersectionTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithIntersectionTypeString: Defaults["UnionType"]["Literal"] & Defaults["IntersectionType"]["String"] = 1;
const RemoveIntersectionTypeIntersectionTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithIntersectionTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["IntersectionType"]["Number"] = 1;
const RemoveIntersectionTypeIntersectionTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithIntersectionTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = 1;
const RemoveIntersectionTypeIntersectionTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithIntersectionTypeAny: Defaults["UnionType"]["Literal"] & Defaults["IntersectionType"]["Any"] = 1;
const RemoveIntersectionTypeIntersectionTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithTypeLiteralLiteral: Defaults["UnionType"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = 1;
const RemoveIntersectionTypeTypeLiteralLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeLiteralObject: Defaults["UnionType"]["Literal"] & Defaults["TypeLiteral"]["Object"] = 1;
const RemoveIntersectionTypeTypeLiteralObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeLiteralString: Defaults["UnionType"]["Literal"] & Defaults["TypeLiteral"]["String"] = 1;
const RemoveIntersectionTypeTypeLiteralStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeLiteralNumber: Defaults["UnionType"]["Literal"] & Defaults["TypeLiteral"]["Number"] = 1;
const RemoveIntersectionTypeTypeLiteralNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeLiteralBoolean: Defaults["UnionType"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeLiteralBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTypeLiteralAny: Defaults["UnionType"]["Literal"] & Defaults["TypeLiteral"]["Any"] = 1;
const RemoveIntersectionTypeTypeLiteralAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithTupleTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["TupleType"]["Literal"] = 1;
const RemoveIntersectionTypeTupleTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTupleTypeObject: Defaults["UnionType"]["Literal"] & Defaults["TupleType"]["Object"] = 1;
const RemoveIntersectionTypeTupleTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTupleTypeString: Defaults["UnionType"]["Literal"] & Defaults["TupleType"]["String"] = 1;
const RemoveIntersectionTypeTupleTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTupleTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["TupleType"]["Number"] = 1;
const RemoveIntersectionTypeTupleTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTupleTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["TupleType"]["Boolean"] = 1;
const RemoveIntersectionTypeTupleTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithTupleTypeAny: Defaults["UnionType"]["Literal"] & Defaults["TupleType"]["Any"] = 1;
const RemoveIntersectionTypeTupleTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithArrayTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["ArrayType"]["Literal"] = 1;
const RemoveIntersectionTypeArrayTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithArrayTypeObject: Defaults["UnionType"]["Literal"] & Defaults["ArrayType"]["Object"] = 1;
const RemoveIntersectionTypeArrayTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithArrayTypeString: Defaults["UnionType"]["Literal"] & Defaults["ArrayType"]["String"] = 1;
const RemoveIntersectionTypeArrayTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithArrayTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["ArrayType"]["Number"] = 1;
const RemoveIntersectionTypeArrayTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithArrayTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["ArrayType"]["Boolean"] = 1;
const RemoveIntersectionTypeArrayTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithArrayTypeAny: Defaults["UnionType"]["Literal"] & Defaults["ArrayType"]["Any"] = 1;
const RemoveIntersectionTypeArrayTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithFunctionTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["FunctionType"]["Literal"] = 1;
const RemoveIntersectionTypeFunctionTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithFunctionTypeObject: Defaults["UnionType"]["Literal"] & Defaults["FunctionType"]["Object"] = 1;
const RemoveIntersectionTypeFunctionTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithFunctionTypeString: Defaults["UnionType"]["Literal"] & Defaults["FunctionType"]["String"] = 1;
const RemoveIntersectionTypeFunctionTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithFunctionTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["FunctionType"]["Number"] = 1;
const RemoveIntersectionTypeFunctionTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithFunctionTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["FunctionType"]["Boolean"] = 1;
const RemoveIntersectionTypeFunctionTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithFunctionTypeAny: Defaults["UnionType"]["Literal"] & Defaults["FunctionType"]["Any"] = 1;
const RemoveIntersectionTypeFunctionTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeLiteralWithConstructorTypeLiteral: Defaults["UnionType"]["Literal"] & Defaults["ConstructorType"]["Literal"] = 1;
const RemoveIntersectionTypeConstructorTypeLiteralFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithConstructorTypeObject: Defaults["UnionType"]["Literal"] & Defaults["ConstructorType"]["Object"] = 1;
const RemoveIntersectionTypeConstructorTypeObjectFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithConstructorTypeString: Defaults["UnionType"]["Literal"] & Defaults["ConstructorType"]["String"] = 1;
const RemoveIntersectionTypeConstructorTypeStringFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithConstructorTypeNumber: Defaults["UnionType"]["Literal"] & Defaults["ConstructorType"]["Number"] = 1;
const RemoveIntersectionTypeConstructorTypeNumberFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithConstructorTypeBoolean: Defaults["UnionType"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = 1;
const RemoveIntersectionTypeConstructorTypeBooleanFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1
const IntersectionTypeUnionTypeLiteralWithConstructorTypeAny: Defaults["UnionType"]["Literal"] & Defaults["ConstructorType"]["Any"] = 1;
const RemoveIntersectionTypeConstructorTypeAnyFromUnionTypeLiteral: Defaults["UnionType"]["Literal"]= 1

const IntersectionTypeUnionTypeObjectWithParenthesizedTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = {};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithParenthesizedTypeObject: Defaults["UnionType"]["Object"] & Defaults["ParenthesizedType"]["Object"] = {};
const RemoveIntersectionTypeParenthesizedTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithParenthesizedTypeString: Defaults["UnionType"]["Object"] & Defaults["ParenthesizedType"]["String"] = {};
const RemoveIntersectionTypeParenthesizedTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithParenthesizedTypeNumber: Defaults["UnionType"]["Object"] & Defaults["ParenthesizedType"]["Number"] = {};
const RemoveIntersectionTypeParenthesizedTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithParenthesizedTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = {};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithParenthesizedTypeAny: Defaults["UnionType"]["Object"] & Defaults["ParenthesizedType"]["Any"] = {};
const RemoveIntersectionTypeParenthesizedTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithTypeReferenceBuiltinLiteral: Defaults["UnionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferenceBuiltinObject: Defaults["UnionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferenceBuiltinString: Defaults["UnionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferenceBuiltinNumber: Defaults["UnionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferenceBuiltinBoolean: Defaults["UnionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferenceBuiltinAny: Defaults["UnionType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithTypeReferencePredefinedLiteral: Defaults["UnionType"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferencePredefinedObject: Defaults["UnionType"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferencePredefinedString: Defaults["UnionType"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferencePredefinedNumber: Defaults["UnionType"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferencePredefinedBoolean: Defaults["UnionType"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeReferencePredefinedAny: Defaults["UnionType"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithUnionTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["UnionType"]["Literal"] = {};
const RemoveIntersectionTypeUnionTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithUnionTypeObject: Defaults["UnionType"]["Object"] & Defaults["UnionType"]["Object"] = {};
const RemoveIntersectionTypeUnionTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithUnionTypeString: Defaults["UnionType"]["Object"] & Defaults["UnionType"]["String"] = {};
const RemoveIntersectionTypeUnionTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithUnionTypeNumber: Defaults["UnionType"]["Object"] & Defaults["UnionType"]["Number"] = {};
const RemoveIntersectionTypeUnionTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithUnionTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["UnionType"]["Boolean"] = {};
const RemoveIntersectionTypeUnionTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithUnionTypeAny: Defaults["UnionType"]["Object"] & Defaults["UnionType"]["Any"] = {};
const RemoveIntersectionTypeUnionTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithIntersectionTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["IntersectionType"]["Literal"] = {};
const RemoveIntersectionTypeIntersectionTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithIntersectionTypeObject: Defaults["UnionType"]["Object"] & Defaults["IntersectionType"]["Object"] = {};
const RemoveIntersectionTypeIntersectionTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithIntersectionTypeString: Defaults["UnionType"]["Object"] & Defaults["IntersectionType"]["String"] = {};
const RemoveIntersectionTypeIntersectionTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithIntersectionTypeNumber: Defaults["UnionType"]["Object"] & Defaults["IntersectionType"]["Number"] = {};
const RemoveIntersectionTypeIntersectionTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithIntersectionTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["IntersectionType"]["Boolean"] = {};
const RemoveIntersectionTypeIntersectionTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithIntersectionTypeAny: Defaults["UnionType"]["Object"] & Defaults["IntersectionType"]["Any"] = {};
const RemoveIntersectionTypeIntersectionTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithTypeLiteralLiteral: Defaults["UnionType"]["Object"] & Defaults["TypeLiteral"]["Literal"] = {};
const RemoveIntersectionTypeTypeLiteralLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeLiteralObject: Defaults["UnionType"]["Object"] & Defaults["TypeLiteral"]["Object"] = {};
const RemoveIntersectionTypeTypeLiteralObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeLiteralString: Defaults["UnionType"]["Object"] & Defaults["TypeLiteral"]["String"] = {};
const RemoveIntersectionTypeTypeLiteralStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeLiteralNumber: Defaults["UnionType"]["Object"] & Defaults["TypeLiteral"]["Number"] = {};
const RemoveIntersectionTypeTypeLiteralNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeLiteralBoolean: Defaults["UnionType"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = {};
const RemoveIntersectionTypeTypeLiteralBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTypeLiteralAny: Defaults["UnionType"]["Object"] & Defaults["TypeLiteral"]["Any"] = {};
const RemoveIntersectionTypeTypeLiteralAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithTupleTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["TupleType"]["Literal"] = {};
const RemoveIntersectionTypeTupleTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTupleTypeObject: Defaults["UnionType"]["Object"] & Defaults["TupleType"]["Object"] = {};
const RemoveIntersectionTypeTupleTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTupleTypeString: Defaults["UnionType"]["Object"] & Defaults["TupleType"]["String"] = {};
const RemoveIntersectionTypeTupleTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTupleTypeNumber: Defaults["UnionType"]["Object"] & Defaults["TupleType"]["Number"] = {};
const RemoveIntersectionTypeTupleTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTupleTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["TupleType"]["Boolean"] = {};
const RemoveIntersectionTypeTupleTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithTupleTypeAny: Defaults["UnionType"]["Object"] & Defaults["TupleType"]["Any"] = {};
const RemoveIntersectionTypeTupleTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithArrayTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["ArrayType"]["Literal"] = {};
const RemoveIntersectionTypeArrayTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithArrayTypeObject: Defaults["UnionType"]["Object"] & Defaults["ArrayType"]["Object"] = {};
const RemoveIntersectionTypeArrayTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithArrayTypeString: Defaults["UnionType"]["Object"] & Defaults["ArrayType"]["String"] = {};
const RemoveIntersectionTypeArrayTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithArrayTypeNumber: Defaults["UnionType"]["Object"] & Defaults["ArrayType"]["Number"] = {};
const RemoveIntersectionTypeArrayTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithArrayTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["ArrayType"]["Boolean"] = {};
const RemoveIntersectionTypeArrayTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithArrayTypeAny: Defaults["UnionType"]["Object"] & Defaults["ArrayType"]["Any"] = {};
const RemoveIntersectionTypeArrayTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithFunctionTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["FunctionType"]["Literal"] = {};
const RemoveIntersectionTypeFunctionTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithFunctionTypeObject: Defaults["UnionType"]["Object"] & Defaults["FunctionType"]["Object"] = {};
const RemoveIntersectionTypeFunctionTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithFunctionTypeString: Defaults["UnionType"]["Object"] & Defaults["FunctionType"]["String"] = {};
const RemoveIntersectionTypeFunctionTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithFunctionTypeNumber: Defaults["UnionType"]["Object"] & Defaults["FunctionType"]["Number"] = {};
const RemoveIntersectionTypeFunctionTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithFunctionTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["FunctionType"]["Boolean"] = {};
const RemoveIntersectionTypeFunctionTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithFunctionTypeAny: Defaults["UnionType"]["Object"] & Defaults["FunctionType"]["Any"] = {};
const RemoveIntersectionTypeFunctionTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeObjectWithConstructorTypeLiteral: Defaults["UnionType"]["Object"] & Defaults["ConstructorType"]["Literal"] = {};
const RemoveIntersectionTypeConstructorTypeLiteralFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithConstructorTypeObject: Defaults["UnionType"]["Object"] & Defaults["ConstructorType"]["Object"] = {};
const RemoveIntersectionTypeConstructorTypeObjectFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithConstructorTypeString: Defaults["UnionType"]["Object"] & Defaults["ConstructorType"]["String"] = {};
const RemoveIntersectionTypeConstructorTypeStringFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithConstructorTypeNumber: Defaults["UnionType"]["Object"] & Defaults["ConstructorType"]["Number"] = {};
const RemoveIntersectionTypeConstructorTypeNumberFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithConstructorTypeBoolean: Defaults["UnionType"]["Object"] & Defaults["ConstructorType"]["Boolean"] = {};
const RemoveIntersectionTypeConstructorTypeBooleanFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}
const IntersectionTypeUnionTypeObjectWithConstructorTypeAny: Defaults["UnionType"]["Object"] & Defaults["ConstructorType"]["Any"] = {};
const RemoveIntersectionTypeConstructorTypeAnyFromUnionTypeObject: Defaults["UnionType"]["Object"]= {}

const IntersectionTypeUnionTypeStringWithParenthesizedTypeLiteral: Defaults["UnionType"]["String"] & Defaults["ParenthesizedType"]["Literal"] = "two";
const RemoveIntersectionTypeParenthesizedTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithParenthesizedTypeObject: Defaults["UnionType"]["String"] & Defaults["ParenthesizedType"]["Object"] = "two";
const RemoveIntersectionTypeParenthesizedTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithParenthesizedTypeString: Defaults["UnionType"]["String"] & Defaults["ParenthesizedType"]["String"] = "two";
const RemoveIntersectionTypeParenthesizedTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithParenthesizedTypeNumber: Defaults["UnionType"]["String"] & Defaults["ParenthesizedType"]["Number"] = "two";
const RemoveIntersectionTypeParenthesizedTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithParenthesizedTypeBoolean: Defaults["UnionType"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = "two";
const RemoveIntersectionTypeParenthesizedTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithParenthesizedTypeAny: Defaults["UnionType"]["String"] & Defaults["ParenthesizedType"]["Any"] = "two";
const RemoveIntersectionTypeParenthesizedTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithTypeReferenceBuiltinLiteral: Defaults["UnionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferenceBuiltinObject: Defaults["UnionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferenceBuiltinString: Defaults["UnionType"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferenceBuiltinNumber: Defaults["UnionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferenceBuiltinBoolean: Defaults["UnionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferenceBuiltinAny: Defaults["UnionType"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithTypeReferencePredefinedLiteral: Defaults["UnionType"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferencePredefinedObject: Defaults["UnionType"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferencePredefinedString: Defaults["UnionType"]["String"] & Defaults["TypeReferencePredefined"]["String"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferencePredefinedNumber: Defaults["UnionType"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferencePredefinedBoolean: Defaults["UnionType"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeReferencePredefinedAny: Defaults["UnionType"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithUnionTypeLiteral: Defaults["UnionType"]["String"] & Defaults["UnionType"]["Literal"] = "two";
const RemoveIntersectionTypeUnionTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithUnionTypeObject: Defaults["UnionType"]["String"] & Defaults["UnionType"]["Object"] = "two";
const RemoveIntersectionTypeUnionTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithUnionTypeString: Defaults["UnionType"]["String"] & Defaults["UnionType"]["String"] = "two";
const RemoveIntersectionTypeUnionTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithUnionTypeNumber: Defaults["UnionType"]["String"] & Defaults["UnionType"]["Number"] = "two";
const RemoveIntersectionTypeUnionTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithUnionTypeBoolean: Defaults["UnionType"]["String"] & Defaults["UnionType"]["Boolean"] = "two";
const RemoveIntersectionTypeUnionTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithUnionTypeAny: Defaults["UnionType"]["String"] & Defaults["UnionType"]["Any"] = "two";
const RemoveIntersectionTypeUnionTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithIntersectionTypeLiteral: Defaults["UnionType"]["String"] & Defaults["IntersectionType"]["Literal"] = "two";
const RemoveIntersectionTypeIntersectionTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithIntersectionTypeObject: Defaults["UnionType"]["String"] & Defaults["IntersectionType"]["Object"] = "two";
const RemoveIntersectionTypeIntersectionTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithIntersectionTypeString: Defaults["UnionType"]["String"] & Defaults["IntersectionType"]["String"] = "two";
const RemoveIntersectionTypeIntersectionTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithIntersectionTypeNumber: Defaults["UnionType"]["String"] & Defaults["IntersectionType"]["Number"] = "two";
const RemoveIntersectionTypeIntersectionTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithIntersectionTypeBoolean: Defaults["UnionType"]["String"] & Defaults["IntersectionType"]["Boolean"] = "two";
const RemoveIntersectionTypeIntersectionTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithIntersectionTypeAny: Defaults["UnionType"]["String"] & Defaults["IntersectionType"]["Any"] = "two";
const RemoveIntersectionTypeIntersectionTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithTypeLiteralLiteral: Defaults["UnionType"]["String"] & Defaults["TypeLiteral"]["Literal"] = "two";
const RemoveIntersectionTypeTypeLiteralLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeLiteralObject: Defaults["UnionType"]["String"] & Defaults["TypeLiteral"]["Object"] = "two";
const RemoveIntersectionTypeTypeLiteralObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeLiteralString: Defaults["UnionType"]["String"] & Defaults["TypeLiteral"]["String"] = "two";
const RemoveIntersectionTypeTypeLiteralStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeLiteralNumber: Defaults["UnionType"]["String"] & Defaults["TypeLiteral"]["Number"] = "two";
const RemoveIntersectionTypeTypeLiteralNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeLiteralBoolean: Defaults["UnionType"]["String"] & Defaults["TypeLiteral"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeLiteralBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTypeLiteralAny: Defaults["UnionType"]["String"] & Defaults["TypeLiteral"]["Any"] = "two";
const RemoveIntersectionTypeTypeLiteralAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithTupleTypeLiteral: Defaults["UnionType"]["String"] & Defaults["TupleType"]["Literal"] = "two";
const RemoveIntersectionTypeTupleTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTupleTypeObject: Defaults["UnionType"]["String"] & Defaults["TupleType"]["Object"] = "two";
const RemoveIntersectionTypeTupleTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTupleTypeString: Defaults["UnionType"]["String"] & Defaults["TupleType"]["String"] = "two";
const RemoveIntersectionTypeTupleTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTupleTypeNumber: Defaults["UnionType"]["String"] & Defaults["TupleType"]["Number"] = "two";
const RemoveIntersectionTypeTupleTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTupleTypeBoolean: Defaults["UnionType"]["String"] & Defaults["TupleType"]["Boolean"] = "two";
const RemoveIntersectionTypeTupleTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithTupleTypeAny: Defaults["UnionType"]["String"] & Defaults["TupleType"]["Any"] = "two";
const RemoveIntersectionTypeTupleTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithArrayTypeLiteral: Defaults["UnionType"]["String"] & Defaults["ArrayType"]["Literal"] = "two";
const RemoveIntersectionTypeArrayTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithArrayTypeObject: Defaults["UnionType"]["String"] & Defaults["ArrayType"]["Object"] = "two";
const RemoveIntersectionTypeArrayTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithArrayTypeString: Defaults["UnionType"]["String"] & Defaults["ArrayType"]["String"] = "two";
const RemoveIntersectionTypeArrayTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithArrayTypeNumber: Defaults["UnionType"]["String"] & Defaults["ArrayType"]["Number"] = "two";
const RemoveIntersectionTypeArrayTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithArrayTypeBoolean: Defaults["UnionType"]["String"] & Defaults["ArrayType"]["Boolean"] = "two";
const RemoveIntersectionTypeArrayTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithArrayTypeAny: Defaults["UnionType"]["String"] & Defaults["ArrayType"]["Any"] = "two";
const RemoveIntersectionTypeArrayTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithFunctionTypeLiteral: Defaults["UnionType"]["String"] & Defaults["FunctionType"]["Literal"] = "two";
const RemoveIntersectionTypeFunctionTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithFunctionTypeObject: Defaults["UnionType"]["String"] & Defaults["FunctionType"]["Object"] = "two";
const RemoveIntersectionTypeFunctionTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithFunctionTypeString: Defaults["UnionType"]["String"] & Defaults["FunctionType"]["String"] = "two";
const RemoveIntersectionTypeFunctionTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithFunctionTypeNumber: Defaults["UnionType"]["String"] & Defaults["FunctionType"]["Number"] = "two";
const RemoveIntersectionTypeFunctionTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithFunctionTypeBoolean: Defaults["UnionType"]["String"] & Defaults["FunctionType"]["Boolean"] = "two";
const RemoveIntersectionTypeFunctionTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithFunctionTypeAny: Defaults["UnionType"]["String"] & Defaults["FunctionType"]["Any"] = "two";
const RemoveIntersectionTypeFunctionTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeStringWithConstructorTypeLiteral: Defaults["UnionType"]["String"] & Defaults["ConstructorType"]["Literal"] = "two";
const RemoveIntersectionTypeConstructorTypeLiteralFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithConstructorTypeObject: Defaults["UnionType"]["String"] & Defaults["ConstructorType"]["Object"] = "two";
const RemoveIntersectionTypeConstructorTypeObjectFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithConstructorTypeString: Defaults["UnionType"]["String"] & Defaults["ConstructorType"]["String"] = "two";
const RemoveIntersectionTypeConstructorTypeStringFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithConstructorTypeNumber: Defaults["UnionType"]["String"] & Defaults["ConstructorType"]["Number"] = "two";
const RemoveIntersectionTypeConstructorTypeNumberFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithConstructorTypeBoolean: Defaults["UnionType"]["String"] & Defaults["ConstructorType"]["Boolean"] = "two";
const RemoveIntersectionTypeConstructorTypeBooleanFromUnionTypeString: Defaults["UnionType"]["String"]= "two"
const IntersectionTypeUnionTypeStringWithConstructorTypeAny: Defaults["UnionType"]["String"] & Defaults["ConstructorType"]["Any"] = "two";
const RemoveIntersectionTypeConstructorTypeAnyFromUnionTypeString: Defaults["UnionType"]["String"]= "two"

const IntersectionTypeUnionTypeNumberWithParenthesizedTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithParenthesizedTypeObject: Defaults["UnionType"]["Number"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithParenthesizedTypeString: Defaults["UnionType"]["Number"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithParenthesizedTypeNumber: Defaults["UnionType"]["Number"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithParenthesizedTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithParenthesizedTypeAny: Defaults["UnionType"]["Number"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithTypeReferenceBuiltinLiteral: Defaults["UnionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferenceBuiltinObject: Defaults["UnionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferenceBuiltinString: Defaults["UnionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferenceBuiltinNumber: Defaults["UnionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferenceBuiltinBoolean: Defaults["UnionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferenceBuiltinAny: Defaults["UnionType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithTypeReferencePredefinedLiteral: Defaults["UnionType"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferencePredefinedObject: Defaults["UnionType"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferencePredefinedString: Defaults["UnionType"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferencePredefinedNumber: Defaults["UnionType"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferencePredefinedBoolean: Defaults["UnionType"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeReferencePredefinedAny: Defaults["UnionType"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithUnionTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithUnionTypeObject: Defaults["UnionType"]["Number"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithUnionTypeString: Defaults["UnionType"]["Number"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithUnionTypeNumber: Defaults["UnionType"]["Number"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithUnionTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithUnionTypeAny: Defaults["UnionType"]["Number"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithIntersectionTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithIntersectionTypeObject: Defaults["UnionType"]["Number"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithIntersectionTypeString: Defaults["UnionType"]["Number"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithIntersectionTypeNumber: Defaults["UnionType"]["Number"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithIntersectionTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithIntersectionTypeAny: Defaults["UnionType"]["Number"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithTypeLiteralLiteral: Defaults["UnionType"]["Number"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeLiteralObject: Defaults["UnionType"]["Number"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeLiteralString: Defaults["UnionType"]["Number"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeLiteralNumber: Defaults["UnionType"]["Number"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeLiteralBoolean: Defaults["UnionType"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTypeLiteralAny: Defaults["UnionType"]["Number"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithTupleTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTupleTypeObject: Defaults["UnionType"]["Number"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTupleTypeString: Defaults["UnionType"]["Number"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTupleTypeNumber: Defaults["UnionType"]["Number"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTupleTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithTupleTypeAny: Defaults["UnionType"]["Number"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithArrayTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithArrayTypeObject: Defaults["UnionType"]["Number"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithArrayTypeString: Defaults["UnionType"]["Number"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithArrayTypeNumber: Defaults["UnionType"]["Number"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithArrayTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithArrayTypeAny: Defaults["UnionType"]["Number"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithFunctionTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithFunctionTypeObject: Defaults["UnionType"]["Number"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithFunctionTypeString: Defaults["UnionType"]["Number"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithFunctionTypeNumber: Defaults["UnionType"]["Number"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithFunctionTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithFunctionTypeAny: Defaults["UnionType"]["Number"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeNumberWithConstructorTypeLiteral: Defaults["UnionType"]["Number"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithConstructorTypeObject: Defaults["UnionType"]["Number"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithConstructorTypeString: Defaults["UnionType"]["Number"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithConstructorTypeNumber: Defaults["UnionType"]["Number"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithConstructorTypeBoolean: Defaults["UnionType"]["Number"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2
const IntersectionTypeUnionTypeNumberWithConstructorTypeAny: Defaults["UnionType"]["Number"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromUnionTypeNumber: Defaults["UnionType"]["Number"]= 2

const IntersectionTypeUnionTypeBooleanWithParenthesizedTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = true;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithParenthesizedTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = true;
const RemoveIntersectionTypeParenthesizedTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithParenthesizedTypeString: Defaults["UnionType"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = true;
const RemoveIntersectionTypeParenthesizedTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithParenthesizedTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = true;
const RemoveIntersectionTypeParenthesizedTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithParenthesizedTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = true;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithParenthesizedTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = true;
const RemoveIntersectionTypeParenthesizedTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithTypeReferenceBuiltinLiteral: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferenceBuiltinObject: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferenceBuiltinString: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferenceBuiltinNumber: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferenceBuiltinBoolean: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferenceBuiltinAny: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithTypeReferencePredefinedLiteral: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferencePredefinedObject: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferencePredefinedString: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferencePredefinedNumber: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferencePredefinedBoolean: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeReferencePredefinedAny: Defaults["UnionType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithUnionTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["UnionType"]["Literal"] = true;
const RemoveIntersectionTypeUnionTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithUnionTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["UnionType"]["Object"] = true;
const RemoveIntersectionTypeUnionTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithUnionTypeString: Defaults["UnionType"]["Boolean"] & Defaults["UnionType"]["String"] = true;
const RemoveIntersectionTypeUnionTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithUnionTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["UnionType"]["Number"] = true;
const RemoveIntersectionTypeUnionTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithUnionTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["UnionType"]["Boolean"] = true;
const RemoveIntersectionTypeUnionTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithUnionTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["UnionType"]["Any"] = true;
const RemoveIntersectionTypeUnionTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithIntersectionTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = true;
const RemoveIntersectionTypeIntersectionTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithIntersectionTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["IntersectionType"]["Object"] = true;
const RemoveIntersectionTypeIntersectionTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithIntersectionTypeString: Defaults["UnionType"]["Boolean"] & Defaults["IntersectionType"]["String"] = true;
const RemoveIntersectionTypeIntersectionTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithIntersectionTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["IntersectionType"]["Number"] = true;
const RemoveIntersectionTypeIntersectionTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithIntersectionTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = true;
const RemoveIntersectionTypeIntersectionTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithIntersectionTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["IntersectionType"]["Any"] = true;
const RemoveIntersectionTypeIntersectionTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithTypeLiteralLiteral: Defaults["UnionType"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = true;
const RemoveIntersectionTypeTypeLiteralLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeLiteralObject: Defaults["UnionType"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = true;
const RemoveIntersectionTypeTypeLiteralObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeLiteralString: Defaults["UnionType"]["Boolean"] & Defaults["TypeLiteral"]["String"] = true;
const RemoveIntersectionTypeTypeLiteralStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeLiteralNumber: Defaults["UnionType"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = true;
const RemoveIntersectionTypeTypeLiteralNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeLiteralBoolean: Defaults["UnionType"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = true;
const RemoveIntersectionTypeTypeLiteralBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTypeLiteralAny: Defaults["UnionType"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = true;
const RemoveIntersectionTypeTypeLiteralAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithTupleTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["TupleType"]["Literal"] = true;
const RemoveIntersectionTypeTupleTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTupleTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["TupleType"]["Object"] = true;
const RemoveIntersectionTypeTupleTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTupleTypeString: Defaults["UnionType"]["Boolean"] & Defaults["TupleType"]["String"] = true;
const RemoveIntersectionTypeTupleTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTupleTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["TupleType"]["Number"] = true;
const RemoveIntersectionTypeTupleTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTupleTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["TupleType"]["Boolean"] = true;
const RemoveIntersectionTypeTupleTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithTupleTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["TupleType"]["Any"] = true;
const RemoveIntersectionTypeTupleTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithArrayTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["ArrayType"]["Literal"] = true;
const RemoveIntersectionTypeArrayTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithArrayTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["ArrayType"]["Object"] = true;
const RemoveIntersectionTypeArrayTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithArrayTypeString: Defaults["UnionType"]["Boolean"] & Defaults["ArrayType"]["String"] = true;
const RemoveIntersectionTypeArrayTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithArrayTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["ArrayType"]["Number"] = true;
const RemoveIntersectionTypeArrayTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithArrayTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = true;
const RemoveIntersectionTypeArrayTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithArrayTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["ArrayType"]["Any"] = true;
const RemoveIntersectionTypeArrayTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithFunctionTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["FunctionType"]["Literal"] = true;
const RemoveIntersectionTypeFunctionTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithFunctionTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["FunctionType"]["Object"] = true;
const RemoveIntersectionTypeFunctionTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithFunctionTypeString: Defaults["UnionType"]["Boolean"] & Defaults["FunctionType"]["String"] = true;
const RemoveIntersectionTypeFunctionTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithFunctionTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["FunctionType"]["Number"] = true;
const RemoveIntersectionTypeFunctionTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithFunctionTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = true;
const RemoveIntersectionTypeFunctionTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithFunctionTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["FunctionType"]["Any"] = true;
const RemoveIntersectionTypeFunctionTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeBooleanWithConstructorTypeLiteral: Defaults["UnionType"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = true;
const RemoveIntersectionTypeConstructorTypeLiteralFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithConstructorTypeObject: Defaults["UnionType"]["Boolean"] & Defaults["ConstructorType"]["Object"] = true;
const RemoveIntersectionTypeConstructorTypeObjectFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithConstructorTypeString: Defaults["UnionType"]["Boolean"] & Defaults["ConstructorType"]["String"] = true;
const RemoveIntersectionTypeConstructorTypeStringFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithConstructorTypeNumber: Defaults["UnionType"]["Boolean"] & Defaults["ConstructorType"]["Number"] = true;
const RemoveIntersectionTypeConstructorTypeNumberFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithConstructorTypeBoolean: Defaults["UnionType"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = true;
const RemoveIntersectionTypeConstructorTypeBooleanFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true
const IntersectionTypeUnionTypeBooleanWithConstructorTypeAny: Defaults["UnionType"]["Boolean"] & Defaults["ConstructorType"]["Any"] = true;
const RemoveIntersectionTypeConstructorTypeAnyFromUnionTypeBoolean: Defaults["UnionType"]["Boolean"]= true

const IntersectionTypeUnionTypeAnyWithParenthesizedTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithParenthesizedTypeObject: Defaults["UnionType"]["Any"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithParenthesizedTypeString: Defaults["UnionType"]["Any"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithParenthesizedTypeNumber: Defaults["UnionType"]["Any"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithParenthesizedTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithParenthesizedTypeAny: Defaults["UnionType"]["Any"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithTypeReferenceBuiltinLiteral: Defaults["UnionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferenceBuiltinObject: Defaults["UnionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferenceBuiltinString: Defaults["UnionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferenceBuiltinNumber: Defaults["UnionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferenceBuiltinBoolean: Defaults["UnionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferenceBuiltinAny: Defaults["UnionType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithTypeReferencePredefinedLiteral: Defaults["UnionType"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferencePredefinedObject: Defaults["UnionType"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferencePredefinedString: Defaults["UnionType"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferencePredefinedNumber: Defaults["UnionType"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferencePredefinedBoolean: Defaults["UnionType"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeReferencePredefinedAny: Defaults["UnionType"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithUnionTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithUnionTypeObject: Defaults["UnionType"]["Any"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithUnionTypeString: Defaults["UnionType"]["Any"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithUnionTypeNumber: Defaults["UnionType"]["Any"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithUnionTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithUnionTypeAny: Defaults["UnionType"]["Any"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithIntersectionTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithIntersectionTypeObject: Defaults["UnionType"]["Any"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithIntersectionTypeString: Defaults["UnionType"]["Any"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithIntersectionTypeNumber: Defaults["UnionType"]["Any"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithIntersectionTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithIntersectionTypeAny: Defaults["UnionType"]["Any"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithTypeLiteralLiteral: Defaults["UnionType"]["Any"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeLiteralObject: Defaults["UnionType"]["Any"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeLiteralString: Defaults["UnionType"]["Any"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeLiteralNumber: Defaults["UnionType"]["Any"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeLiteralBoolean: Defaults["UnionType"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTypeLiteralAny: Defaults["UnionType"]["Any"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithTupleTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTupleTypeObject: Defaults["UnionType"]["Any"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTupleTypeString: Defaults["UnionType"]["Any"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTupleTypeNumber: Defaults["UnionType"]["Any"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTupleTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithTupleTypeAny: Defaults["UnionType"]["Any"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithArrayTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithArrayTypeObject: Defaults["UnionType"]["Any"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithArrayTypeString: Defaults["UnionType"]["Any"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithArrayTypeNumber: Defaults["UnionType"]["Any"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithArrayTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithArrayTypeAny: Defaults["UnionType"]["Any"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithFunctionTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithFunctionTypeObject: Defaults["UnionType"]["Any"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithFunctionTypeString: Defaults["UnionType"]["Any"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithFunctionTypeNumber: Defaults["UnionType"]["Any"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithFunctionTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithFunctionTypeAny: Defaults["UnionType"]["Any"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

const IntersectionTypeUnionTypeAnyWithConstructorTypeLiteral: Defaults["UnionType"]["Any"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithConstructorTypeObject: Defaults["UnionType"]["Any"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithConstructorTypeString: Defaults["UnionType"]["Any"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithConstructorTypeNumber: Defaults["UnionType"]["Any"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithConstructorTypeBoolean: Defaults["UnionType"]["Any"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2
const IntersectionTypeUnionTypeAnyWithConstructorTypeAny: Defaults["UnionType"]["Any"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromUnionTypeAny: Defaults["UnionType"]["Any"]= 2

