import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - TypeLiteral
const IntersectionTypeTypeLiteralLiteralWithParenthesizedTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithParenthesizedTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = {"key":1};
const RemoveIntersectionTypeParenthesizedTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithParenthesizedTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["ParenthesizedType"]["String"] = {"key":1};
const RemoveIntersectionTypeParenthesizedTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithParenthesizedTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = {"key":1};
const RemoveIntersectionTypeParenthesizedTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithParenthesizedTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithParenthesizedTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = {"key":1};
const RemoveIntersectionTypeParenthesizedTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithTypeReferenceBuiltinLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {"key":1};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferenceBuiltinObject: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = {"key":1};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferenceBuiltinString: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = {"key":1};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferenceBuiltinNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = {"key":1};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferenceBuiltinBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferenceBuiltinAny: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = {"key":1};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithTypeReferencePredefinedLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = {"key":1};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferencePredefinedObject: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = {"key":1};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferencePredefinedString: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = {"key":1};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferencePredefinedNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = {"key":1};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferencePredefinedBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeReferencePredefinedAny: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = {"key":1};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithUnionTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["UnionType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeUnionTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithUnionTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["UnionType"]["Object"] = {"key":1};
const RemoveIntersectionTypeUnionTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithUnionTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["UnionType"]["String"] = {"key":1};
const RemoveIntersectionTypeUnionTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithUnionTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["UnionType"]["Number"] = {"key":1};
const RemoveIntersectionTypeUnionTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithUnionTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["UnionType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeUnionTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithUnionTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["UnionType"]["Any"] = {"key":1};
const RemoveIntersectionTypeUnionTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithIntersectionTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["IntersectionType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeIntersectionTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithIntersectionTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["IntersectionType"]["Object"] = {"key":1};
const RemoveIntersectionTypeIntersectionTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithIntersectionTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["IntersectionType"]["String"] = {"key":1};
const RemoveIntersectionTypeIntersectionTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithIntersectionTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["IntersectionType"]["Number"] = {"key":1};
const RemoveIntersectionTypeIntersectionTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithIntersectionTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeIntersectionTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithIntersectionTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["IntersectionType"]["Any"] = {"key":1};
const RemoveIntersectionTypeIntersectionTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = {"key":1};
const RemoveIntersectionTypeTypeLiteralLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeLiteralObject: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeLiteral"]["Object"] = {"key":1};
const RemoveIntersectionTypeTypeLiteralObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeLiteralString: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeLiteral"]["String"] = {"key":1};
const RemoveIntersectionTypeTypeLiteralStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeLiteralNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeLiteral"]["Number"] = {"key":1};
const RemoveIntersectionTypeTypeLiteralNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeLiteralBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeTypeLiteralBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTypeLiteralAny: Defaults["TypeLiteral"]["Literal"] & Defaults["TypeLiteral"]["Any"] = {"key":1};
const RemoveIntersectionTypeTypeLiteralAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithTupleTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["TupleType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeTupleTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTupleTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["TupleType"]["Object"] = {"key":1};
const RemoveIntersectionTypeTupleTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTupleTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["TupleType"]["String"] = {"key":1};
const RemoveIntersectionTypeTupleTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTupleTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["TupleType"]["Number"] = {"key":1};
const RemoveIntersectionTypeTupleTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTupleTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["TupleType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeTupleTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithTupleTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["TupleType"]["Any"] = {"key":1};
const RemoveIntersectionTypeTupleTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithArrayTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["ArrayType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeArrayTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithArrayTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["ArrayType"]["Object"] = {"key":1};
const RemoveIntersectionTypeArrayTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithArrayTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["ArrayType"]["String"] = {"key":1};
const RemoveIntersectionTypeArrayTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithArrayTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["ArrayType"]["Number"] = {"key":1};
const RemoveIntersectionTypeArrayTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithArrayTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["ArrayType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeArrayTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithArrayTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["ArrayType"]["Any"] = {"key":1};
const RemoveIntersectionTypeArrayTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithFunctionTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["FunctionType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeFunctionTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithFunctionTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["FunctionType"]["Object"] = {"key":1};
const RemoveIntersectionTypeFunctionTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithFunctionTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["FunctionType"]["String"] = {"key":1};
const RemoveIntersectionTypeFunctionTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithFunctionTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["FunctionType"]["Number"] = {"key":1};
const RemoveIntersectionTypeFunctionTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithFunctionTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["FunctionType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeFunctionTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithFunctionTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["FunctionType"]["Any"] = {"key":1};
const RemoveIntersectionTypeFunctionTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralLiteralWithConstructorTypeLiteral: Defaults["TypeLiteral"]["Literal"] & Defaults["ConstructorType"]["Literal"] = {"key":1};
const RemoveIntersectionTypeConstructorTypeLiteralFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithConstructorTypeObject: Defaults["TypeLiteral"]["Literal"] & Defaults["ConstructorType"]["Object"] = {"key":1};
const RemoveIntersectionTypeConstructorTypeObjectFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithConstructorTypeString: Defaults["TypeLiteral"]["Literal"] & Defaults["ConstructorType"]["String"] = {"key":1};
const RemoveIntersectionTypeConstructorTypeStringFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithConstructorTypeNumber: Defaults["TypeLiteral"]["Literal"] & Defaults["ConstructorType"]["Number"] = {"key":1};
const RemoveIntersectionTypeConstructorTypeNumberFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithConstructorTypeBoolean: Defaults["TypeLiteral"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = {"key":1};
const RemoveIntersectionTypeConstructorTypeBooleanFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}
const IntersectionTypeTypeLiteralLiteralWithConstructorTypeAny: Defaults["TypeLiteral"]["Literal"] & Defaults["ConstructorType"]["Any"] = {"key":1};
const RemoveIntersectionTypeConstructorTypeAnyFromTypeLiteralLiteral: Defaults["TypeLiteral"]["Literal"]= {"key":1}

const IntersectionTypeTypeLiteralObjectWithParenthesizedTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithParenthesizedTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["ParenthesizedType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeParenthesizedTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithParenthesizedTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["ParenthesizedType"]["String"] = {"key":{}};
const RemoveIntersectionTypeParenthesizedTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithParenthesizedTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["ParenthesizedType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeParenthesizedTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithParenthesizedTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithParenthesizedTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["ParenthesizedType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeParenthesizedTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithTypeReferenceBuiltinLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferenceBuiltinObject: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = {"key":{}};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferenceBuiltinString: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = {"key":{}};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferenceBuiltinNumber: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = {"key":{}};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferenceBuiltinBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferenceBuiltinAny: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = {"key":{}};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithTypeReferencePredefinedLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferencePredefinedObject: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = {"key":{}};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferencePredefinedString: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = {"key":{}};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferencePredefinedNumber: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = {"key":{}};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferencePredefinedBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeReferencePredefinedAny: Defaults["TypeLiteral"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = {"key":{}};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithUnionTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["UnionType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeUnionTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithUnionTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["UnionType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeUnionTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithUnionTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["UnionType"]["String"] = {"key":{}};
const RemoveIntersectionTypeUnionTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithUnionTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["UnionType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeUnionTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithUnionTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["UnionType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeUnionTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithUnionTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["UnionType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeUnionTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithIntersectionTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["IntersectionType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeIntersectionTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithIntersectionTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["IntersectionType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeIntersectionTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithIntersectionTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["IntersectionType"]["String"] = {"key":{}};
const RemoveIntersectionTypeIntersectionTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithIntersectionTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["IntersectionType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeIntersectionTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithIntersectionTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["IntersectionType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeIntersectionTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithIntersectionTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["IntersectionType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeIntersectionTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithTypeLiteralLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["TypeLiteral"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeTypeLiteralLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeLiteralObject: Defaults["TypeLiteral"]["Object"] & Defaults["TypeLiteral"]["Object"] = {"key":{}};
const RemoveIntersectionTypeTypeLiteralObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeLiteralString: Defaults["TypeLiteral"]["Object"] & Defaults["TypeLiteral"]["String"] = {"key":{}};
const RemoveIntersectionTypeTypeLiteralStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeLiteralNumber: Defaults["TypeLiteral"]["Object"] & Defaults["TypeLiteral"]["Number"] = {"key":{}};
const RemoveIntersectionTypeTypeLiteralNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeLiteralBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeTypeLiteralBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTypeLiteralAny: Defaults["TypeLiteral"]["Object"] & Defaults["TypeLiteral"]["Any"] = {"key":{}};
const RemoveIntersectionTypeTypeLiteralAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithTupleTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["TupleType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeTupleTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTupleTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["TupleType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeTupleTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTupleTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["TupleType"]["String"] = {"key":{}};
const RemoveIntersectionTypeTupleTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTupleTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["TupleType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeTupleTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTupleTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["TupleType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeTupleTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithTupleTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["TupleType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeTupleTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithArrayTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["ArrayType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeArrayTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithArrayTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["ArrayType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeArrayTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithArrayTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["ArrayType"]["String"] = {"key":{}};
const RemoveIntersectionTypeArrayTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithArrayTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["ArrayType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeArrayTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithArrayTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["ArrayType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeArrayTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithArrayTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["ArrayType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeArrayTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithFunctionTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["FunctionType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeFunctionTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithFunctionTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["FunctionType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeFunctionTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithFunctionTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["FunctionType"]["String"] = {"key":{}};
const RemoveIntersectionTypeFunctionTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithFunctionTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["FunctionType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeFunctionTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithFunctionTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["FunctionType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeFunctionTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithFunctionTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["FunctionType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeFunctionTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralObjectWithConstructorTypeLiteral: Defaults["TypeLiteral"]["Object"] & Defaults["ConstructorType"]["Literal"] = {"key":{}};
const RemoveIntersectionTypeConstructorTypeLiteralFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithConstructorTypeObject: Defaults["TypeLiteral"]["Object"] & Defaults["ConstructorType"]["Object"] = {"key":{}};
const RemoveIntersectionTypeConstructorTypeObjectFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithConstructorTypeString: Defaults["TypeLiteral"]["Object"] & Defaults["ConstructorType"]["String"] = {"key":{}};
const RemoveIntersectionTypeConstructorTypeStringFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithConstructorTypeNumber: Defaults["TypeLiteral"]["Object"] & Defaults["ConstructorType"]["Number"] = {"key":{}};
const RemoveIntersectionTypeConstructorTypeNumberFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithConstructorTypeBoolean: Defaults["TypeLiteral"]["Object"] & Defaults["ConstructorType"]["Boolean"] = {"key":{}};
const RemoveIntersectionTypeConstructorTypeBooleanFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}
const IntersectionTypeTypeLiteralObjectWithConstructorTypeAny: Defaults["TypeLiteral"]["Object"] & Defaults["ConstructorType"]["Any"] = {"key":{}};
const RemoveIntersectionTypeConstructorTypeAnyFromTypeLiteralObject: Defaults["TypeLiteral"]["Object"]= {"key":{}}

const IntersectionTypeTypeLiteralStringWithParenthesizedTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["ParenthesizedType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithParenthesizedTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["ParenthesizedType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeParenthesizedTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithParenthesizedTypeString: Defaults["TypeLiteral"]["String"] & Defaults["ParenthesizedType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeParenthesizedTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithParenthesizedTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["ParenthesizedType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeParenthesizedTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithParenthesizedTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithParenthesizedTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["ParenthesizedType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeParenthesizedTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithTypeReferenceBuiltinLiteral: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferenceBuiltinObject: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferenceBuiltinString: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferenceBuiltinNumber: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferenceBuiltinBoolean: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferenceBuiltinAny: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithTypeReferencePredefinedLiteral: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferencePredefinedObject: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferencePredefinedString: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferencePredefined"]["String"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferencePredefinedNumber: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferencePredefinedBoolean: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeReferencePredefinedAny: Defaults["TypeLiteral"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithUnionTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["UnionType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeUnionTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithUnionTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["UnionType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeUnionTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithUnionTypeString: Defaults["TypeLiteral"]["String"] & Defaults["UnionType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeUnionTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithUnionTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["UnionType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeUnionTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithUnionTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["UnionType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeUnionTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithUnionTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["UnionType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeUnionTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithIntersectionTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["IntersectionType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeIntersectionTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithIntersectionTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["IntersectionType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeIntersectionTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithIntersectionTypeString: Defaults["TypeLiteral"]["String"] & Defaults["IntersectionType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeIntersectionTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithIntersectionTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["IntersectionType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeIntersectionTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithIntersectionTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["IntersectionType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeIntersectionTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithIntersectionTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["IntersectionType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeIntersectionTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithTypeLiteralLiteral: Defaults["TypeLiteral"]["String"] & Defaults["TypeLiteral"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeTypeLiteralLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeLiteralObject: Defaults["TypeLiteral"]["String"] & Defaults["TypeLiteral"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeTypeLiteralObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeLiteralString: Defaults["TypeLiteral"]["String"] & Defaults["TypeLiteral"]["String"] = {"key":"two"};
const RemoveIntersectionTypeTypeLiteralStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeLiteralNumber: Defaults["TypeLiteral"]["String"] & Defaults["TypeLiteral"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeTypeLiteralNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeLiteralBoolean: Defaults["TypeLiteral"]["String"] & Defaults["TypeLiteral"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeTypeLiteralBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTypeLiteralAny: Defaults["TypeLiteral"]["String"] & Defaults["TypeLiteral"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeTypeLiteralAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithTupleTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["TupleType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeTupleTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTupleTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["TupleType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeTupleTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTupleTypeString: Defaults["TypeLiteral"]["String"] & Defaults["TupleType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeTupleTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTupleTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["TupleType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeTupleTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTupleTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["TupleType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeTupleTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithTupleTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["TupleType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeTupleTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithArrayTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["ArrayType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeArrayTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithArrayTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["ArrayType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeArrayTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithArrayTypeString: Defaults["TypeLiteral"]["String"] & Defaults["ArrayType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeArrayTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithArrayTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["ArrayType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeArrayTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithArrayTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["ArrayType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeArrayTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithArrayTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["ArrayType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeArrayTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithFunctionTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["FunctionType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeFunctionTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithFunctionTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["FunctionType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeFunctionTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithFunctionTypeString: Defaults["TypeLiteral"]["String"] & Defaults["FunctionType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeFunctionTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithFunctionTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["FunctionType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeFunctionTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithFunctionTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["FunctionType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeFunctionTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithFunctionTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["FunctionType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeFunctionTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralStringWithConstructorTypeLiteral: Defaults["TypeLiteral"]["String"] & Defaults["ConstructorType"]["Literal"] = {"key":"two"};
const RemoveIntersectionTypeConstructorTypeLiteralFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithConstructorTypeObject: Defaults["TypeLiteral"]["String"] & Defaults["ConstructorType"]["Object"] = {"key":"two"};
const RemoveIntersectionTypeConstructorTypeObjectFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithConstructorTypeString: Defaults["TypeLiteral"]["String"] & Defaults["ConstructorType"]["String"] = {"key":"two"};
const RemoveIntersectionTypeConstructorTypeStringFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithConstructorTypeNumber: Defaults["TypeLiteral"]["String"] & Defaults["ConstructorType"]["Number"] = {"key":"two"};
const RemoveIntersectionTypeConstructorTypeNumberFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithConstructorTypeBoolean: Defaults["TypeLiteral"]["String"] & Defaults["ConstructorType"]["Boolean"] = {"key":"two"};
const RemoveIntersectionTypeConstructorTypeBooleanFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}
const IntersectionTypeTypeLiteralStringWithConstructorTypeAny: Defaults["TypeLiteral"]["String"] & Defaults["ConstructorType"]["Any"] = {"key":"two"};
const RemoveIntersectionTypeConstructorTypeAnyFromTypeLiteralString: Defaults["TypeLiteral"]["String"]= {"key":"two"}

const IntersectionTypeTypeLiteralNumberWithParenthesizedTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithParenthesizedTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["ParenthesizedType"]["Object"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithParenthesizedTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["ParenthesizedType"]["String"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithParenthesizedTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["ParenthesizedType"]["Number"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithParenthesizedTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithParenthesizedTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["ParenthesizedType"]["Any"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithTypeReferenceBuiltinLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferenceBuiltinObject: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferenceBuiltinString: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferenceBuiltinNumber: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferenceBuiltinBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferenceBuiltinAny: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithTypeReferencePredefinedLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferencePredefinedObject: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferencePredefinedString: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferencePredefinedNumber: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferencePredefinedBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeReferencePredefinedAny: Defaults["TypeLiteral"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithUnionTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["UnionType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeUnionTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithUnionTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["UnionType"]["Object"] = {"key":2};
const RemoveIntersectionTypeUnionTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithUnionTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["UnionType"]["String"] = {"key":2};
const RemoveIntersectionTypeUnionTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithUnionTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["UnionType"]["Number"] = {"key":2};
const RemoveIntersectionTypeUnionTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithUnionTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["UnionType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeUnionTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithUnionTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["UnionType"]["Any"] = {"key":2};
const RemoveIntersectionTypeUnionTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithIntersectionTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["IntersectionType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithIntersectionTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["IntersectionType"]["Object"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithIntersectionTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["IntersectionType"]["String"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithIntersectionTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["IntersectionType"]["Number"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithIntersectionTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["IntersectionType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithIntersectionTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["IntersectionType"]["Any"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithTypeLiteralLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["TypeLiteral"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeLiteralObject: Defaults["TypeLiteral"]["Number"] & Defaults["TypeLiteral"]["Object"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeLiteralString: Defaults["TypeLiteral"]["Number"] & Defaults["TypeLiteral"]["String"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeLiteralNumber: Defaults["TypeLiteral"]["Number"] & Defaults["TypeLiteral"]["Number"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeLiteralBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTypeLiteralAny: Defaults["TypeLiteral"]["Number"] & Defaults["TypeLiteral"]["Any"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithTupleTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["TupleType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTupleTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTupleTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["TupleType"]["Object"] = {"key":2};
const RemoveIntersectionTypeTupleTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTupleTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["TupleType"]["String"] = {"key":2};
const RemoveIntersectionTypeTupleTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTupleTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["TupleType"]["Number"] = {"key":2};
const RemoveIntersectionTypeTupleTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTupleTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["TupleType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTupleTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithTupleTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["TupleType"]["Any"] = {"key":2};
const RemoveIntersectionTypeTupleTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithArrayTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["ArrayType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeArrayTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithArrayTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["ArrayType"]["Object"] = {"key":2};
const RemoveIntersectionTypeArrayTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithArrayTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["ArrayType"]["String"] = {"key":2};
const RemoveIntersectionTypeArrayTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithArrayTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["ArrayType"]["Number"] = {"key":2};
const RemoveIntersectionTypeArrayTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithArrayTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["ArrayType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeArrayTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithArrayTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["ArrayType"]["Any"] = {"key":2};
const RemoveIntersectionTypeArrayTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithFunctionTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["FunctionType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithFunctionTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["FunctionType"]["Object"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithFunctionTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["FunctionType"]["String"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithFunctionTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["FunctionType"]["Number"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithFunctionTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["FunctionType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithFunctionTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["FunctionType"]["Any"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralNumberWithConstructorTypeLiteral: Defaults["TypeLiteral"]["Number"] & Defaults["ConstructorType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeLiteralFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithConstructorTypeObject: Defaults["TypeLiteral"]["Number"] & Defaults["ConstructorType"]["Object"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeObjectFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithConstructorTypeString: Defaults["TypeLiteral"]["Number"] & Defaults["ConstructorType"]["String"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeStringFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithConstructorTypeNumber: Defaults["TypeLiteral"]["Number"] & Defaults["ConstructorType"]["Number"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeNumberFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithConstructorTypeBoolean: Defaults["TypeLiteral"]["Number"] & Defaults["ConstructorType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeBooleanFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}
const IntersectionTypeTypeLiteralNumberWithConstructorTypeAny: Defaults["TypeLiteral"]["Number"] & Defaults["ConstructorType"]["Any"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeAnyFromTypeLiteralNumber: Defaults["TypeLiteral"]["Number"]= {"key":2}

const IntersectionTypeTypeLiteralBooleanWithParenthesizedTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithParenthesizedTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = {"key":true};
const RemoveIntersectionTypeParenthesizedTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithParenthesizedTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = {"key":true};
const RemoveIntersectionTypeParenthesizedTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithParenthesizedTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = {"key":true};
const RemoveIntersectionTypeParenthesizedTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithParenthesizedTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithParenthesizedTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = {"key":true};
const RemoveIntersectionTypeParenthesizedTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithTypeReferenceBuiltinLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {"key":true};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferenceBuiltinObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = {"key":true};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferenceBuiltinString: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = {"key":true};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferenceBuiltinNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = {"key":true};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferenceBuiltinBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferenceBuiltinAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = {"key":true};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithTypeReferencePredefinedLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = {"key":true};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferencePredefinedObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = {"key":true};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferencePredefinedString: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = {"key":true};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferencePredefinedNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = {"key":true};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferencePredefinedBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeReferencePredefinedAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = {"key":true};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithUnionTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["UnionType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeUnionTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithUnionTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["UnionType"]["Object"] = {"key":true};
const RemoveIntersectionTypeUnionTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithUnionTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["UnionType"]["String"] = {"key":true};
const RemoveIntersectionTypeUnionTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithUnionTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["UnionType"]["Number"] = {"key":true};
const RemoveIntersectionTypeUnionTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithUnionTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["UnionType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeUnionTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithUnionTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["UnionType"]["Any"] = {"key":true};
const RemoveIntersectionTypeUnionTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithIntersectionTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeIntersectionTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithIntersectionTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["IntersectionType"]["Object"] = {"key":true};
const RemoveIntersectionTypeIntersectionTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithIntersectionTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["IntersectionType"]["String"] = {"key":true};
const RemoveIntersectionTypeIntersectionTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithIntersectionTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["IntersectionType"]["Number"] = {"key":true};
const RemoveIntersectionTypeIntersectionTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithIntersectionTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeIntersectionTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithIntersectionTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["IntersectionType"]["Any"] = {"key":true};
const RemoveIntersectionTypeIntersectionTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithTypeLiteralLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = {"key":true};
const RemoveIntersectionTypeTypeLiteralLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeLiteralObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = {"key":true};
const RemoveIntersectionTypeTypeLiteralObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeLiteralString: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeLiteral"]["String"] = {"key":true};
const RemoveIntersectionTypeTypeLiteralStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeLiteralNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = {"key":true};
const RemoveIntersectionTypeTypeLiteralNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeTypeLiteralBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTypeLiteralAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = {"key":true};
const RemoveIntersectionTypeTypeLiteralAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithTupleTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["TupleType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeTupleTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTupleTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["TupleType"]["Object"] = {"key":true};
const RemoveIntersectionTypeTupleTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTupleTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["TupleType"]["String"] = {"key":true};
const RemoveIntersectionTypeTupleTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTupleTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["TupleType"]["Number"] = {"key":true};
const RemoveIntersectionTypeTupleTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTupleTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["TupleType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeTupleTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithTupleTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["TupleType"]["Any"] = {"key":true};
const RemoveIntersectionTypeTupleTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithArrayTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["ArrayType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeArrayTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithArrayTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["ArrayType"]["Object"] = {"key":true};
const RemoveIntersectionTypeArrayTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithArrayTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["ArrayType"]["String"] = {"key":true};
const RemoveIntersectionTypeArrayTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithArrayTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["ArrayType"]["Number"] = {"key":true};
const RemoveIntersectionTypeArrayTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithArrayTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeArrayTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithArrayTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["ArrayType"]["Any"] = {"key":true};
const RemoveIntersectionTypeArrayTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithFunctionTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["FunctionType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeFunctionTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithFunctionTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["FunctionType"]["Object"] = {"key":true};
const RemoveIntersectionTypeFunctionTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithFunctionTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["FunctionType"]["String"] = {"key":true};
const RemoveIntersectionTypeFunctionTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithFunctionTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["FunctionType"]["Number"] = {"key":true};
const RemoveIntersectionTypeFunctionTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithFunctionTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeFunctionTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithFunctionTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["FunctionType"]["Any"] = {"key":true};
const RemoveIntersectionTypeFunctionTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralBooleanWithConstructorTypeLiteral: Defaults["TypeLiteral"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = {"key":true};
const RemoveIntersectionTypeConstructorTypeLiteralFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithConstructorTypeObject: Defaults["TypeLiteral"]["Boolean"] & Defaults["ConstructorType"]["Object"] = {"key":true};
const RemoveIntersectionTypeConstructorTypeObjectFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithConstructorTypeString: Defaults["TypeLiteral"]["Boolean"] & Defaults["ConstructorType"]["String"] = {"key":true};
const RemoveIntersectionTypeConstructorTypeStringFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithConstructorTypeNumber: Defaults["TypeLiteral"]["Boolean"] & Defaults["ConstructorType"]["Number"] = {"key":true};
const RemoveIntersectionTypeConstructorTypeNumberFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithConstructorTypeBoolean: Defaults["TypeLiteral"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = {"key":true};
const RemoveIntersectionTypeConstructorTypeBooleanFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}
const IntersectionTypeTypeLiteralBooleanWithConstructorTypeAny: Defaults["TypeLiteral"]["Boolean"] & Defaults["ConstructorType"]["Any"] = {"key":true};
const RemoveIntersectionTypeConstructorTypeAnyFromTypeLiteralBoolean: Defaults["TypeLiteral"]["Boolean"]= {"key":true}

const IntersectionTypeTypeLiteralAnyWithParenthesizedTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithParenthesizedTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["ParenthesizedType"]["Object"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithParenthesizedTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["ParenthesizedType"]["String"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithParenthesizedTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["ParenthesizedType"]["Number"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithParenthesizedTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithParenthesizedTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["ParenthesizedType"]["Any"] = {"key":2};
const RemoveIntersectionTypeParenthesizedTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithTypeReferenceBuiltinLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferenceBuiltinObject: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferenceBuiltinString: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferenceBuiltinNumber: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferenceBuiltinBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferenceBuiltinAny: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = {"key":2};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithTypeReferencePredefinedLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferencePredefinedObject: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferencePredefinedString: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferencePredefinedNumber: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferencePredefinedBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeReferencePredefinedAny: Defaults["TypeLiteral"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = {"key":2};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithUnionTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["UnionType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeUnionTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithUnionTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["UnionType"]["Object"] = {"key":2};
const RemoveIntersectionTypeUnionTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithUnionTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["UnionType"]["String"] = {"key":2};
const RemoveIntersectionTypeUnionTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithUnionTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["UnionType"]["Number"] = {"key":2};
const RemoveIntersectionTypeUnionTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithUnionTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["UnionType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeUnionTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithUnionTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["UnionType"]["Any"] = {"key":2};
const RemoveIntersectionTypeUnionTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithIntersectionTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["IntersectionType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithIntersectionTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["IntersectionType"]["Object"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithIntersectionTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["IntersectionType"]["String"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithIntersectionTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["IntersectionType"]["Number"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithIntersectionTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["IntersectionType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithIntersectionTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["IntersectionType"]["Any"] = {"key":2};
const RemoveIntersectionTypeIntersectionTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithTypeLiteralLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["TypeLiteral"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeLiteralObject: Defaults["TypeLiteral"]["Any"] & Defaults["TypeLiteral"]["Object"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeLiteralString: Defaults["TypeLiteral"]["Any"] & Defaults["TypeLiteral"]["String"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeLiteralNumber: Defaults["TypeLiteral"]["Any"] & Defaults["TypeLiteral"]["Number"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeLiteralBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTypeLiteralAny: Defaults["TypeLiteral"]["Any"] & Defaults["TypeLiteral"]["Any"] = {"key":2};
const RemoveIntersectionTypeTypeLiteralAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithTupleTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["TupleType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeTupleTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTupleTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["TupleType"]["Object"] = {"key":2};
const RemoveIntersectionTypeTupleTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTupleTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["TupleType"]["String"] = {"key":2};
const RemoveIntersectionTypeTupleTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTupleTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["TupleType"]["Number"] = {"key":2};
const RemoveIntersectionTypeTupleTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTupleTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["TupleType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeTupleTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithTupleTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["TupleType"]["Any"] = {"key":2};
const RemoveIntersectionTypeTupleTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithArrayTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["ArrayType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeArrayTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithArrayTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["ArrayType"]["Object"] = {"key":2};
const RemoveIntersectionTypeArrayTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithArrayTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["ArrayType"]["String"] = {"key":2};
const RemoveIntersectionTypeArrayTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithArrayTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["ArrayType"]["Number"] = {"key":2};
const RemoveIntersectionTypeArrayTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithArrayTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["ArrayType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeArrayTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithArrayTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["ArrayType"]["Any"] = {"key":2};
const RemoveIntersectionTypeArrayTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithFunctionTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["FunctionType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithFunctionTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["FunctionType"]["Object"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithFunctionTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["FunctionType"]["String"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithFunctionTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["FunctionType"]["Number"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithFunctionTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["FunctionType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithFunctionTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["FunctionType"]["Any"] = {"key":2};
const RemoveIntersectionTypeFunctionTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

const IntersectionTypeTypeLiteralAnyWithConstructorTypeLiteral: Defaults["TypeLiteral"]["Any"] & Defaults["ConstructorType"]["Literal"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeLiteralFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithConstructorTypeObject: Defaults["TypeLiteral"]["Any"] & Defaults["ConstructorType"]["Object"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeObjectFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithConstructorTypeString: Defaults["TypeLiteral"]["Any"] & Defaults["ConstructorType"]["String"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeStringFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithConstructorTypeNumber: Defaults["TypeLiteral"]["Any"] & Defaults["ConstructorType"]["Number"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeNumberFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithConstructorTypeBoolean: Defaults["TypeLiteral"]["Any"] & Defaults["ConstructorType"]["Boolean"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeBooleanFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}
const IntersectionTypeTypeLiteralAnyWithConstructorTypeAny: Defaults["TypeLiteral"]["Any"] & Defaults["ConstructorType"]["Any"] = {"key":2};
const RemoveIntersectionTypeConstructorTypeAnyFromTypeLiteralAny: Defaults["TypeLiteral"]["Any"]= {"key":2}

