import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - ConstructorType
const IntersectionTypeConstructorTypeLiteralWithParenthesizedTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = 1;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithParenthesizedTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = 1;
const RemoveIntersectionTypeParenthesizedTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithParenthesizedTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["ParenthesizedType"]["String"] = 1;
const RemoveIntersectionTypeParenthesizedTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithParenthesizedTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = 1;
const RemoveIntersectionTypeParenthesizedTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithParenthesizedTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = 1;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithParenthesizedTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = 1;
const RemoveIntersectionTypeParenthesizedTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithTypeReferenceBuiltinLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferenceBuiltinObject: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferenceBuiltinString: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferenceBuiltinNumber: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferenceBuiltinBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferenceBuiltinAny: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithTypeReferencePredefinedLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferencePredefinedObject: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferencePredefinedString: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferencePredefinedNumber: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferencePredefinedBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeReferencePredefinedAny: Defaults["ConstructorType"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithUnionTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["UnionType"]["Literal"] = 1;
const RemoveIntersectionTypeUnionTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithUnionTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["UnionType"]["Object"] = 1;
const RemoveIntersectionTypeUnionTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithUnionTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["UnionType"]["String"] = 1;
const RemoveIntersectionTypeUnionTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithUnionTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["UnionType"]["Number"] = 1;
const RemoveIntersectionTypeUnionTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithUnionTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["UnionType"]["Boolean"] = 1;
const RemoveIntersectionTypeUnionTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithUnionTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["UnionType"]["Any"] = 1;
const RemoveIntersectionTypeUnionTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithIntersectionTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["IntersectionType"]["Literal"] = 1;
const RemoveIntersectionTypeIntersectionTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithIntersectionTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["IntersectionType"]["Object"] = 1;
const RemoveIntersectionTypeIntersectionTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithIntersectionTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["IntersectionType"]["String"] = 1;
const RemoveIntersectionTypeIntersectionTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithIntersectionTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["IntersectionType"]["Number"] = 1;
const RemoveIntersectionTypeIntersectionTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithIntersectionTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = 1;
const RemoveIntersectionTypeIntersectionTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithIntersectionTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["IntersectionType"]["Any"] = 1;
const RemoveIntersectionTypeIntersectionTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithTypeLiteralLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = 1;
const RemoveIntersectionTypeTypeLiteralLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeLiteralObject: Defaults["ConstructorType"]["Literal"] & Defaults["TypeLiteral"]["Object"] = 1;
const RemoveIntersectionTypeTypeLiteralObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeLiteralString: Defaults["ConstructorType"]["Literal"] & Defaults["TypeLiteral"]["String"] = 1;
const RemoveIntersectionTypeTypeLiteralStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeLiteralNumber: Defaults["ConstructorType"]["Literal"] & Defaults["TypeLiteral"]["Number"] = 1;
const RemoveIntersectionTypeTypeLiteralNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeLiteralBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeLiteralBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTypeLiteralAny: Defaults["ConstructorType"]["Literal"] & Defaults["TypeLiteral"]["Any"] = 1;
const RemoveIntersectionTypeTypeLiteralAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithTupleTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["TupleType"]["Literal"] = 1;
const RemoveIntersectionTypeTupleTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTupleTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["TupleType"]["Object"] = 1;
const RemoveIntersectionTypeTupleTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTupleTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["TupleType"]["String"] = 1;
const RemoveIntersectionTypeTupleTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTupleTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["TupleType"]["Number"] = 1;
const RemoveIntersectionTypeTupleTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTupleTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["TupleType"]["Boolean"] = 1;
const RemoveIntersectionTypeTupleTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithTupleTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["TupleType"]["Any"] = 1;
const RemoveIntersectionTypeTupleTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithArrayTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["ArrayType"]["Literal"] = 1;
const RemoveIntersectionTypeArrayTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithArrayTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["ArrayType"]["Object"] = 1;
const RemoveIntersectionTypeArrayTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithArrayTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["ArrayType"]["String"] = 1;
const RemoveIntersectionTypeArrayTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithArrayTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["ArrayType"]["Number"] = 1;
const RemoveIntersectionTypeArrayTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithArrayTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["ArrayType"]["Boolean"] = 1;
const RemoveIntersectionTypeArrayTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithArrayTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["ArrayType"]["Any"] = 1;
const RemoveIntersectionTypeArrayTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithFunctionTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["FunctionType"]["Literal"] = 1;
const RemoveIntersectionTypeFunctionTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithFunctionTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["FunctionType"]["Object"] = 1;
const RemoveIntersectionTypeFunctionTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithFunctionTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["FunctionType"]["String"] = 1;
const RemoveIntersectionTypeFunctionTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithFunctionTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["FunctionType"]["Number"] = 1;
const RemoveIntersectionTypeFunctionTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithFunctionTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["FunctionType"]["Boolean"] = 1;
const RemoveIntersectionTypeFunctionTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithFunctionTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["FunctionType"]["Any"] = 1;
const RemoveIntersectionTypeFunctionTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeLiteralWithConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"] & Defaults["ConstructorType"]["Literal"] = 1;
const RemoveIntersectionTypeConstructorTypeLiteralFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithConstructorTypeObject: Defaults["ConstructorType"]["Literal"] & Defaults["ConstructorType"]["Object"] = 1;
const RemoveIntersectionTypeConstructorTypeObjectFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithConstructorTypeString: Defaults["ConstructorType"]["Literal"] & Defaults["ConstructorType"]["String"] = 1;
const RemoveIntersectionTypeConstructorTypeStringFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithConstructorTypeNumber: Defaults["ConstructorType"]["Literal"] & Defaults["ConstructorType"]["Number"] = 1;
const RemoveIntersectionTypeConstructorTypeNumberFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithConstructorTypeBoolean: Defaults["ConstructorType"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = 1;
const RemoveIntersectionTypeConstructorTypeBooleanFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1
const IntersectionTypeConstructorTypeLiteralWithConstructorTypeAny: Defaults["ConstructorType"]["Literal"] & Defaults["ConstructorType"]["Any"] = 1;
const RemoveIntersectionTypeConstructorTypeAnyFromConstructorTypeLiteral: Defaults["ConstructorType"]["Literal"]= 1

const IntersectionTypeConstructorTypeObjectWithParenthesizedTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = {};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithParenthesizedTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["ParenthesizedType"]["Object"] = {};
const RemoveIntersectionTypeParenthesizedTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithParenthesizedTypeString: Defaults["ConstructorType"]["Object"] & Defaults["ParenthesizedType"]["String"] = {};
const RemoveIntersectionTypeParenthesizedTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithParenthesizedTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["ParenthesizedType"]["Number"] = {};
const RemoveIntersectionTypeParenthesizedTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithParenthesizedTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = {};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithParenthesizedTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["ParenthesizedType"]["Any"] = {};
const RemoveIntersectionTypeParenthesizedTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithTypeReferenceBuiltinLiteral: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferenceBuiltinObject: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferenceBuiltinString: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferenceBuiltinNumber: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferenceBuiltinBoolean: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferenceBuiltinAny: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithTypeReferencePredefinedLiteral: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferencePredefinedObject: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferencePredefinedString: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferencePredefinedNumber: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferencePredefinedBoolean: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeReferencePredefinedAny: Defaults["ConstructorType"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithUnionTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["UnionType"]["Literal"] = {};
const RemoveIntersectionTypeUnionTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithUnionTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["UnionType"]["Object"] = {};
const RemoveIntersectionTypeUnionTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithUnionTypeString: Defaults["ConstructorType"]["Object"] & Defaults["UnionType"]["String"] = {};
const RemoveIntersectionTypeUnionTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithUnionTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["UnionType"]["Number"] = {};
const RemoveIntersectionTypeUnionTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithUnionTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["UnionType"]["Boolean"] = {};
const RemoveIntersectionTypeUnionTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithUnionTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["UnionType"]["Any"] = {};
const RemoveIntersectionTypeUnionTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithIntersectionTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["IntersectionType"]["Literal"] = {};
const RemoveIntersectionTypeIntersectionTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithIntersectionTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["IntersectionType"]["Object"] = {};
const RemoveIntersectionTypeIntersectionTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithIntersectionTypeString: Defaults["ConstructorType"]["Object"] & Defaults["IntersectionType"]["String"] = {};
const RemoveIntersectionTypeIntersectionTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithIntersectionTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["IntersectionType"]["Number"] = {};
const RemoveIntersectionTypeIntersectionTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithIntersectionTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["IntersectionType"]["Boolean"] = {};
const RemoveIntersectionTypeIntersectionTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithIntersectionTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["IntersectionType"]["Any"] = {};
const RemoveIntersectionTypeIntersectionTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithTypeLiteralLiteral: Defaults["ConstructorType"]["Object"] & Defaults["TypeLiteral"]["Literal"] = {};
const RemoveIntersectionTypeTypeLiteralLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeLiteralObject: Defaults["ConstructorType"]["Object"] & Defaults["TypeLiteral"]["Object"] = {};
const RemoveIntersectionTypeTypeLiteralObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeLiteralString: Defaults["ConstructorType"]["Object"] & Defaults["TypeLiteral"]["String"] = {};
const RemoveIntersectionTypeTypeLiteralStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeLiteralNumber: Defaults["ConstructorType"]["Object"] & Defaults["TypeLiteral"]["Number"] = {};
const RemoveIntersectionTypeTypeLiteralNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeLiteralBoolean: Defaults["ConstructorType"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = {};
const RemoveIntersectionTypeTypeLiteralBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTypeLiteralAny: Defaults["ConstructorType"]["Object"] & Defaults["TypeLiteral"]["Any"] = {};
const RemoveIntersectionTypeTypeLiteralAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithTupleTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["TupleType"]["Literal"] = {};
const RemoveIntersectionTypeTupleTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTupleTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["TupleType"]["Object"] = {};
const RemoveIntersectionTypeTupleTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTupleTypeString: Defaults["ConstructorType"]["Object"] & Defaults["TupleType"]["String"] = {};
const RemoveIntersectionTypeTupleTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTupleTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["TupleType"]["Number"] = {};
const RemoveIntersectionTypeTupleTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTupleTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["TupleType"]["Boolean"] = {};
const RemoveIntersectionTypeTupleTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithTupleTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["TupleType"]["Any"] = {};
const RemoveIntersectionTypeTupleTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithArrayTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["ArrayType"]["Literal"] = {};
const RemoveIntersectionTypeArrayTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithArrayTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["ArrayType"]["Object"] = {};
const RemoveIntersectionTypeArrayTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithArrayTypeString: Defaults["ConstructorType"]["Object"] & Defaults["ArrayType"]["String"] = {};
const RemoveIntersectionTypeArrayTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithArrayTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["ArrayType"]["Number"] = {};
const RemoveIntersectionTypeArrayTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithArrayTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["ArrayType"]["Boolean"] = {};
const RemoveIntersectionTypeArrayTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithArrayTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["ArrayType"]["Any"] = {};
const RemoveIntersectionTypeArrayTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithFunctionTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["FunctionType"]["Literal"] = {};
const RemoveIntersectionTypeFunctionTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithFunctionTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["FunctionType"]["Object"] = {};
const RemoveIntersectionTypeFunctionTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithFunctionTypeString: Defaults["ConstructorType"]["Object"] & Defaults["FunctionType"]["String"] = {};
const RemoveIntersectionTypeFunctionTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithFunctionTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["FunctionType"]["Number"] = {};
const RemoveIntersectionTypeFunctionTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithFunctionTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["FunctionType"]["Boolean"] = {};
const RemoveIntersectionTypeFunctionTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithFunctionTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["FunctionType"]["Any"] = {};
const RemoveIntersectionTypeFunctionTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeObjectWithConstructorTypeLiteral: Defaults["ConstructorType"]["Object"] & Defaults["ConstructorType"]["Literal"] = {};
const RemoveIntersectionTypeConstructorTypeLiteralFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithConstructorTypeObject: Defaults["ConstructorType"]["Object"] & Defaults["ConstructorType"]["Object"] = {};
const RemoveIntersectionTypeConstructorTypeObjectFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithConstructorTypeString: Defaults["ConstructorType"]["Object"] & Defaults["ConstructorType"]["String"] = {};
const RemoveIntersectionTypeConstructorTypeStringFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithConstructorTypeNumber: Defaults["ConstructorType"]["Object"] & Defaults["ConstructorType"]["Number"] = {};
const RemoveIntersectionTypeConstructorTypeNumberFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithConstructorTypeBoolean: Defaults["ConstructorType"]["Object"] & Defaults["ConstructorType"]["Boolean"] = {};
const RemoveIntersectionTypeConstructorTypeBooleanFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}
const IntersectionTypeConstructorTypeObjectWithConstructorTypeAny: Defaults["ConstructorType"]["Object"] & Defaults["ConstructorType"]["Any"] = {};
const RemoveIntersectionTypeConstructorTypeAnyFromConstructorTypeObject: Defaults["ConstructorType"]["Object"]= {}

const IntersectionTypeConstructorTypeStringWithParenthesizedTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["ParenthesizedType"]["Literal"] = "two";
const RemoveIntersectionTypeParenthesizedTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithParenthesizedTypeObject: Defaults["ConstructorType"]["String"] & Defaults["ParenthesizedType"]["Object"] = "two";
const RemoveIntersectionTypeParenthesizedTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithParenthesizedTypeString: Defaults["ConstructorType"]["String"] & Defaults["ParenthesizedType"]["String"] = "two";
const RemoveIntersectionTypeParenthesizedTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithParenthesizedTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["ParenthesizedType"]["Number"] = "two";
const RemoveIntersectionTypeParenthesizedTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithParenthesizedTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = "two";
const RemoveIntersectionTypeParenthesizedTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithParenthesizedTypeAny: Defaults["ConstructorType"]["String"] & Defaults["ParenthesizedType"]["Any"] = "two";
const RemoveIntersectionTypeParenthesizedTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithTypeReferenceBuiltinLiteral: Defaults["ConstructorType"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferenceBuiltinObject: Defaults["ConstructorType"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferenceBuiltinString: Defaults["ConstructorType"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferenceBuiltinNumber: Defaults["ConstructorType"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferenceBuiltinBoolean: Defaults["ConstructorType"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferenceBuiltinAny: Defaults["ConstructorType"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithTypeReferencePredefinedLiteral: Defaults["ConstructorType"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferencePredefinedObject: Defaults["ConstructorType"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferencePredefinedString: Defaults["ConstructorType"]["String"] & Defaults["TypeReferencePredefined"]["String"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferencePredefinedNumber: Defaults["ConstructorType"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferencePredefinedBoolean: Defaults["ConstructorType"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeReferencePredefinedAny: Defaults["ConstructorType"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithUnionTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["UnionType"]["Literal"] = "two";
const RemoveIntersectionTypeUnionTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithUnionTypeObject: Defaults["ConstructorType"]["String"] & Defaults["UnionType"]["Object"] = "two";
const RemoveIntersectionTypeUnionTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithUnionTypeString: Defaults["ConstructorType"]["String"] & Defaults["UnionType"]["String"] = "two";
const RemoveIntersectionTypeUnionTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithUnionTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["UnionType"]["Number"] = "two";
const RemoveIntersectionTypeUnionTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithUnionTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["UnionType"]["Boolean"] = "two";
const RemoveIntersectionTypeUnionTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithUnionTypeAny: Defaults["ConstructorType"]["String"] & Defaults["UnionType"]["Any"] = "two";
const RemoveIntersectionTypeUnionTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithIntersectionTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["IntersectionType"]["Literal"] = "two";
const RemoveIntersectionTypeIntersectionTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithIntersectionTypeObject: Defaults["ConstructorType"]["String"] & Defaults["IntersectionType"]["Object"] = "two";
const RemoveIntersectionTypeIntersectionTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithIntersectionTypeString: Defaults["ConstructorType"]["String"] & Defaults["IntersectionType"]["String"] = "two";
const RemoveIntersectionTypeIntersectionTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithIntersectionTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["IntersectionType"]["Number"] = "two";
const RemoveIntersectionTypeIntersectionTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithIntersectionTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["IntersectionType"]["Boolean"] = "two";
const RemoveIntersectionTypeIntersectionTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithIntersectionTypeAny: Defaults["ConstructorType"]["String"] & Defaults["IntersectionType"]["Any"] = "two";
const RemoveIntersectionTypeIntersectionTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithTypeLiteralLiteral: Defaults["ConstructorType"]["String"] & Defaults["TypeLiteral"]["Literal"] = "two";
const RemoveIntersectionTypeTypeLiteralLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeLiteralObject: Defaults["ConstructorType"]["String"] & Defaults["TypeLiteral"]["Object"] = "two";
const RemoveIntersectionTypeTypeLiteralObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeLiteralString: Defaults["ConstructorType"]["String"] & Defaults["TypeLiteral"]["String"] = "two";
const RemoveIntersectionTypeTypeLiteralStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeLiteralNumber: Defaults["ConstructorType"]["String"] & Defaults["TypeLiteral"]["Number"] = "two";
const RemoveIntersectionTypeTypeLiteralNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeLiteralBoolean: Defaults["ConstructorType"]["String"] & Defaults["TypeLiteral"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeLiteralBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTypeLiteralAny: Defaults["ConstructorType"]["String"] & Defaults["TypeLiteral"]["Any"] = "two";
const RemoveIntersectionTypeTypeLiteralAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithTupleTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["TupleType"]["Literal"] = "two";
const RemoveIntersectionTypeTupleTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTupleTypeObject: Defaults["ConstructorType"]["String"] & Defaults["TupleType"]["Object"] = "two";
const RemoveIntersectionTypeTupleTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTupleTypeString: Defaults["ConstructorType"]["String"] & Defaults["TupleType"]["String"] = "two";
const RemoveIntersectionTypeTupleTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTupleTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["TupleType"]["Number"] = "two";
const RemoveIntersectionTypeTupleTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTupleTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["TupleType"]["Boolean"] = "two";
const RemoveIntersectionTypeTupleTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithTupleTypeAny: Defaults["ConstructorType"]["String"] & Defaults["TupleType"]["Any"] = "two";
const RemoveIntersectionTypeTupleTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithArrayTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["ArrayType"]["Literal"] = "two";
const RemoveIntersectionTypeArrayTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithArrayTypeObject: Defaults["ConstructorType"]["String"] & Defaults["ArrayType"]["Object"] = "two";
const RemoveIntersectionTypeArrayTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithArrayTypeString: Defaults["ConstructorType"]["String"] & Defaults["ArrayType"]["String"] = "two";
const RemoveIntersectionTypeArrayTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithArrayTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["ArrayType"]["Number"] = "two";
const RemoveIntersectionTypeArrayTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithArrayTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["ArrayType"]["Boolean"] = "two";
const RemoveIntersectionTypeArrayTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithArrayTypeAny: Defaults["ConstructorType"]["String"] & Defaults["ArrayType"]["Any"] = "two";
const RemoveIntersectionTypeArrayTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithFunctionTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["FunctionType"]["Literal"] = "two";
const RemoveIntersectionTypeFunctionTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithFunctionTypeObject: Defaults["ConstructorType"]["String"] & Defaults["FunctionType"]["Object"] = "two";
const RemoveIntersectionTypeFunctionTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithFunctionTypeString: Defaults["ConstructorType"]["String"] & Defaults["FunctionType"]["String"] = "two";
const RemoveIntersectionTypeFunctionTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithFunctionTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["FunctionType"]["Number"] = "two";
const RemoveIntersectionTypeFunctionTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithFunctionTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["FunctionType"]["Boolean"] = "two";
const RemoveIntersectionTypeFunctionTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithFunctionTypeAny: Defaults["ConstructorType"]["String"] & Defaults["FunctionType"]["Any"] = "two";
const RemoveIntersectionTypeFunctionTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeStringWithConstructorTypeLiteral: Defaults["ConstructorType"]["String"] & Defaults["ConstructorType"]["Literal"] = "two";
const RemoveIntersectionTypeConstructorTypeLiteralFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithConstructorTypeObject: Defaults["ConstructorType"]["String"] & Defaults["ConstructorType"]["Object"] = "two";
const RemoveIntersectionTypeConstructorTypeObjectFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithConstructorTypeString: Defaults["ConstructorType"]["String"] & Defaults["ConstructorType"]["String"] = "two";
const RemoveIntersectionTypeConstructorTypeStringFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithConstructorTypeNumber: Defaults["ConstructorType"]["String"] & Defaults["ConstructorType"]["Number"] = "two";
const RemoveIntersectionTypeConstructorTypeNumberFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithConstructorTypeBoolean: Defaults["ConstructorType"]["String"] & Defaults["ConstructorType"]["Boolean"] = "two";
const RemoveIntersectionTypeConstructorTypeBooleanFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"
const IntersectionTypeConstructorTypeStringWithConstructorTypeAny: Defaults["ConstructorType"]["String"] & Defaults["ConstructorType"]["Any"] = "two";
const RemoveIntersectionTypeConstructorTypeAnyFromConstructorTypeString: Defaults["ConstructorType"]["String"]= "two"

const IntersectionTypeConstructorTypeNumberWithParenthesizedTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithParenthesizedTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithParenthesizedTypeString: Defaults["ConstructorType"]["Number"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithParenthesizedTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithParenthesizedTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithParenthesizedTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithTypeReferenceBuiltinLiteral: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferenceBuiltinObject: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferenceBuiltinString: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferenceBuiltinNumber: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferenceBuiltinBoolean: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferenceBuiltinAny: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithTypeReferencePredefinedLiteral: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferencePredefinedObject: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferencePredefinedString: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferencePredefinedNumber: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferencePredefinedBoolean: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeReferencePredefinedAny: Defaults["ConstructorType"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithUnionTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithUnionTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithUnionTypeString: Defaults["ConstructorType"]["Number"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithUnionTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithUnionTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithUnionTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithIntersectionTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithIntersectionTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithIntersectionTypeString: Defaults["ConstructorType"]["Number"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithIntersectionTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithIntersectionTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithIntersectionTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithTypeLiteralLiteral: Defaults["ConstructorType"]["Number"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeLiteralObject: Defaults["ConstructorType"]["Number"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeLiteralString: Defaults["ConstructorType"]["Number"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeLiteralNumber: Defaults["ConstructorType"]["Number"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeLiteralBoolean: Defaults["ConstructorType"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTypeLiteralAny: Defaults["ConstructorType"]["Number"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithTupleTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTupleTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTupleTypeString: Defaults["ConstructorType"]["Number"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTupleTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTupleTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithTupleTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithArrayTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithArrayTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithArrayTypeString: Defaults["ConstructorType"]["Number"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithArrayTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithArrayTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithArrayTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithFunctionTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithFunctionTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithFunctionTypeString: Defaults["ConstructorType"]["Number"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithFunctionTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithFunctionTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithFunctionTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeNumberWithConstructorTypeLiteral: Defaults["ConstructorType"]["Number"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithConstructorTypeObject: Defaults["ConstructorType"]["Number"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithConstructorTypeString: Defaults["ConstructorType"]["Number"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithConstructorTypeNumber: Defaults["ConstructorType"]["Number"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithConstructorTypeBoolean: Defaults["ConstructorType"]["Number"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2
const IntersectionTypeConstructorTypeNumberWithConstructorTypeAny: Defaults["ConstructorType"]["Number"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromConstructorTypeNumber: Defaults["ConstructorType"]["Number"]= 2

const IntersectionTypeConstructorTypeBooleanWithParenthesizedTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = true;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithParenthesizedTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = true;
const RemoveIntersectionTypeParenthesizedTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithParenthesizedTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = true;
const RemoveIntersectionTypeParenthesizedTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithParenthesizedTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = true;
const RemoveIntersectionTypeParenthesizedTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithParenthesizedTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = true;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithParenthesizedTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = true;
const RemoveIntersectionTypeParenthesizedTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithTypeReferenceBuiltinLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferenceBuiltinObject: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferenceBuiltinString: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferenceBuiltinNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferenceBuiltinBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferenceBuiltinAny: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithTypeReferencePredefinedLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferencePredefinedObject: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferencePredefinedString: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferencePredefinedNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferencePredefinedBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeReferencePredefinedAny: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithUnionTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["UnionType"]["Literal"] = true;
const RemoveIntersectionTypeUnionTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithUnionTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["UnionType"]["Object"] = true;
const RemoveIntersectionTypeUnionTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithUnionTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["UnionType"]["String"] = true;
const RemoveIntersectionTypeUnionTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithUnionTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["UnionType"]["Number"] = true;
const RemoveIntersectionTypeUnionTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithUnionTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["UnionType"]["Boolean"] = true;
const RemoveIntersectionTypeUnionTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithUnionTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["UnionType"]["Any"] = true;
const RemoveIntersectionTypeUnionTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithIntersectionTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = true;
const RemoveIntersectionTypeIntersectionTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithIntersectionTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["IntersectionType"]["Object"] = true;
const RemoveIntersectionTypeIntersectionTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithIntersectionTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["IntersectionType"]["String"] = true;
const RemoveIntersectionTypeIntersectionTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithIntersectionTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["IntersectionType"]["Number"] = true;
const RemoveIntersectionTypeIntersectionTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithIntersectionTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = true;
const RemoveIntersectionTypeIntersectionTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithIntersectionTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["IntersectionType"]["Any"] = true;
const RemoveIntersectionTypeIntersectionTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithTypeLiteralLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = true;
const RemoveIntersectionTypeTypeLiteralLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeLiteralObject: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = true;
const RemoveIntersectionTypeTypeLiteralObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeLiteralString: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeLiteral"]["String"] = true;
const RemoveIntersectionTypeTypeLiteralStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeLiteralNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = true;
const RemoveIntersectionTypeTypeLiteralNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeLiteralBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = true;
const RemoveIntersectionTypeTypeLiteralBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTypeLiteralAny: Defaults["ConstructorType"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = true;
const RemoveIntersectionTypeTypeLiteralAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithTupleTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["TupleType"]["Literal"] = true;
const RemoveIntersectionTypeTupleTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTupleTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["TupleType"]["Object"] = true;
const RemoveIntersectionTypeTupleTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTupleTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["TupleType"]["String"] = true;
const RemoveIntersectionTypeTupleTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTupleTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["TupleType"]["Number"] = true;
const RemoveIntersectionTypeTupleTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTupleTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["TupleType"]["Boolean"] = true;
const RemoveIntersectionTypeTupleTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithTupleTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["TupleType"]["Any"] = true;
const RemoveIntersectionTypeTupleTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithArrayTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["ArrayType"]["Literal"] = true;
const RemoveIntersectionTypeArrayTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithArrayTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["ArrayType"]["Object"] = true;
const RemoveIntersectionTypeArrayTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithArrayTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["ArrayType"]["String"] = true;
const RemoveIntersectionTypeArrayTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithArrayTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["ArrayType"]["Number"] = true;
const RemoveIntersectionTypeArrayTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithArrayTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = true;
const RemoveIntersectionTypeArrayTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithArrayTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["ArrayType"]["Any"] = true;
const RemoveIntersectionTypeArrayTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithFunctionTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["FunctionType"]["Literal"] = true;
const RemoveIntersectionTypeFunctionTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithFunctionTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["FunctionType"]["Object"] = true;
const RemoveIntersectionTypeFunctionTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithFunctionTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["FunctionType"]["String"] = true;
const RemoveIntersectionTypeFunctionTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithFunctionTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["FunctionType"]["Number"] = true;
const RemoveIntersectionTypeFunctionTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithFunctionTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = true;
const RemoveIntersectionTypeFunctionTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithFunctionTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["FunctionType"]["Any"] = true;
const RemoveIntersectionTypeFunctionTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeBooleanWithConstructorTypeLiteral: Defaults["ConstructorType"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = true;
const RemoveIntersectionTypeConstructorTypeLiteralFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithConstructorTypeObject: Defaults["ConstructorType"]["Boolean"] & Defaults["ConstructorType"]["Object"] = true;
const RemoveIntersectionTypeConstructorTypeObjectFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithConstructorTypeString: Defaults["ConstructorType"]["Boolean"] & Defaults["ConstructorType"]["String"] = true;
const RemoveIntersectionTypeConstructorTypeStringFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithConstructorTypeNumber: Defaults["ConstructorType"]["Boolean"] & Defaults["ConstructorType"]["Number"] = true;
const RemoveIntersectionTypeConstructorTypeNumberFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = true;
const RemoveIntersectionTypeConstructorTypeBooleanFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true
const IntersectionTypeConstructorTypeBooleanWithConstructorTypeAny: Defaults["ConstructorType"]["Boolean"] & Defaults["ConstructorType"]["Any"] = true;
const RemoveIntersectionTypeConstructorTypeAnyFromConstructorTypeBoolean: Defaults["ConstructorType"]["Boolean"]= true

const IntersectionTypeConstructorTypeAnyWithParenthesizedTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithParenthesizedTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithParenthesizedTypeString: Defaults["ConstructorType"]["Any"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithParenthesizedTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithParenthesizedTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithParenthesizedTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithTypeReferenceBuiltinLiteral: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferenceBuiltinObject: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferenceBuiltinString: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferenceBuiltinNumber: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferenceBuiltinBoolean: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferenceBuiltinAny: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithTypeReferencePredefinedLiteral: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferencePredefinedObject: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferencePredefinedString: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferencePredefinedNumber: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferencePredefinedBoolean: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeReferencePredefinedAny: Defaults["ConstructorType"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithUnionTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithUnionTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithUnionTypeString: Defaults["ConstructorType"]["Any"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithUnionTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithUnionTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithUnionTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithIntersectionTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithIntersectionTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithIntersectionTypeString: Defaults["ConstructorType"]["Any"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithIntersectionTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithIntersectionTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithIntersectionTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithTypeLiteralLiteral: Defaults["ConstructorType"]["Any"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeLiteralObject: Defaults["ConstructorType"]["Any"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeLiteralString: Defaults["ConstructorType"]["Any"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeLiteralNumber: Defaults["ConstructorType"]["Any"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeLiteralBoolean: Defaults["ConstructorType"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTypeLiteralAny: Defaults["ConstructorType"]["Any"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithTupleTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTupleTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTupleTypeString: Defaults["ConstructorType"]["Any"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTupleTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTupleTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithTupleTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithArrayTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithArrayTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithArrayTypeString: Defaults["ConstructorType"]["Any"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithArrayTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithArrayTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithArrayTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithFunctionTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithFunctionTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithFunctionTypeString: Defaults["ConstructorType"]["Any"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithFunctionTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithFunctionTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithFunctionTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

const IntersectionTypeConstructorTypeAnyWithConstructorTypeLiteral: Defaults["ConstructorType"]["Any"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithConstructorTypeObject: Defaults["ConstructorType"]["Any"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithConstructorTypeString: Defaults["ConstructorType"]["Any"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithConstructorTypeNumber: Defaults["ConstructorType"]["Any"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithConstructorTypeBoolean: Defaults["ConstructorType"]["Any"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2
const IntersectionTypeConstructorTypeAnyWithConstructorTypeAny: Defaults["ConstructorType"]["Any"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromConstructorTypeAny: Defaults["ConstructorType"]["Any"]= 2

