import { Defaults } from "../../defaults";

/*
 * IntersectionType
 */

// Remove Intersection - ParenthesizedType
const IntersectionTypeParenthesizedTypeLiteralWithParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["ParenthesizedType"]["Literal"] = 1;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithParenthesizedTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["ParenthesizedType"]["Object"] = 1;
const RemoveIntersectionTypeParenthesizedTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithParenthesizedTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["ParenthesizedType"]["String"] = 1;
const RemoveIntersectionTypeParenthesizedTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["ParenthesizedType"]["Number"] = 1;
const RemoveIntersectionTypeParenthesizedTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["ParenthesizedType"]["Boolean"] = 1;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithParenthesizedTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["ParenthesizedType"]["Any"] = 1;
const RemoveIntersectionTypeParenthesizedTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithTypeReferenceBuiltinLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferenceBuiltinObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferenceBuiltinString: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["String"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferenceBuiltinNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferenceBuiltinBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferenceBuiltinAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferenceBuiltin"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithTypeReferencePredefinedLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferencePredefined"]["Literal"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferencePredefinedObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferencePredefined"]["Object"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferencePredefinedString: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferencePredefined"]["String"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferencePredefinedNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferencePredefined"]["Number"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferencePredefinedBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferencePredefined"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeReferencePredefinedAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeReferencePredefined"]["Any"] = 1;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithUnionTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["UnionType"]["Literal"] = 1;
const RemoveIntersectionTypeUnionTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithUnionTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["UnionType"]["Object"] = 1;
const RemoveIntersectionTypeUnionTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithUnionTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["UnionType"]["String"] = 1;
const RemoveIntersectionTypeUnionTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithUnionTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["UnionType"]["Number"] = 1;
const RemoveIntersectionTypeUnionTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithUnionTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["UnionType"]["Boolean"] = 1;
const RemoveIntersectionTypeUnionTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithUnionTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["UnionType"]["Any"] = 1;
const RemoveIntersectionTypeUnionTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithIntersectionTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["IntersectionType"]["Literal"] = 1;
const RemoveIntersectionTypeIntersectionTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithIntersectionTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["IntersectionType"]["Object"] = 1;
const RemoveIntersectionTypeIntersectionTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithIntersectionTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["IntersectionType"]["String"] = 1;
const RemoveIntersectionTypeIntersectionTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithIntersectionTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["IntersectionType"]["Number"] = 1;
const RemoveIntersectionTypeIntersectionTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithIntersectionTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["IntersectionType"]["Boolean"] = 1;
const RemoveIntersectionTypeIntersectionTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithIntersectionTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["IntersectionType"]["Any"] = 1;
const RemoveIntersectionTypeIntersectionTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithTypeLiteralLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeLiteral"]["Literal"] = 1;
const RemoveIntersectionTypeTypeLiteralLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeLiteralObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeLiteral"]["Object"] = 1;
const RemoveIntersectionTypeTypeLiteralObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeLiteralString: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeLiteral"]["String"] = 1;
const RemoveIntersectionTypeTypeLiteralStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeLiteralNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeLiteral"]["Number"] = 1;
const RemoveIntersectionTypeTypeLiteralNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeLiteralBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeLiteral"]["Boolean"] = 1;
const RemoveIntersectionTypeTypeLiteralBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTypeLiteralAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["TypeLiteral"]["Any"] = 1;
const RemoveIntersectionTypeTypeLiteralAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithTupleTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["TupleType"]["Literal"] = 1;
const RemoveIntersectionTypeTupleTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTupleTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["TupleType"]["Object"] = 1;
const RemoveIntersectionTypeTupleTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTupleTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["TupleType"]["String"] = 1;
const RemoveIntersectionTypeTupleTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTupleTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["TupleType"]["Number"] = 1;
const RemoveIntersectionTypeTupleTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTupleTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["TupleType"]["Boolean"] = 1;
const RemoveIntersectionTypeTupleTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithTupleTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["TupleType"]["Any"] = 1;
const RemoveIntersectionTypeTupleTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithArrayTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["ArrayType"]["Literal"] = 1;
const RemoveIntersectionTypeArrayTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithArrayTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["ArrayType"]["Object"] = 1;
const RemoveIntersectionTypeArrayTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithArrayTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["ArrayType"]["String"] = 1;
const RemoveIntersectionTypeArrayTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithArrayTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["ArrayType"]["Number"] = 1;
const RemoveIntersectionTypeArrayTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithArrayTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["ArrayType"]["Boolean"] = 1;
const RemoveIntersectionTypeArrayTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithArrayTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["ArrayType"]["Any"] = 1;
const RemoveIntersectionTypeArrayTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithFunctionTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["FunctionType"]["Literal"] = 1;
const RemoveIntersectionTypeFunctionTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithFunctionTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["FunctionType"]["Object"] = 1;
const RemoveIntersectionTypeFunctionTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithFunctionTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["FunctionType"]["String"] = 1;
const RemoveIntersectionTypeFunctionTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithFunctionTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["FunctionType"]["Number"] = 1;
const RemoveIntersectionTypeFunctionTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithFunctionTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["FunctionType"]["Boolean"] = 1;
const RemoveIntersectionTypeFunctionTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithFunctionTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["FunctionType"]["Any"] = 1;
const RemoveIntersectionTypeFunctionTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeLiteralWithConstructorTypeLiteral: Defaults["ParenthesizedType"]["Literal"] & Defaults["ConstructorType"]["Literal"] = 1;
const RemoveIntersectionTypeConstructorTypeLiteralFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithConstructorTypeObject: Defaults["ParenthesizedType"]["Literal"] & Defaults["ConstructorType"]["Object"] = 1;
const RemoveIntersectionTypeConstructorTypeObjectFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithConstructorTypeString: Defaults["ParenthesizedType"]["Literal"] & Defaults["ConstructorType"]["String"] = 1;
const RemoveIntersectionTypeConstructorTypeStringFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithConstructorTypeNumber: Defaults["ParenthesizedType"]["Literal"] & Defaults["ConstructorType"]["Number"] = 1;
const RemoveIntersectionTypeConstructorTypeNumberFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithConstructorTypeBoolean: Defaults["ParenthesizedType"]["Literal"] & Defaults["ConstructorType"]["Boolean"] = 1;
const RemoveIntersectionTypeConstructorTypeBooleanFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1
const IntersectionTypeParenthesizedTypeLiteralWithConstructorTypeAny: Defaults["ParenthesizedType"]["Literal"] & Defaults["ConstructorType"]["Any"] = 1;
const RemoveIntersectionTypeConstructorTypeAnyFromParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Literal"]= 1

const IntersectionTypeParenthesizedTypeObjectWithParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["ParenthesizedType"]["Literal"] = {};
const RemoveIntersectionTypeParenthesizedTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["ParenthesizedType"]["Object"] = {};
const RemoveIntersectionTypeParenthesizedTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithParenthesizedTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["ParenthesizedType"]["String"] = {};
const RemoveIntersectionTypeParenthesizedTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["ParenthesizedType"]["Number"] = {};
const RemoveIntersectionTypeParenthesizedTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["ParenthesizedType"]["Boolean"] = {};
const RemoveIntersectionTypeParenthesizedTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithParenthesizedTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["ParenthesizedType"]["Any"] = {};
const RemoveIntersectionTypeParenthesizedTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithTypeReferenceBuiltinLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferenceBuiltinObject: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Object"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferenceBuiltinString: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferenceBuiltin"]["String"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferenceBuiltinNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Number"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferenceBuiltinBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferenceBuiltinAny: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferenceBuiltin"]["Any"] = {};
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithTypeReferencePredefinedLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferencePredefined"]["Literal"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferencePredefinedObject: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferencePredefined"]["Object"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferencePredefinedString: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferencePredefined"]["String"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferencePredefinedNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferencePredefined"]["Number"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferencePredefinedBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferencePredefined"]["Boolean"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeReferencePredefinedAny: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeReferencePredefined"]["Any"] = {};
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithUnionTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["UnionType"]["Literal"] = {};
const RemoveIntersectionTypeUnionTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithUnionTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["UnionType"]["Object"] = {};
const RemoveIntersectionTypeUnionTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithUnionTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["UnionType"]["String"] = {};
const RemoveIntersectionTypeUnionTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithUnionTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["UnionType"]["Number"] = {};
const RemoveIntersectionTypeUnionTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithUnionTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["UnionType"]["Boolean"] = {};
const RemoveIntersectionTypeUnionTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithUnionTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["UnionType"]["Any"] = {};
const RemoveIntersectionTypeUnionTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithIntersectionTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["IntersectionType"]["Literal"] = {};
const RemoveIntersectionTypeIntersectionTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithIntersectionTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["IntersectionType"]["Object"] = {};
const RemoveIntersectionTypeIntersectionTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithIntersectionTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["IntersectionType"]["String"] = {};
const RemoveIntersectionTypeIntersectionTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithIntersectionTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["IntersectionType"]["Number"] = {};
const RemoveIntersectionTypeIntersectionTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithIntersectionTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["IntersectionType"]["Boolean"] = {};
const RemoveIntersectionTypeIntersectionTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithIntersectionTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["IntersectionType"]["Any"] = {};
const RemoveIntersectionTypeIntersectionTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithTypeLiteralLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeLiteral"]["Literal"] = {};
const RemoveIntersectionTypeTypeLiteralLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeLiteralObject: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeLiteral"]["Object"] = {};
const RemoveIntersectionTypeTypeLiteralObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeLiteralString: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeLiteral"]["String"] = {};
const RemoveIntersectionTypeTypeLiteralStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeLiteralNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeLiteral"]["Number"] = {};
const RemoveIntersectionTypeTypeLiteralNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeLiteralBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeLiteral"]["Boolean"] = {};
const RemoveIntersectionTypeTypeLiteralBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTypeLiteralAny: Defaults["ParenthesizedType"]["Object"] & Defaults["TypeLiteral"]["Any"] = {};
const RemoveIntersectionTypeTypeLiteralAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithTupleTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["TupleType"]["Literal"] = {};
const RemoveIntersectionTypeTupleTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTupleTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["TupleType"]["Object"] = {};
const RemoveIntersectionTypeTupleTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTupleTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["TupleType"]["String"] = {};
const RemoveIntersectionTypeTupleTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTupleTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["TupleType"]["Number"] = {};
const RemoveIntersectionTypeTupleTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTupleTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["TupleType"]["Boolean"] = {};
const RemoveIntersectionTypeTupleTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithTupleTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["TupleType"]["Any"] = {};
const RemoveIntersectionTypeTupleTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithArrayTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["ArrayType"]["Literal"] = {};
const RemoveIntersectionTypeArrayTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithArrayTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["ArrayType"]["Object"] = {};
const RemoveIntersectionTypeArrayTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithArrayTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["ArrayType"]["String"] = {};
const RemoveIntersectionTypeArrayTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithArrayTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["ArrayType"]["Number"] = {};
const RemoveIntersectionTypeArrayTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithArrayTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["ArrayType"]["Boolean"] = {};
const RemoveIntersectionTypeArrayTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithArrayTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["ArrayType"]["Any"] = {};
const RemoveIntersectionTypeArrayTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithFunctionTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["FunctionType"]["Literal"] = {};
const RemoveIntersectionTypeFunctionTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithFunctionTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["FunctionType"]["Object"] = {};
const RemoveIntersectionTypeFunctionTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithFunctionTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["FunctionType"]["String"] = {};
const RemoveIntersectionTypeFunctionTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithFunctionTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["FunctionType"]["Number"] = {};
const RemoveIntersectionTypeFunctionTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithFunctionTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["FunctionType"]["Boolean"] = {};
const RemoveIntersectionTypeFunctionTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithFunctionTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["FunctionType"]["Any"] = {};
const RemoveIntersectionTypeFunctionTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeObjectWithConstructorTypeLiteral: Defaults["ParenthesizedType"]["Object"] & Defaults["ConstructorType"]["Literal"] = {};
const RemoveIntersectionTypeConstructorTypeLiteralFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithConstructorTypeObject: Defaults["ParenthesizedType"]["Object"] & Defaults["ConstructorType"]["Object"] = {};
const RemoveIntersectionTypeConstructorTypeObjectFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithConstructorTypeString: Defaults["ParenthesizedType"]["Object"] & Defaults["ConstructorType"]["String"] = {};
const RemoveIntersectionTypeConstructorTypeStringFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithConstructorTypeNumber: Defaults["ParenthesizedType"]["Object"] & Defaults["ConstructorType"]["Number"] = {};
const RemoveIntersectionTypeConstructorTypeNumberFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithConstructorTypeBoolean: Defaults["ParenthesizedType"]["Object"] & Defaults["ConstructorType"]["Boolean"] = {};
const RemoveIntersectionTypeConstructorTypeBooleanFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}
const IntersectionTypeParenthesizedTypeObjectWithConstructorTypeAny: Defaults["ParenthesizedType"]["Object"] & Defaults["ConstructorType"]["Any"] = {};
const RemoveIntersectionTypeConstructorTypeAnyFromParenthesizedTypeObject: Defaults["ParenthesizedType"]["Object"]= {}

const IntersectionTypeParenthesizedTypeStringWithParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["ParenthesizedType"]["Literal"] = "two";
const RemoveIntersectionTypeParenthesizedTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithParenthesizedTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["ParenthesizedType"]["Object"] = "two";
const RemoveIntersectionTypeParenthesizedTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithParenthesizedTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["ParenthesizedType"]["String"] = "two";
const RemoveIntersectionTypeParenthesizedTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithParenthesizedTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["ParenthesizedType"]["Number"] = "two";
const RemoveIntersectionTypeParenthesizedTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["ParenthesizedType"]["Boolean"] = "two";
const RemoveIntersectionTypeParenthesizedTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithParenthesizedTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["ParenthesizedType"]["Any"] = "two";
const RemoveIntersectionTypeParenthesizedTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithTypeReferenceBuiltinLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferenceBuiltin"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferenceBuiltinObject: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferenceBuiltin"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferenceBuiltinString: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferenceBuiltin"]["String"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferenceBuiltinNumber: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferenceBuiltin"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferenceBuiltinBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferenceBuiltinAny: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferenceBuiltin"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithTypeReferencePredefinedLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferencePredefined"]["Literal"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferencePredefinedObject: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferencePredefined"]["Object"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferencePredefinedString: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferencePredefined"]["String"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferencePredefinedNumber: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferencePredefined"]["Number"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferencePredefinedBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferencePredefined"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeReferencePredefinedAny: Defaults["ParenthesizedType"]["String"] & Defaults["TypeReferencePredefined"]["Any"] = "two";
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithUnionTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["UnionType"]["Literal"] = "two";
const RemoveIntersectionTypeUnionTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithUnionTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["UnionType"]["Object"] = "two";
const RemoveIntersectionTypeUnionTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithUnionTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["UnionType"]["String"] = "two";
const RemoveIntersectionTypeUnionTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithUnionTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["UnionType"]["Number"] = "two";
const RemoveIntersectionTypeUnionTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithUnionTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["UnionType"]["Boolean"] = "two";
const RemoveIntersectionTypeUnionTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithUnionTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["UnionType"]["Any"] = "two";
const RemoveIntersectionTypeUnionTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithIntersectionTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["IntersectionType"]["Literal"] = "two";
const RemoveIntersectionTypeIntersectionTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithIntersectionTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["IntersectionType"]["Object"] = "two";
const RemoveIntersectionTypeIntersectionTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithIntersectionTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["IntersectionType"]["String"] = "two";
const RemoveIntersectionTypeIntersectionTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithIntersectionTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["IntersectionType"]["Number"] = "two";
const RemoveIntersectionTypeIntersectionTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithIntersectionTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["IntersectionType"]["Boolean"] = "two";
const RemoveIntersectionTypeIntersectionTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithIntersectionTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["IntersectionType"]["Any"] = "two";
const RemoveIntersectionTypeIntersectionTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithTypeLiteralLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["TypeLiteral"]["Literal"] = "two";
const RemoveIntersectionTypeTypeLiteralLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeLiteralObject: Defaults["ParenthesizedType"]["String"] & Defaults["TypeLiteral"]["Object"] = "two";
const RemoveIntersectionTypeTypeLiteralObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeLiteralString: Defaults["ParenthesizedType"]["String"] & Defaults["TypeLiteral"]["String"] = "two";
const RemoveIntersectionTypeTypeLiteralStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeLiteralNumber: Defaults["ParenthesizedType"]["String"] & Defaults["TypeLiteral"]["Number"] = "two";
const RemoveIntersectionTypeTypeLiteralNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeLiteralBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["TypeLiteral"]["Boolean"] = "two";
const RemoveIntersectionTypeTypeLiteralBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTypeLiteralAny: Defaults["ParenthesizedType"]["String"] & Defaults["TypeLiteral"]["Any"] = "two";
const RemoveIntersectionTypeTypeLiteralAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithTupleTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["TupleType"]["Literal"] = "two";
const RemoveIntersectionTypeTupleTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTupleTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["TupleType"]["Object"] = "two";
const RemoveIntersectionTypeTupleTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTupleTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["TupleType"]["String"] = "two";
const RemoveIntersectionTypeTupleTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTupleTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["TupleType"]["Number"] = "two";
const RemoveIntersectionTypeTupleTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTupleTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["TupleType"]["Boolean"] = "two";
const RemoveIntersectionTypeTupleTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithTupleTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["TupleType"]["Any"] = "two";
const RemoveIntersectionTypeTupleTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithArrayTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["ArrayType"]["Literal"] = "two";
const RemoveIntersectionTypeArrayTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithArrayTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["ArrayType"]["Object"] = "two";
const RemoveIntersectionTypeArrayTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithArrayTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["ArrayType"]["String"] = "two";
const RemoveIntersectionTypeArrayTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithArrayTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["ArrayType"]["Number"] = "two";
const RemoveIntersectionTypeArrayTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithArrayTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["ArrayType"]["Boolean"] = "two";
const RemoveIntersectionTypeArrayTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithArrayTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["ArrayType"]["Any"] = "two";
const RemoveIntersectionTypeArrayTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithFunctionTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["FunctionType"]["Literal"] = "two";
const RemoveIntersectionTypeFunctionTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithFunctionTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["FunctionType"]["Object"] = "two";
const RemoveIntersectionTypeFunctionTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithFunctionTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["FunctionType"]["String"] = "two";
const RemoveIntersectionTypeFunctionTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithFunctionTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["FunctionType"]["Number"] = "two";
const RemoveIntersectionTypeFunctionTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithFunctionTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["FunctionType"]["Boolean"] = "two";
const RemoveIntersectionTypeFunctionTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithFunctionTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["FunctionType"]["Any"] = "two";
const RemoveIntersectionTypeFunctionTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeStringWithConstructorTypeLiteral: Defaults["ParenthesizedType"]["String"] & Defaults["ConstructorType"]["Literal"] = "two";
const RemoveIntersectionTypeConstructorTypeLiteralFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithConstructorTypeObject: Defaults["ParenthesizedType"]["String"] & Defaults["ConstructorType"]["Object"] = "two";
const RemoveIntersectionTypeConstructorTypeObjectFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithConstructorTypeString: Defaults["ParenthesizedType"]["String"] & Defaults["ConstructorType"]["String"] = "two";
const RemoveIntersectionTypeConstructorTypeStringFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithConstructorTypeNumber: Defaults["ParenthesizedType"]["String"] & Defaults["ConstructorType"]["Number"] = "two";
const RemoveIntersectionTypeConstructorTypeNumberFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithConstructorTypeBoolean: Defaults["ParenthesizedType"]["String"] & Defaults["ConstructorType"]["Boolean"] = "two";
const RemoveIntersectionTypeConstructorTypeBooleanFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"
const IntersectionTypeParenthesizedTypeStringWithConstructorTypeAny: Defaults["ParenthesizedType"]["String"] & Defaults["ConstructorType"]["Any"] = "two";
const RemoveIntersectionTypeConstructorTypeAnyFromParenthesizedTypeString: Defaults["ParenthesizedType"]["String"]= "two"

const IntersectionTypeParenthesizedTypeNumberWithParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithParenthesizedTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithParenthesizedTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithParenthesizedTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithTypeReferenceBuiltinLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferenceBuiltinObject: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferenceBuiltinString: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferenceBuiltinNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferenceBuiltinBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferenceBuiltinAny: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithTypeReferencePredefinedLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferencePredefinedObject: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferencePredefinedString: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferencePredefinedNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferencePredefinedBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeReferencePredefinedAny: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithUnionTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithUnionTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithUnionTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithUnionTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithUnionTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithUnionTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithIntersectionTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithIntersectionTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithIntersectionTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithIntersectionTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithIntersectionTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithIntersectionTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithTypeLiteralLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeLiteralObject: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeLiteralString: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeLiteralNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeLiteralBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTypeLiteralAny: Defaults["ParenthesizedType"]["Number"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithTupleTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTupleTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTupleTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTupleTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTupleTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithTupleTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithArrayTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithArrayTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithArrayTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithArrayTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithArrayTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithArrayTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithFunctionTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithFunctionTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithFunctionTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithFunctionTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithFunctionTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithFunctionTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeNumberWithConstructorTypeLiteral: Defaults["ParenthesizedType"]["Number"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithConstructorTypeObject: Defaults["ParenthesizedType"]["Number"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithConstructorTypeString: Defaults["ParenthesizedType"]["Number"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithConstructorTypeNumber: Defaults["ParenthesizedType"]["Number"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithConstructorTypeBoolean: Defaults["ParenthesizedType"]["Number"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2
const IntersectionTypeParenthesizedTypeNumberWithConstructorTypeAny: Defaults["ParenthesizedType"]["Number"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Number"]= 2

const IntersectionTypeParenthesizedTypeBooleanWithParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ParenthesizedType"]["Literal"] = true;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithParenthesizedTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ParenthesizedType"]["Object"] = true;
const RemoveIntersectionTypeParenthesizedTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithParenthesizedTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ParenthesizedType"]["String"] = true;
const RemoveIntersectionTypeParenthesizedTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ParenthesizedType"]["Number"] = true;
const RemoveIntersectionTypeParenthesizedTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ParenthesizedType"]["Boolean"] = true;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithParenthesizedTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ParenthesizedType"]["Any"] = true;
const RemoveIntersectionTypeParenthesizedTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithTypeReferenceBuiltinLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferenceBuiltinObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Object"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferenceBuiltinString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["String"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferenceBuiltinNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Number"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferenceBuiltinBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferenceBuiltinAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferenceBuiltin"]["Any"] = true;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithTypeReferencePredefinedLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Literal"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferencePredefinedObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Object"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferencePredefinedString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferencePredefined"]["String"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferencePredefinedNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Number"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferencePredefinedBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Boolean"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeReferencePredefinedAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeReferencePredefined"]["Any"] = true;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithUnionTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["UnionType"]["Literal"] = true;
const RemoveIntersectionTypeUnionTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithUnionTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["UnionType"]["Object"] = true;
const RemoveIntersectionTypeUnionTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithUnionTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["UnionType"]["String"] = true;
const RemoveIntersectionTypeUnionTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithUnionTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["UnionType"]["Number"] = true;
const RemoveIntersectionTypeUnionTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithUnionTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["UnionType"]["Boolean"] = true;
const RemoveIntersectionTypeUnionTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithUnionTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["UnionType"]["Any"] = true;
const RemoveIntersectionTypeUnionTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithIntersectionTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["IntersectionType"]["Literal"] = true;
const RemoveIntersectionTypeIntersectionTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithIntersectionTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["IntersectionType"]["Object"] = true;
const RemoveIntersectionTypeIntersectionTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithIntersectionTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["IntersectionType"]["String"] = true;
const RemoveIntersectionTypeIntersectionTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithIntersectionTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["IntersectionType"]["Number"] = true;
const RemoveIntersectionTypeIntersectionTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithIntersectionTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["IntersectionType"]["Boolean"] = true;
const RemoveIntersectionTypeIntersectionTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithIntersectionTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["IntersectionType"]["Any"] = true;
const RemoveIntersectionTypeIntersectionTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithTypeLiteralLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeLiteral"]["Literal"] = true;
const RemoveIntersectionTypeTypeLiteralLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeLiteralObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeLiteral"]["Object"] = true;
const RemoveIntersectionTypeTypeLiteralObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeLiteralString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeLiteral"]["String"] = true;
const RemoveIntersectionTypeTypeLiteralStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeLiteralNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeLiteral"]["Number"] = true;
const RemoveIntersectionTypeTypeLiteralNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeLiteralBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeLiteral"]["Boolean"] = true;
const RemoveIntersectionTypeTypeLiteralBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTypeLiteralAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TypeLiteral"]["Any"] = true;
const RemoveIntersectionTypeTypeLiteralAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithTupleTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TupleType"]["Literal"] = true;
const RemoveIntersectionTypeTupleTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTupleTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TupleType"]["Object"] = true;
const RemoveIntersectionTypeTupleTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTupleTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TupleType"]["String"] = true;
const RemoveIntersectionTypeTupleTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTupleTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TupleType"]["Number"] = true;
const RemoveIntersectionTypeTupleTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTupleTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TupleType"]["Boolean"] = true;
const RemoveIntersectionTypeTupleTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithTupleTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["TupleType"]["Any"] = true;
const RemoveIntersectionTypeTupleTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithArrayTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ArrayType"]["Literal"] = true;
const RemoveIntersectionTypeArrayTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithArrayTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ArrayType"]["Object"] = true;
const RemoveIntersectionTypeArrayTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithArrayTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ArrayType"]["String"] = true;
const RemoveIntersectionTypeArrayTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithArrayTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ArrayType"]["Number"] = true;
const RemoveIntersectionTypeArrayTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithArrayTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ArrayType"]["Boolean"] = true;
const RemoveIntersectionTypeArrayTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithArrayTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ArrayType"]["Any"] = true;
const RemoveIntersectionTypeArrayTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithFunctionTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["FunctionType"]["Literal"] = true;
const RemoveIntersectionTypeFunctionTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithFunctionTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["FunctionType"]["Object"] = true;
const RemoveIntersectionTypeFunctionTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithFunctionTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["FunctionType"]["String"] = true;
const RemoveIntersectionTypeFunctionTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithFunctionTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["FunctionType"]["Number"] = true;
const RemoveIntersectionTypeFunctionTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithFunctionTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["FunctionType"]["Boolean"] = true;
const RemoveIntersectionTypeFunctionTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithFunctionTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["FunctionType"]["Any"] = true;
const RemoveIntersectionTypeFunctionTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeBooleanWithConstructorTypeLiteral: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ConstructorType"]["Literal"] = true;
const RemoveIntersectionTypeConstructorTypeLiteralFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithConstructorTypeObject: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ConstructorType"]["Object"] = true;
const RemoveIntersectionTypeConstructorTypeObjectFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithConstructorTypeString: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ConstructorType"]["String"] = true;
const RemoveIntersectionTypeConstructorTypeStringFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithConstructorTypeNumber: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ConstructorType"]["Number"] = true;
const RemoveIntersectionTypeConstructorTypeNumberFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithConstructorTypeBoolean: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ConstructorType"]["Boolean"] = true;
const RemoveIntersectionTypeConstructorTypeBooleanFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true
const IntersectionTypeParenthesizedTypeBooleanWithConstructorTypeAny: Defaults["ParenthesizedType"]["Boolean"] & Defaults["ConstructorType"]["Any"] = true;
const RemoveIntersectionTypeConstructorTypeAnyFromParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Boolean"]= true

const IntersectionTypeParenthesizedTypeAnyWithParenthesizedTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["ParenthesizedType"]["Literal"] = 2;
const RemoveIntersectionTypeParenthesizedTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithParenthesizedTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["ParenthesizedType"]["Object"] = 2;
const RemoveIntersectionTypeParenthesizedTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithParenthesizedTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["ParenthesizedType"]["String"] = 2;
const RemoveIntersectionTypeParenthesizedTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithParenthesizedTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["ParenthesizedType"]["Number"] = 2;
const RemoveIntersectionTypeParenthesizedTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithParenthesizedTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["ParenthesizedType"]["Boolean"] = 2;
const RemoveIntersectionTypeParenthesizedTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["ParenthesizedType"]["Any"] = 2;
const RemoveIntersectionTypeParenthesizedTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithTypeReferenceBuiltinLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferenceBuiltinObject: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferenceBuiltinString: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferenceBuiltin"]["String"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferenceBuiltinNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferenceBuiltinBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferenceBuiltinAny: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferenceBuiltin"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferenceBuiltinAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithTypeReferencePredefinedLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferencePredefined"]["Literal"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferencePredefinedObject: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferencePredefined"]["Object"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferencePredefinedString: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferencePredefined"]["String"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferencePredefinedNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferencePredefined"]["Number"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferencePredefinedBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferencePredefined"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeReferencePredefinedAny: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeReferencePredefined"]["Any"] = 2;
const RemoveIntersectionTypeTypeReferencePredefinedAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithUnionTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["UnionType"]["Literal"] = 2;
const RemoveIntersectionTypeUnionTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithUnionTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["UnionType"]["Object"] = 2;
const RemoveIntersectionTypeUnionTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithUnionTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["UnionType"]["String"] = 2;
const RemoveIntersectionTypeUnionTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithUnionTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["UnionType"]["Number"] = 2;
const RemoveIntersectionTypeUnionTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithUnionTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["UnionType"]["Boolean"] = 2;
const RemoveIntersectionTypeUnionTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithUnionTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["UnionType"]["Any"] = 2;
const RemoveIntersectionTypeUnionTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithIntersectionTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["IntersectionType"]["Literal"] = 2;
const RemoveIntersectionTypeIntersectionTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithIntersectionTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["IntersectionType"]["Object"] = 2;
const RemoveIntersectionTypeIntersectionTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithIntersectionTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["IntersectionType"]["String"] = 2;
const RemoveIntersectionTypeIntersectionTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithIntersectionTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["IntersectionType"]["Number"] = 2;
const RemoveIntersectionTypeIntersectionTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithIntersectionTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["IntersectionType"]["Boolean"] = 2;
const RemoveIntersectionTypeIntersectionTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithIntersectionTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["IntersectionType"]["Any"] = 2;
const RemoveIntersectionTypeIntersectionTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithTypeLiteralLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeLiteral"]["Literal"] = 2;
const RemoveIntersectionTypeTypeLiteralLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeLiteralObject: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeLiteral"]["Object"] = 2;
const RemoveIntersectionTypeTypeLiteralObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeLiteralString: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeLiteral"]["String"] = 2;
const RemoveIntersectionTypeTypeLiteralStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeLiteralNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeLiteral"]["Number"] = 2;
const RemoveIntersectionTypeTypeLiteralNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeLiteralBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeLiteral"]["Boolean"] = 2;
const RemoveIntersectionTypeTypeLiteralBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTypeLiteralAny: Defaults["ParenthesizedType"]["Any"] & Defaults["TypeLiteral"]["Any"] = 2;
const RemoveIntersectionTypeTypeLiteralAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithTupleTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["TupleType"]["Literal"] = 2;
const RemoveIntersectionTypeTupleTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTupleTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["TupleType"]["Object"] = 2;
const RemoveIntersectionTypeTupleTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTupleTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["TupleType"]["String"] = 2;
const RemoveIntersectionTypeTupleTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTupleTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["TupleType"]["Number"] = 2;
const RemoveIntersectionTypeTupleTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTupleTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["TupleType"]["Boolean"] = 2;
const RemoveIntersectionTypeTupleTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithTupleTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["TupleType"]["Any"] = 2;
const RemoveIntersectionTypeTupleTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithArrayTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["ArrayType"]["Literal"] = 2;
const RemoveIntersectionTypeArrayTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithArrayTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["ArrayType"]["Object"] = 2;
const RemoveIntersectionTypeArrayTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithArrayTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["ArrayType"]["String"] = 2;
const RemoveIntersectionTypeArrayTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithArrayTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["ArrayType"]["Number"] = 2;
const RemoveIntersectionTypeArrayTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithArrayTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["ArrayType"]["Boolean"] = 2;
const RemoveIntersectionTypeArrayTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithArrayTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["ArrayType"]["Any"] = 2;
const RemoveIntersectionTypeArrayTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithFunctionTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["FunctionType"]["Literal"] = 2;
const RemoveIntersectionTypeFunctionTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithFunctionTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["FunctionType"]["Object"] = 2;
const RemoveIntersectionTypeFunctionTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithFunctionTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["FunctionType"]["String"] = 2;
const RemoveIntersectionTypeFunctionTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithFunctionTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["FunctionType"]["Number"] = 2;
const RemoveIntersectionTypeFunctionTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithFunctionTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["FunctionType"]["Boolean"] = 2;
const RemoveIntersectionTypeFunctionTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithFunctionTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["FunctionType"]["Any"] = 2;
const RemoveIntersectionTypeFunctionTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

const IntersectionTypeParenthesizedTypeAnyWithConstructorTypeLiteral: Defaults["ParenthesizedType"]["Any"] & Defaults["ConstructorType"]["Literal"] = 2;
const RemoveIntersectionTypeConstructorTypeLiteralFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithConstructorTypeObject: Defaults["ParenthesizedType"]["Any"] & Defaults["ConstructorType"]["Object"] = 2;
const RemoveIntersectionTypeConstructorTypeObjectFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithConstructorTypeString: Defaults["ParenthesizedType"]["Any"] & Defaults["ConstructorType"]["String"] = 2;
const RemoveIntersectionTypeConstructorTypeStringFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithConstructorTypeNumber: Defaults["ParenthesizedType"]["Any"] & Defaults["ConstructorType"]["Number"] = 2;
const RemoveIntersectionTypeConstructorTypeNumberFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithConstructorTypeBoolean: Defaults["ParenthesizedType"]["Any"] & Defaults["ConstructorType"]["Boolean"] = 2;
const RemoveIntersectionTypeConstructorTypeBooleanFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2
const IntersectionTypeParenthesizedTypeAnyWithConstructorTypeAny: Defaults["ParenthesizedType"]["Any"] & Defaults["ConstructorType"]["Any"] = 2;
const RemoveIntersectionTypeConstructorTypeAnyFromParenthesizedTypeAny: Defaults["ParenthesizedType"]["Any"]= 2

